/* Content library (aircraft, history, milestones, preflight, certificates, career paths, featured airports)
   Part of AvHype Aviation Education. This file is loaded by the page at startup
   and MUST sit in the same folder as the .html file when deployed.
   Safe to edit this section's content directly. */
window.__AV_CERTIFICATES__ = [
  { id: "student", name: "Student Pilot", kind: "Certificate", path: "airplane",
    summary: "Entry credential allowing supervised solo training. No minimum age to begin training; 16 to solo an airplane (14 for gliders/balloons).",
    eligibility: "Apply via IACRA; instructor endorses for solo. English proficiency required.",
    source: "cfr61" },
  { id: "sport", name: "Sport Pilot", kind: "Certificate", path: "airplane",
    summary: "Fly light-sport aircraft with reduced training time and (often) without a medical, using a valid U.S. driver's license under conditions.",
    eligibility: "17+ (16 gliders), pass knowledge & practical tests, meet aeronautical experience.",
    source: "cfr61" },
  { id: "recpilot", name: "Recreational Pilot", kind: "Certificate", path: "airplane",
    summary: "Limited private-style privileges with fewer hours but more restrictions on distance, airspace, and aircraft.",
    eligibility: "17+, knowledge & practical tests, third-class medical or BasicMed where applicable.",
    source: "cfr61" },
  { id: "private", name: "Private Pilot", kind: "Certificate", path: "airplane",
    summary: "Carry passengers (not for compensation) day and night, cross-country. The foundational 'real' certificate for most pilots.",
    eligibility: "17+, English, medical/BasicMed, min 40 hrs (often more), knowledge test, checkride.",
    source: "cfr61" },
  { id: "commercial", name: "Commercial Pilot", kind: "Certificate", path: "airplane",
    summary: "Fly for compensation or hire within regulatory limits; higher precision standards and additional maneuvers.",
    eligibility: "18+, second-class medical for many roles, 250 hrs typical, knowledge test, checkride.",
    source: "cfr61" },
  { id: "atp", name: "Airline Transport Pilot", kind: "Certificate", path: "airplane",
    summary: "Highest pilot certificate; required to act as airline captain (and often first officer). Demanding experience and testing.",
    eligibility: "23+ (restricted ATP younger), first-class medical for airline duty, 1500 hrs typical, ATP-CTP, checkride.",
    source: "cfr61" },
  { id: "remote", name: "Remote Pilot (sUAS)", kind: "Certificate", path: "drone",
    summary: "Authorizes commercial small-drone operations under Part 107.",
    eligibility: "16+, English, UAG knowledge test, TSA vetting, recurrent training every 24 months.",
    source: "cfr107" },
  { id: "cfi-cert", name: "Flight Instructor (CFI)", kind: "Certificate", path: "airplane",
    summary: "Authorizes teaching and endorsing student pilots. Requires mastery plus the ability to teach.",
    eligibility: "18+, commercial or ATP, FOI & instructor knowledge tests, intensive checkride.",
    source: "cfr61" },
  { id: "gi-cert", name: "Ground Instructor", kind: "Certificate", path: "airplane",
    summary: "Authorizes providing and endorsing ground (knowledge) training. Basic, Advanced, and Instrument levels.",
    eligibility: "18+, pass required knowledge tests; no flight test for ground instructor.",
    source: "cfr61" }
];

window.__AV_CAREER_PATHS__ = [
  { id: "hobby", name: "Hobby Pilot", path: "airplane",
    steps: ["Aviation 000", "Sport/Recreational/Private", "Build personal proficiency", "Add ratings as interests grow"],
    note: "Fly for personal enjoyment. No compensation; focus on currency and skill." },
  { id: "drone-biz", name: "Drone Business Operator", path: "drone",
    steps: ["Part 107", "Pick a niche (real estate, mapping, inspection)", "SOPs + insurance", "Build a portfolio and clients"],
    note: "Hiring/contracts vary by client and insurer; many require proof of Part 107 and liability coverage." },
  { id: "cfi-build", name: "CFI Time-Building Route", path: "airplane",
    steps: ["Private", "Instrument", "Commercial", "CFI / CFII / MEI", "Instruct to build hours toward ATP"],
    note: "A common path to airline minimums. Pace depends on student availability and weather." },
  { id: "p135", name: "Part 135 / Charter Awareness", path: "airplane",
    steps: ["Commercial + Instrument", "Multi-engine", "Meet operator & insurance minimums", "Type/role training"],
    note: "Requirements vary widely by operator, aircraft, and insurance." },
  { id: "airline", name: "Airline Pathway", path: "airplane",
    steps: ["Private → Instrument → Commercial → Multi", "Build hours (often via CFI)", "ATP / R-ATP + ATP-CTP", "Regional → major"],
    note: "Hiring depends on hours, certificates, medical, record, and market conditions." },
  { id: "corp", name: "Corporate Aviation", path: "airplane",
    steps: ["Commercial/ATP", "Type ratings", "Networking & operator standards", "Specialized aircraft training"],
    note: "Often relationship- and type-driven; standards set by the operator and insurer." },
  { id: "heli-ops", name: "Helicopter EMS / Law / Utility Awareness", path: "helicopter",
    steps: ["Helicopter Private → Commercial", "Build turbine/operational experience", "Specialized mission training"],
    note: "EMS, law enforcement, and utility roles have demanding, employer-specific requirements." },
  { id: "media", name: "Aerial Photography & Mapping", path: "drone",
    steps: ["Part 107", "Sensor/payload skills", "Data processing workflow", "Client deliverables & licensing"],
    note: "Technical data skills often matter as much as flying; deliverables drive the business." },
  { id: "publicsafety", name: "Public Safety Drone Work", path: "drone",
    steps: ["Part 107", "Agency program & policy", "Thermal/SAR training", "Interagency coordination"],
    note: "Usually performed under an agency program with specific authorizations and policies." }
];

window.__AV_AIRCRAFT__ = [
  { id: "montgolfier", name: "Montgolfier Balloon", maker: "Montgolfier Brothers", cat: "balloon", role: "Balloon", year: 1783, era: "Pioneers",
    blurb: "The first aircraft to carry humans aloft.",
    body: "In 1783 the Montgolfier brothers demonstrated a hot air balloon that carried the first human passengers over Paris. It opened the age of flight more than a century before powered airplanes, proving people could leave the ground in a controlled craft.",
    specs: [["First human flight", "1783"], ["Type", "Hot air balloon"], ["Lift", "Heated air"], ["Origin", "France"]] },
  { id: "wright-flyer", name: "Wright Flyer", maker: "Wright Brothers", cat: "airplane", role: "Experimental", year: 1903, era: "Pioneers",
    blurb: "The first powered, controlled, sustained airplane flight.",
    body: "On December 17, 1903, at Kitty Hawk, North Carolina, the Wright brothers flew the first powered, controlled, and sustained heavier-than-air flight. Their breakthrough was not just power but three-axis control, the foundation every airplane still uses today.",
    specs: [["First flight", "Dec 17, 1903"], ["Engine", "About 12 hp"], ["First hop", "About 120 ft, 12 sec"], ["Crew", "1"]] },
  { id: "bleriot-xi", name: "Blériot XI", maker: "Louis Blériot", cat: "airplane", role: "Pioneer", year: 1909, era: "Pioneers",
    blurb: "First airplane to cross the English Channel.",
    body: "In 1909 Louis Blériot flew his Blériot XI across the English Channel, the first heavier-than-air crossing. The flight showed the airplane could cover real distances over water and made Blériot a household name across Europe.",
    specs: [["Channel crossing", "1909"], ["Engine", "About 25 hp"], ["Layout", "Monoplane"], ["Origin", "France"]] },
  { id: "ford-trimotor", name: "Ford Trimotor", maker: "Ford", cat: "airplane", role: "Airliner", year: 1926, era: "Golden Age",
    blurb: "An early all-metal US airliner, the 'Tin Goose.'",
    body: "The Ford Trimotor was a rugged, all-metal, three-engine airliner that helped establish early US passenger service. Its corrugated metal skin and reliability made air travel feel practical to a public still wary of flying.",
    specs: [["Introduced", "1926"], ["Engines", "Three radials"], ["Skin", "Corrugated metal"], ["Role", "Passenger transport"]] },
  { id: "spirit-stlouis", name: "Spirit of St. Louis", maker: "Ryan Airlines", cat: "airplane", role: "Record", year: 1927, era: "Golden Age",
    blurb: "Lindbergh's first solo nonstop New York to Paris flight.",
    body: "In May 1927 Charles Lindbergh flew the custom Ryan monoplane Spirit of St. Louis alone and nonstop from New York to Paris, roughly thirty-three and a half hours. The flight electrified the world and accelerated public investment in aviation.",
    specs: [["Transatlantic", "May 1927"], ["Duration", "About 33.5 hours"], ["Engine", "Wright Whirlwind"], ["Crew", "1 (Lindbergh)"]] },
  { id: "dc3", name: "Douglas DC-3", maker: "Douglas", cat: "airplane", role: "Airliner", year: 1935, era: "Golden Age",
    blurb: "The airliner that made passenger travel profitable.",
    body: "First flown in 1935, the DC-3 was reliable and economical enough to make airlines profitable carrying passengers, not just mail. Tens of thousands were built, many serving as the military C-47 in World War II, and some still fly today.",
    specs: [["First flight", "1935"], ["Engines", "Two radials"], ["Passengers", "About 21"], ["Military name", "C-47"]] },
  { id: "spitfire", name: "Supermarine Spitfire", maker: "Supermarine", cat: "airplane", role: "Fighter", year: 1936, era: "World War II",
    blurb: "The iconic British fighter of the Battle of Britain.",
    body: "Designed by R. J. Mitchell and first flown in 1936, the Spitfire became a symbol of British defense during the 1940 Battle of Britain. Its elliptical wing and Rolls-Royce Merlin engine gave it the agility and performance that made it legendary.",
    specs: [["First flight", "1936"], ["Engine", "Rolls-Royce Merlin"], ["Wing", "Elliptical"], ["Role", "Interceptor fighter"]] },
  { id: "p51", name: "P-51 Mustang", maker: "North American Aviation", cat: "airplane", role: "Fighter", year: 1940, era: "World War II",
    blurb: "The long-range escort fighter that changed the air war.",
    body: "The P-51 Mustang, especially once fitted with the Merlin engine, combined speed with the range to escort bombers deep into Germany and back. That long reach made daylight strategic bombing far more survivable and reshaped the air campaign.",
    specs: [["First flight", "1940"], ["Engine", "Packard Merlin (later)"], ["Strength", "Long range"], ["Role", "Escort fighter"]] },
  { id: "b17", name: "B-17 Flying Fortress", maker: "Boeing", cat: "airplane", role: "Bomber", year: 1935, era: "World War II",
    blurb: "The heavily armed US heavy bomber of World War II.",
    body: "The four-engine B-17 was a mainstay of the US daylight strategic bombing campaign in Europe. Bristling with defensive guns and able to absorb heavy damage, it earned its 'Flying Fortress' name and became an enduring symbol of the air war.",
    specs: [["First flight", "1935"], ["Engines", "Four radials"], ["Trait", "Heavy defensive armament"], ["Role", "Strategic bomber"]] },
  { id: "bell-x1", name: "Bell X-1", maker: "Bell Aircraft", cat: "airplane", role: "Experimental", year: 1947, era: "Jet Age",
    blurb: "First aircraft to exceed the speed of sound in level flight.",
    body: "In October 1947 Chuck Yeager flew the rocket-powered Bell X-1 past the speed of sound in level flight, breaking the so-called sound barrier. Air-launched from a bomber, the X-1 opened the era of supersonic flight and modern flight research.",
    specs: [["Supersonic", "Oct 14, 1947"], ["Power", "Rocket engine"], ["Pilot", "Chuck Yeager"], ["Launch", "Air-dropped"]] },
  { id: "comet", name: "de Havilland Comet", maker: "de Havilland", cat: "airplane", role: "Airliner", year: 1949, era: "Jet Age",
    blurb: "The world's first jet airliner.",
    body: "First flown in 1949 and in service by 1952, the Comet was the first commercial jet airliner. Early fatal accidents traced to metal fatigue led to hard-won lessons in structural design that made later jetliners far safer.",
    specs: [["First flight", "1949"], ["In service", "1952"], ["Type", "Jet airliner"], ["Legacy", "Fatigue lessons"]] },
  { id: "707", name: "Boeing 707", maker: "Boeing", cat: "airplane", role: "Airliner", year: 1957, era: "Jet Age",
    blurb: "Brought the jet age to mainstream air travel.",
    body: "The Boeing 707 helped make jet travel the norm for the traveling public from the late 1950s. Fast and far-reaching, it shrank the world and set the template for the modern jet airliner.",
    specs: [["First flight", "1957"], ["Engines", "Four jets"], ["Impact", "Mainstream jet travel"], ["Role", "Airliner"]] },
  { id: "sr71", name: "Lockheed SR-71 Blackbird", maker: "Lockheed", cat: "airplane", role: "Reconnaissance", year: 1964, era: "Jet Age",
    blurb: "The fastest air-breathing crewed aircraft.",
    body: "Built largely of titanium and first flown in 1964, the SR-71 cruised at more than three times the speed of sound at extreme altitude for strategic reconnaissance. It often outran threats simply by accelerating, and it still holds speed records.",
    specs: [["First flight", "1964"], ["Speed", "Above Mach 3"], ["Material", "Mostly titanium"], ["Role", "Reconnaissance"]] },
  { id: "747", name: "Boeing 747", maker: "Boeing", cat: "airplane", role: "Airliner", year: 1969, era: "Jet Age",
    blurb: "The first wide-body 'jumbo jet.'",
    body: "First flown in 1969, the 747 was the first wide-body airliner, with its distinctive upper-deck hump and enormous capacity. It made long-haul travel affordable for millions and reigned for decades as the 'Queen of the Skies.'",
    specs: [["First flight", "1969"], ["Engines", "Four jets"], ["Feature", "Upper-deck hump"], ["Role", "Wide-body airliner"]] },
  { id: "concorde", name: "Concorde", maker: "Aérospatiale / BAC", cat: "airplane", role: "Airliner", year: 1969, era: "Jet Age",
    blurb: "The supersonic passenger airliner.",
    body: "A joint British and French project first flown in 1969, Concorde carried passengers at about twice the speed of sound, crossing the Atlantic in a few hours. Its droop nose and slender delta wing made it unmistakable; it served from 1976 to 2003.",
    specs: [["First flight", "1969"], ["Speed", "About Mach 2"], ["Service", "1976 to 2003"], ["Wing", "Delta"]] },
  { id: "j3cub", name: "Piper J-3 Cub", maker: "Piper", cat: "airplane", role: "Trainer", year: 1938, era: "Golden Age",
    blurb: "The classic yellow taildragger trainer.",
    body: "Simple, light, and famously bright yellow, the Piper J-3 Cub taught generations of pilots to fly from the late 1930s. Its forgiving handling and tandem seating made it a beloved icon of light aviation.",
    specs: [["Introduced", "1938"], ["Seating", "Tandem, two"], ["Gear", "Taildragger"], ["Role", "Primary trainer"]] },
  { id: "c172", name: "Cessna 172 Skyhawk", maker: "Cessna", cat: "airplane", role: "Trainer", year: 1955, era: "Jet Age",
    blurb: "The most-produced aircraft in history.",
    body: "Introduced in the mid-1950s, the four-seat, high-wing Cessna 172 became the most-produced aircraft ever and the quintessential trainer. Its stability and simplicity have made it the airplane countless pilots first solo in.",
    specs: [["Introduced", "1955"], ["Seating", "Four"], ["Wing", "High-wing"], ["Claim", "Most-produced aircraft"]] },
  { id: "737", name: "Boeing 737", maker: "Boeing", cat: "airplane", role: "Airliner", year: 1967, era: "Jet Age",
    blurb: "The best-selling jet airliner family.",
    body: "First flown in 1967, the narrow-body 737 became the best-selling commercial jet airliner family, continually updated across generations. It is a workhorse of short and medium routes for airlines worldwide.",
    specs: [["First flight", "1967"], ["Engines", "Two jets"], ["Class", "Narrow-body"], ["Status", "Best-selling jetliner"]] },
  { id: "f16", name: "F-16 Fighting Falcon", maker: "General Dynamics / Lockheed Martin", cat: "airplane", role: "Fighter", year: 1974, era: "Modern Era",
    blurb: "A widely exported multirole fighter.",
    body: "First flown in 1974, the F-16 introduced fly-by-wire controls, a bubble canopy, and a reclined seat for high-G agility. Affordable and capable, it became one of the most widely operated fighters in the world.",
    specs: [["First flight", "1974"], ["Controls", "Fly-by-wire"], ["Canopy", "Bubble"], ["Role", "Multirole fighter"]] },
  { id: "a380", name: "Airbus A380", maker: "Airbus", cat: "airplane", role: "Airliner", year: 2005, era: "Modern Era",
    blurb: "The largest passenger airliner ever built.",
    body: "First flown in 2005, the double-deck A380 is the largest passenger airliner, carrying very high numbers of travelers on dense long-haul routes. Its full-length two decks set it apart from every other airliner.",
    specs: [["First flight", "2005"], ["Engines", "Four jets"], ["Decks", "Full-length double"], ["Claim", "Largest passenger airliner"]] },
  { id: "vs300", name: "Sikorsky VS-300", maker: "Sikorsky", cat: "rotorcraft", role: "Experimental", year: 1939, era: "World War II",
    blurb: "Pioneered the standard single-rotor helicopter layout.",
    body: "Igor Sikorsky's VS-300, flown from 1939, established the configuration of a single main rotor with a small anti-torque tail rotor. That layout became the template for most helicopters built ever since.",
    specs: [["First flight", "1939"], ["Layout", "Single main rotor"], ["Anti-torque", "Tail rotor"], ["Designer", "Igor Sikorsky"]] },
  { id: "bell47", name: "Bell 47", maker: "Bell", cat: "rotorcraft", role: "Utility", year: 1945, era: "Jet Age",
    blurb: "The first helicopter certified for civilian use.",
    body: "The Bell 47, with its distinctive bubble canopy and open lattice tail, was the first helicopter certified for civil use in the mid-1940s. It is widely remembered for its medical-evacuation role and its appearance on screen.",
    specs: [["Civil certification", "1946"], ["Feature", "Bubble canopy"], ["Tail", "Open lattice"], ["Role", "Light utility"]] },
  { id: "uh1", name: "Bell UH-1 Iroquois (Huey)", maker: "Bell", cat: "rotorcraft", role: "Utility", year: 1956, era: "Jet Age",
    blurb: "The iconic utility helicopter of the Vietnam era.",
    body: "First flown in 1956, the UH-1, universally called the Huey, became the defining helicopter of the Vietnam War for troop transport, medevac, and support. Its distinctive rotor sound is instantly recognizable.",
    specs: [["First flight", "1956"], ["Nickname", "Huey"], ["Roles", "Transport and medevac"], ["Era", "Vietnam War"]] },
  { id: "r44", name: "Robinson R44", maker: "Robinson Helicopter", cat: "rotorcraft", role: "Light", year: 1990, era: "Modern Era",
    blurb: "One of the world's most popular civil helicopters.",
    body: "First flown in 1990, the piston-powered, four-seat Robinson R44 became one of the most-produced civil helicopters in the world. Its relatively low cost made helicopter training and private ownership far more accessible.",
    specs: [["First flight", "1990"], ["Seating", "Four"], ["Engine", "Piston"], ["Role", "Training and private"]] },
  { id: "v22", name: "Bell Boeing V-22 Osprey", maker: "Bell Boeing", cat: "poweredlift", role: "Tiltrotor", year: 1989, era: "Modern Era",
    blurb: "A tiltrotor that hovers like a helicopter and cruises like a turboprop.",
    body: "First flown in 1989, the V-22 is a tiltrotor: it takes off and lands vertically like a helicopter, then tilts its rotors forward to cruise like an airplane. It is a leading example of the powered-lift category.",
    specs: [["First flight", "1989"], ["Type", "Tiltrotor"], ["Category", "Powered-lift"], ["Trait", "Vertical takeoff, winged cruise"]] },
  { id: "sgs233", name: "Schweizer SGS 2-33", maker: "Schweizer", cat: "glider", role: "Trainer", year: 1967, era: "Modern Era",
    blurb: "A classic two-seat training sailplane.",
    body: "The Schweizer SGS 2-33 is a rugged two-seat training glider that introduced many North American pilots to soaring. Forgiving and durable, it became a fixture at glider clubs and schools for decades.",
    specs: [["Introduced", "1967"], ["Seating", "Two"], ["Type", "Training sailplane"], ["Trait", "Rugged and forgiving"]] },
  { id: "p38", name: "Lockheed P-38 Lightning", maker: "Lockheed", cat: "airplane", role: "Fighter", year: 1939, era: "World War II",
    blurb: "The distinctive twin-boom WWII fighter.",
    body: "The P-38 was a fast, twin-engine, twin-boom fighter used across every theater of World War II for escort, reconnaissance, and ground attack. Its unmistakable shape and high performance made it one of the war's most recognizable aircraft.",
    specs: [["First flight", "1939"], ["Engines", "Two"], ["Shape", "Twin-boom"], ["Roles", "Fighter, recon"]] },
  { id: "b25", name: "North American B-25 Mitchell", maker: "North American Aviation", cat: "airplane", role: "Bomber", year: 1940, era: "World War II",
    blurb: "The medium bomber of the Doolittle Raid.",
    body: "The twin-engine B-25 was a versatile medium bomber best remembered for the 1942 Doolittle Raid, when sixteen launched from an aircraft carrier to strike Japan. Rugged and adaptable, it served in every theater of the war.",
    specs: [["First flight", "1940"], ["Engines", "Two"], ["Class", "Medium bomber"], ["Famous for", "Doolittle Raid"]] },
  { id: "bonanza", name: "Beechcraft Bonanza", maker: "Beechcraft", cat: "airplane", role: "General aviation", year: 1947, era: "Jet Age",
    blurb: "A high-performance single with a record-long production run.",
    body: "Introduced in 1947, the Bonanza became famous for its early V-tail and its speed and refinement as a personal aircraft. It holds one of the longest continuous production runs of any aircraft in history.",
    specs: [["Introduced", "1947"], ["Early tail", "V-tail"], ["Class", "High-performance single"], ["Note", "Very long production run"]] },
  { id: "beaver", name: "de Havilland Canada DHC-2 Beaver", maker: "de Havilland Canada", cat: "airplane", role: "Bush plane", year: 1947, era: "Jet Age",
    blurb: "The legendary short-field bush plane.",
    body: "The DHC-2 Beaver is a rugged single-engine aircraft beloved for its short takeoff and landing ability and its capacity to operate from remote strips, lakes, and snow. It became an icon of bush flying around the world.",
    specs: [["Introduced", "1947"], ["Strength", "Short-field STOL"], ["Operates from", "Land, water, snow"], ["Role", "Bush utility"]] },
  { id: "c152", name: "Cessna 152", maker: "Cessna", cat: "airplane", role: "Trainer", year: 1977, era: "Modern Era",
    blurb: "A ubiquitous two-seat trainer.",
    body: "The two-seat Cessna 152 followed the 150 as one of the most widely used training aircraft, valued for its simplicity, economy, and forgiving handling. Generations of pilots have learned the basics in one.",
    specs: [["Introduced", "1977"], ["Seating", "Two"], ["Wing", "High-wing"], ["Role", "Primary trainer"]] },
  { id: "sr22", name: "Cirrus SR22", maker: "Cirrus", cat: "airplane", role: "General aviation", year: 2001, era: "Modern Era",
    blurb: "A composite single with a whole-airframe parachute.",
    body: "The Cirrus SR22 became one of the best-selling general aviation airplanes thanks to its modern composite design, advanced avionics, and a whole-airframe parachute that can lower the entire aircraft to the ground in an emergency. It helped reshape expectations for personal aircraft safety.",
    specs: [["Introduced", "2001"], ["Build", "Composite"], ["Safety", "Whole-airframe parachute"], ["Class", "High-performance single"]] },
  { id: "a320", name: "Airbus A320", maker: "Airbus", cat: "airplane", role: "Airliner", year: 1987, era: "Modern Era",
    blurb: "Brought fly-by-wire to everyday airliners.",
    body: "First flown in 1987, the narrow-body A320 introduced digital fly-by-wire flight controls and sidestick controls to mainstream airliners. It became one of the best-selling jet families in the world, the main rival to the Boeing 737.",
    specs: [["First flight", "1987"], ["Controls", "Fly-by-wire"], ["Class", "Narrow-body"], ["Rival", "Boeing 737"]] },
  { id: "777", name: "Boeing 777", maker: "Boeing", cat: "airplane", role: "Airliner", year: 1994, era: "Modern Era",
    blurb: "A long-range twinjet workhorse.",
    body: "First flown in 1994, the 777 is a large, long-range twin-engine airliner and was Boeing's first fly-by-wire jet. Its efficiency and range made twin-engine aircraft the standard for long overwater routes.",
    specs: [["First flight", "1994"], ["Engines", "Two (large)"], ["Range", "Long-haul"], ["First Boeing", "Fly-by-wire"]] },
  { id: "787", name: "Boeing 787 Dreamliner", maker: "Boeing", cat: "airplane", role: "Airliner", year: 2009, era: "Modern Era",
    blurb: "A fuel-efficient composite airliner.",
    body: "First flown in 2009, the 787 uses a largely carbon-composite structure and modern engines for high fuel efficiency on long routes. Features like higher cabin humidity and larger windows were aimed at passenger comfort.",
    specs: [["First flight", "2009"], ["Structure", "Carbon composite"], ["Focus", "Fuel efficiency"], ["Class", "Wide-body"]] },
  { id: "uh60", name: "Sikorsky UH-60 Black Hawk", maker: "Sikorsky", cat: "rotorcraft", role: "Utility", year: 1974, era: "Modern Era",
    blurb: "A widely used military utility helicopter.",
    body: "First flown in 1974, the UH-60 Black Hawk is a twin-engine utility helicopter used for troop transport, medical evacuation, and many other roles. It has become one of the most widely operated military helicopters in the world.",
    specs: [["First flight", "1974"], ["Engines", "Two"], ["Roles", "Transport, medevac"], ["Use", "Military utility"]] },
  { id: "ch47", name: "Boeing CH-47 Chinook", maker: "Boeing", cat: "rotorcraft", role: "Heavy lift", year: 1961, era: "Jet Age",
    blurb: "A tandem-rotor heavy-lift helicopter.",
    body: "First flown in 1961, the Chinook uses two large rotors front and back instead of a tail rotor, giving it great lifting power for troops and heavy cargo. Its longevity has kept it in service for decades.",
    specs: [["First flight", "1961"], ["Rotors", "Tandem (two)"], ["Strength", "Heavy lift"], ["Role", "Cargo and troops"]] },
  { id: "r22", name: "Robinson R22", maker: "Robinson Helicopter", cat: "rotorcraft", role: "Trainer", year: 1979, era: "Modern Era",
    blurb: "A popular two-seat training helicopter.",
    body: "Introduced in the late 1970s, the lightweight two-seat Robinson R22 became one of the most common helicopter trainers in the world. Its low operating cost made helicopter flight training far more accessible.",
    specs: [["Introduced", "Late 1970s"], ["Seating", "Two"], ["Engine", "Piston"], ["Role", "Helicopter trainer"]] },

  /* ---- Gliders ---- */
  { id: "ask21", name: "Schleicher ASK 21", maker: "Alexander Schleicher", cat: "glider", role: "Trainer", year: 1979, era: "Modern Era",
    blurb: "One of the world's most widely used training gliders.",
    body: "The ASK 21 is a two-seat training glider flown by clubs and schools around the world, valued for its docile handling and strength. Its tandem cockpit and solid performance make it a favorite for early instruction and basic aerobatics alike.",
    specs: [["Introduced", "1979"], ["Seating", "Two (tandem)"], ["Type", "Training sailplane"], ["Trait", "Docile, widely used"]] },
  { id: "sgs126", name: "Schweizer SGS 1-26", maker: "Schweizer", cat: "glider", role: "Sport", year: 1954, era: "Jet Age",
    blurb: "A classic single-seat club sailplane.",
    body: "Produced for decades, the single-seat SGS 1-26 became a staple of American soaring clubs and one-design racing. Simple and affordable, it gave many pilots their first solo cross-country soaring flights.",
    specs: [["Introduced", "1954"], ["Seating", "One"], ["Type", "Club sailplane"], ["Trait", "One-design racing"]] },
  { id: "perlan2", name: "Airbus Perlan 2", maker: "Perlan Project / Airbus", cat: "glider", role: "Research", year: 2015, era: "Modern Era",
    blurb: "A pressurized glider that soared to the edge of space.",
    body: "The engineless, pressurized Perlan 2 rides rare stratospheric mountain waves to extreme altitude, reaching 76,124 feet over the Andes in 2018 — higher than the U-2's level-flight record. It was built to study flight in air as thin as the surface of Mars.",
    specs: [["Record", "76,124 ft (2018)"], ["Power", "None (engineless)"], ["Lift", "Stratospheric mountain wave"], ["Wingspan", "~84 ft"]] },

  /* ---- Lighter-than-air ---- */
  { id: "hotair", name: "Hot-Air Balloon", maker: "Various", cat: "balloon", role: "Sport", year: 1960, era: "Jet Age",
    blurb: "The modern sport descendant of the first aircraft.",
    body: "A modern hot-air balloon heats the air inside a nylon envelope with a propane burner; warm air is lighter than the cooler air around it, so the balloon rises. The pilot controls altitude with the burner and a vent and steers only by finding winds at different heights.",
    specs: [["Lift", "Heated air"], ["Fuel", "Propane"], ["Control", "Altitude only"], ["Category", "Lighter-than-air"]] },
  { id: "gasballoon", name: "Gas Balloon", maker: "Various", cat: "balloon", role: "Sport", year: 1783, era: "Pioneers",
    blurb: "A balloon lifted by a light gas instead of heat.",
    body: "A gas balloon is filled with a gas lighter than air — historically hydrogen, today usually helium — and needs no burner, so it can stay aloft for days. Gas balloons hold the great distance and duration records and still race in events like the Gordon Bennett Cup.",
    specs: [["Lift", "Helium or hydrogen"], ["Endurance", "Days"], ["Records", "Distance & duration"], ["Category", "Lighter-than-air"]] },
  { id: "zeppelinnt", name: "Zeppelin NT", maker: "Zeppelin", cat: "balloon", role: "Airship", year: 1997, era: "Modern Era",
    blurb: "The modern airship behind today's Goodyear fleet.",
    body: "The Zeppelin NT (\"New Technology\") is a semi-rigid airship about 246 feet long, with an internal frame and steerable engines that make it far more maneuverable than older blimps. Goodyear's current fleet are Zeppelin NT airships, often seen over sporting events.",
    specs: [["First flight", "1997"], ["Length", "~246 ft"], ["Type", "Semi-rigid airship"], ["Use", "Advertising, sightseeing"]] },

  /* ---- Powered-lift ---- */
  { id: "harrier", name: "Harrier \"Jump Jet\"", maker: "Hawker Siddeley / BAE", cat: "poweredlift", role: "Attack", year: 1966, era: "Jet Age",
    blurb: "The vectored-thrust jet that hovers and lands vertically.",
    body: "The Harrier directs its jet exhaust through four rotating nozzles, letting it take off and land vertically or from very short strips. It proved a fixed-wing combat jet could operate without a conventional runway, a landmark in powered-lift flight.",
    specs: [["First flight", "1966"], ["Lift", "Vectored thrust"], ["Trait", "VTOL / STOVL"], ["Category", "Powered-lift"]] },
  { id: "jobys4", name: "Joby S4", maker: "Joby Aviation", cat: "poweredlift", role: "Air taxi", year: 2017, era: "Modern Era",
    blurb: "An all-electric air taxi in FAA certification.",
    body: "The Joby S4 is an electric vertical-takeoff aircraft with six tilting rotors that carries a pilot and four passengers, designed for quiet urban hops at up to roughly 200 mph over about 150 miles. It is one of the leading eVTOL designs working through FAA type certification.",
    specs: [["Power", "All-electric"], ["Seats", "1 pilot + 4"], ["Range", "~150 mi"], ["Top speed", "~200 mph"]] },
  { id: "midnight", name: "Archer Midnight", maker: "Archer Aviation", cat: "poweredlift", role: "Air taxi", year: 2023, era: "Modern Era",
    blurb: "An electric air taxi built for short city trips.",
    body: "Archer's Midnight is an eVTOL with twelve propellers — six that tilt and six fixed — carrying a pilot and four passengers about 100 miles at up to roughly 150 mph. It is aimed at short back-to-back urban flights and is progressing through FAA certification.",
    specs: [["Power", "All-electric"], ["Seats", "1 pilot + 4"], ["Range", "~100 mi"], ["Rotors", "12 (6 tilt)"]] },

  /* ---- Gyroplanes ---- */
  { id: "cierva-c30", name: "Cierva C.30 Autogiro", maker: "Cierva", cat: "rotorcraft", role: "Autogiro", year: 1933, era: "Golden Age",
    blurb: "The first widely successful rotary-wing aircraft.",
    body: "Juan de la Cierva's autogiro used a freely spinning, unpowered rotor for lift and a conventional propeller for thrust, letting it fly slowly and land in a short distance. It could not hover, but it solved the rotor problems that later made the practical helicopter possible.",
    specs: [["Introduced", "1933"], ["Rotor", "Unpowered (autorotating)"], ["Thrust", "Propeller"], ["Legacy", "Forerunner of the helicopter"]] },
  { id: "cavalon", name: "AutoGyro Cavalon", maker: "AutoGyro GmbH", cat: "rotorcraft", role: "Gyroplane", year: 2011, era: "Modern Era",
    blurb: "A popular modern sport gyroplane.",
    body: "The Cavalon is a modern two-seat gyroplane with side-by-side seating and a pusher propeller, part of a wave of designs that made the type popular again. Like all gyroplanes it flies on a continuously autorotating rotor, giving slow, stable flight and a very short landing.",
    specs: [["Introduced", "2011"], ["Seating", "Two (side-by-side)"], ["Rotor", "Autorotating"], ["Prop", "Pusher"]] },

  /* ---- More rotorcraft ---- */
  { id: "bell206", name: "Bell 206 JetRanger", maker: "Bell", cat: "rotorcraft", role: "Utility", year: 1967, era: "Jet Age",
    blurb: "One of the most successful light turbine helicopters.",
    body: "The Bell 206 JetRanger became a fixture of news, police, charter, and training flying thanks to its reliable turbine engine and graceful handling. Its sleek shape is one of the most recognizable in civil helicopter aviation.",
    specs: [["Introduced", "1967"], ["Engine", "Single turbine"], ["Seating", "Up to five"], ["Uses", "News, police, charter"]] },
  { id: "h125", name: "Airbus H125 (AStar)", maker: "Airbus Helicopters", cat: "rotorcraft", role: "Utility", year: 1974, era: "Modern Era",
    blurb: "A high-altitude single-engine workhorse.",
    body: "The H125, long known as the AStar or Écureuil, is a single-engine utility helicopter prized for hot-and-high performance and used for tours, firefighting, and mountain work. One famously landed on the summit of Mount Everest in 2005.",
    specs: [["Introduced", "1974"], ["Engine", "Single turbine"], ["Strength", "Hot-and-high"], ["Feat", "Everest summit landing (2005)"]] },

  /* ---- More airplanes ---- */
  { id: "pa28", name: "Piper PA-28 Cherokee", maker: "Piper", cat: "airplane", role: "Trainer", year: 1960, era: "Jet Age",
    blurb: "A low-wing trainer that taught generations to fly.",
    body: "The PA-28 Cherokee family is among the most common training and personal airplanes ever built — the low-wing counterpart to the high-wing Cessna 172. Simple, stable, and produced in huge numbers, it remains a staple at flight schools.",
    specs: [["Introduced", "1960"], ["Wing", "Low"], ["Seating", "Four"], ["Role", "Training, touring"]] },
  { id: "c182", name: "Cessna 182 Skylane", maker: "Cessna", cat: "airplane", role: "Touring", year: 1956, era: "Jet Age",
    blurb: "A roomy, capable step-up from the 172.",
    body: "The Cessna 182 Skylane is a high-wing single with more power and load-carrying ability than the 172, making it a popular cross-country and family airplane. Its constant-speed propeller and useful load make it a common move-up aircraft for private pilots.",
    specs: [["Introduced", "1956"], ["Wing", "High"], ["Seating", "Four"], ["Trait", "More power & payload"]] },
  { id: "c130", name: "Lockheed C-130 Hercules", maker: "Lockheed", cat: "airplane", role: "Transport", year: 1954, era: "Jet Age",
    blurb: "The legendary turboprop military transport.",
    body: "First flown in 1954, the four-engine C-130 Hercules hauls troops and cargo into short, rough airstrips and has served in airlift, firefighting, gunship, and rescue roles. One of the longest continuously produced military aircraft in history, it still flies worldwide.",
    specs: [["First flight", "1954"], ["Engines", "Four turboprop"], ["Role", "Tactical airlift"], ["Trait", "Short, rough fields"]] }
];

window.__AV_HISTORY__ = [
  { era: "Pioneers (1783–1914)", items: [
    { year: "1783", title: "First human flight", text: "The Montgolfier brothers' hot air balloon carries the first people aloft over Paris." },
    { year: "1800s", title: "Cayley defines flight", text: "Sir George Cayley identifies lift, thrust, and drag and builds early gliders, founding aerodynamics." },
    { year: "1890s", title: "Lilienthal's glides", text: "Otto Lilienthal makes repeated controlled glider flights, directly inspiring the Wright brothers." },
    { year: "1903", title: "First powered airplane", text: "The Wright brothers achieve the first powered, controlled, sustained flight at Kitty Hawk." },
    { year: "1909", title: "Channel crossing", text: "Louis Blériot flies an airplane across the English Channel, proving real cross-water range." },
    { year: "1914", title: "First airline service", text: "The St. Petersburg–Tampa Airboat Line begins the first scheduled airline service." }
  ]},
  { era: "Golden Age (1919–1938)", items: [
    { year: "1919", title: "Nonstop Atlantic", text: "Alcock and Brown make the first nonstop transatlantic airplane flight." },
    { year: "1921", title: "Bessie Coleman earns her license", text: "Bessie Coleman becomes the first African American and first Native American woman to earn a pilot license." },
    { year: "1923", title: "The autogiro", text: "Juan de la Cierva flies the autogiro, the first successful rotary-wing aircraft and a forerunner of the helicopter." },
    { year: "1924", title: "Around the world", text: "US Army aviators complete the first flight around the world, in open-cockpit Douglas World Cruisers." },
    { year: "1927", title: "Lindbergh solo", text: "Charles Lindbergh flies solo and nonstop from New York to Paris, igniting public enthusiasm." },
    { year: "1929", title: "Flight by instruments", text: "Jimmy Doolittle makes the first flight performed entirely by reference to instruments." },
    { year: "1932", title: "Earhart solo Atlantic", text: "Amelia Earhart becomes the first woman to fly solo across the Atlantic." },
    { year: "1933", title: "Modern airliner", text: "The Boeing 247, an early all-metal modern airliner, enters service." },
    { year: "1935", title: "The DC-3", text: "The Douglas DC-3 first flies and soon makes airline passenger travel profitable." },
    { year: "1937", title: "End of the airship", text: "The Hindenburg disaster effectively ends passenger airship travel." }
  ]},
  { era: "World War II (1939–1945)", items: [
    { year: "1939", title: "First jet flight", text: "Germany's Heinkel He 178 makes the first flight of a turbojet-powered aircraft." },
    { year: "1939", title: "Practical helicopter", text: "Igor Sikorsky's VS-300 pioneers the single-main-rotor helicopter that becomes standard." },
    { year: "1940", title: "Battle of Britain", text: "Fighters like the Spitfire and Hurricane defend Britain in a decisive air campaign." },
    { year: "1944", title: "First jet fighter", text: "Germany fields the Messerschmitt Me 262, the first operational jet fighter." },
    { year: "1945", title: "Wartime advances", text: "Radar, pressurization, and long-range aircraft mature rapidly during the war." }
  ]},
  { era: "Jet Age (1945–1969)", items: [
    { year: "1947", title: "Breaking the sound barrier", text: "Chuck Yeager exceeds the speed of sound in level flight in the Bell X-1." },
    { year: "1949", title: "First jet airliner", text: "The de Havilland Comet first flies, entering service in 1952 as the first jet airliner." },
    { year: "1958", title: "Jet age for travelers", text: "The Boeing 707 helps make jet airliners the norm for mainstream travel." },
    { year: "1961", title: "First human in space", text: "Yuri Gagarin orbits the Earth, becoming the first person to fly in space." },
    { year: "1964", title: "Mach 3 flight", text: "The SR-71 Blackbird flies, cruising above three times the speed of sound." },
    { year: "1969", title: "Jumbo and supersonic", text: "The wide-body Boeing 747 and the supersonic Concorde both make first flights." },
    { year: "1969", title: "Moon landing", text: "Apollo 11 lands humans on the Moon, the summit of the space race." }
  ]},
  { era: "Modern Era (1970–present)", items: [
    { year: "1970", title: "Wide-body era", text: "The Boeing 747 enters service, making long-haul travel affordable for millions." },
    { year: "1976", title: "Supersonic service", text: "Concorde begins supersonic passenger service across the Atlantic." },
    { year: "1978", title: "Airline deregulation", text: "US airline deregulation reshapes routes, pricing, and competition." },
    { year: "1980s", title: "Fly-by-wire airliners", text: "The Airbus A320 brings fly-by-wire flight controls to mainstream airliners." },
    { year: "1981", title: "Reusable spacecraft", text: "The Space Shuttle makes its first orbital flight, the first reusable crewed spacecraft." },
    { year: "1986", title: "Around the world nonstop", text: "Voyager completes the first nonstop, non-refueled flight around the world." },
    { year: "1990s", title: "GPS and glass", text: "Satellite navigation and glass cockpits transform how aircraft are flown." },
    { year: "2004", title: "Private spaceflight", text: "SpaceShipOne becomes the first privately funded craft to carry a human to space, winning the Ansari X Prize." },
    { year: "2005", title: "Largest airliner", text: "The double-deck Airbus A380, the largest passenger airliner, first flies." },
    { year: "2010s+", title: "Electric and eVTOL", text: "Electric aircraft, eVTOL air taxis, and commercial spaceflight open a new era." },
    { year: "2020", title: "Commercial crew", text: "A SpaceX Crew Dragon carries astronauts to orbit, the first crewed orbital flight by a private company." },
    { year: "2021", title: "Powered flight on Mars", text: "NASA's Ingenuity helicopter makes the first powered, controlled flight on another planet." }
  ]}
];

window.__AV_AIRPORTS__ = [
  /* ---- Major US hubs ---- */
  { id: "atl", name: "Hartsfield–Jackson Atlanta International", code: "ATL / KATL", city: "Atlanta, Georgia", group: "Major US hubs", tag: "Busiest in the world",
    blurb: "The world's busiest airport by passengers.",
    body: "Atlanta has been the world's busiest airport by passenger traffic almost every year since 1998, handling well over 100 million passengers annually. It is Delta Air Lines' largest hub, with five parallel runways feeding a single central terminal built for massive connecting traffic.",
    facts: [["Identifier", "ATL / KATL"], ["Location", "Atlanta, GA"], ["Elevation", "~1,026 ft"], ["Runways", "5 parallel"], ["Known for", "Busiest airport on Earth"]] },
  { id: "dfw", name: "Dallas/Fort Worth International", code: "DFW / KDFW", city: "Dallas–Fort Worth, Texas", group: "Major US hubs", tag: "Larger than Manhattan",
    blurb: "One of the largest airports by land area.",
    body: "DFW covers more ground than the island of Manhattan and ranks among the busiest airports in the world by both passengers and aircraft movements. It is American Airlines' main hub and the primary international gateway for the central United States.",
    facts: [["Identifier", "DFW / KDFW"], ["Location", "Dallas–Fort Worth, TX"], ["Elevation", "~607 ft"], ["Runways", "7"], ["Known for", "Among the largest by area"]] },
  { id: "den", name: "Denver International", code: "DEN / KDEN", city: "Denver, Colorado", group: "Major US hubs", tag: "Largest US airport by land",
    blurb: "North America's largest airport by land area.",
    body: "Denver International is the largest airport in North America by land area, about 53 square miles, and its peaked white roof echoes the Rocky Mountains beyond. At roughly 5,430 feet it is one of the highest major US airports, and its Runway 16R/34L is the longest commercial runway in North America at 16,000 feet.",
    facts: [["Identifier", "DEN / KDEN"], ["Location", "Denver, CO"], ["Elevation", "~5,430 ft"], ["Runways", "6"], ["Known for", "Longest US commercial runway"]] },
  { id: "ord", name: "Chicago O'Hare International", code: "ORD / KORD", city: "Chicago, Illinois", group: "Major US hubs", tag: "",
    blurb: "One of the world's great connecting hubs.",
    body: "O'Hare has long been among the busiest airports in the world by aircraft movements and is a major hub for both United and American. Its dense, bank-driven schedule links the central US to destinations across the globe.",
    facts: [["Identifier", "ORD / KORD"], ["Location", "Chicago, IL"], ["Elevation", "~672 ft"], ["Runways", "8"], ["Known for", "Major connecting hub"]] },
  { id: "lax", name: "Los Angeles International", code: "LAX / KLAX", city: "Los Angeles, California", group: "Major US hubs", tag: "",
    blurb: "The primary US gateway to the Pacific.",
    body: "LAX is one of the busiest origin-and-destination airports in the world and the main gateway between the US and the Pacific. Its midcentury Theme Building and rows of parallel runways are icons of West Coast aviation.",
    facts: [["Identifier", "LAX / KLAX"], ["Location", "Los Angeles, CA"], ["Elevation", "~125 ft"], ["Runways", "4"], ["Known for", "Major Pacific gateway"]] },
  { id: "jfk", name: "John F. Kennedy International", code: "JFK / KJFK", city: "New York, New York", group: "Major US hubs", tag: "",
    blurb: "New York's main international gateway.",
    body: "JFK is New York's principal international airport and one of the busiest in the US for overseas traffic. Opened in the 1940s and expanded ever since, it serves as a hub for long-haul flights to every continent.",
    facts: [["Identifier", "JFK / KJFK"], ["Location", "New York, NY"], ["Elevation", "~13 ft"], ["Runways", "4"], ["Known for", "NYC international gateway"]] },
  { id: "sfo", name: "San Francisco International", code: "SFO / KSFO", city: "San Francisco, California", group: "Major US hubs", tag: "Fog & close parallels",
    blurb: "A Pacific gateway famous for its fog.",
    body: "San Francisco International is a major trans-Pacific hub known for closely spaced parallel runways that complicate operations when the Bay Area's marine-layer fog rolls in. It is a key hub for United Airlines.",
    facts: [["Identifier", "SFO / KSFO"], ["Location", "San Francisco, CA"], ["Elevation", "~13 ft"], ["Runways", "4"], ["Known for", "Closely spaced parallels"]] },

  /* ---- Major world hubs ---- */
  { id: "lhr", name: "London Heathrow", code: "LHR / EGLL", city: "London, United Kingdom", group: "Major world hubs", tag: "Busiest in Europe",
    blurb: "Europe's busiest airport on just two runways.",
    body: "Heathrow is the busiest airport in Europe and one of the busiest international hubs in the world, all handled on two parallel runways running near capacity. It is the home base of British Airways and a major global connecting point.",
    facts: [["Identifier", "LHR / EGLL"], ["Location", "London, UK"], ["Elevation", "~83 ft"], ["Runways", "2"], ["Known for", "Busiest in Europe"]] },
  { id: "dxb", name: "Dubai International", code: "DXB / OMDB", city: "Dubai, United Arab Emirates", group: "Major world hubs", tag: "Busiest for international travel",
    blurb: "The world's busiest for international passengers.",
    body: "Dubai International is the world's busiest airport for international passengers and the home of Emirates. It symbolizes the Gulf's rise as a global crossroads, linking Europe, Asia, Africa, and the Americas on long-haul widebodies.",
    facts: [["Identifier", "DXB / OMDB"], ["Location", "Dubai, UAE"], ["Elevation", "~62 ft"], ["Runways", "2"], ["Known for", "Top international hub"]] },
  { id: "hnd", name: "Tokyo Haneda", code: "HND / RJTT", city: "Tokyo, Japan", group: "Major world hubs", tag: "",
    blurb: "One of the world's busiest, near central Tokyo.",
    body: "Haneda is among the busiest airports in the world and sits close to central Tokyo, making it a favorite for business travel. Built partly on reclaimed land in Tokyo Bay, it handles huge domestic and growing international traffic.",
    facts: [["Identifier", "HND / RJTT"], ["Location", "Tokyo, Japan"], ["Elevation", "~21 ft"], ["Runways", "4"], ["Known for", "Close to central Tokyo"]] },
  { id: "ams", name: "Amsterdam Schiphol", code: "AMS / EHAM", city: "Amsterdam, Netherlands", group: "Major world hubs", tag: "Below sea level",
    blurb: "A major hub built below sea level.",
    body: "Schiphol is one of the few major airports built below sea level, sitting about 11 feet beneath it on a drained lake bed. A major European hub with an unusually large number of runways, it is the home base of KLM.",
    facts: [["Identifier", "AMS / EHAM"], ["Location", "Amsterdam, Netherlands"], ["Elevation", "~-11 ft"], ["Runways", "6"], ["Known for", "Major hub below sea level"]] },
  { id: "sin", name: "Singapore Changi", code: "SIN / WSSS", city: "Singapore", group: "Major world hubs", tag: "Top-rated experience",
    blurb: "Renowned for its passenger experience.",
    body: "Changi is consistently ranked among the world's best airports, famous for its Jewel complex with an indoor waterfall and gardens. It is a major Southeast Asian hub and a benchmark for airport design.",
    facts: [["Identifier", "SIN / WSSS"], ["Location", "Singapore"], ["Elevation", "~22 ft"], ["Runways", "Two main"], ["Known for", "World-class terminals"]] },
  { id: "hkg", name: "Hong Kong International", code: "HKG / VHHH", city: "Hong Kong", group: "Major world hubs", tag: "Built on a man-made island",
    blurb: "A major hub on a largely artificial island.",
    body: "Opened in 1998 at Chek Lap Kok, Hong Kong International was built on a largely man-made island formed by leveling and reclaiming land from the sea. It is one of the world's busiest airports for cargo and a major passenger gateway to Asia.",
    facts: [["Identifier", "HKG / VHHH"], ["Location", "Hong Kong"], ["Elevation", "~28 ft"], ["Runways", "3"], ["Known for", "Top global cargo hub"]] },
  { id: "ist", name: "Istanbul Airport", code: "IST / LTFM", city: "Istanbul, Türkiye", group: "Major world hubs", tag: "Among the world's largest",
    blurb: "A vast hub bridging Europe and Asia.",
    body: "Opened in 2018, Istanbul Airport is one of the largest airports in the world and the main hub of Turkish Airlines, built to connect Europe, Asia, Africa, and the Middle East. It quickly grew into one of the busiest airports on the planet.",
    facts: [["Identifier", "IST / LTFM"], ["Location", "Istanbul, Türkiye"], ["Elevation", "~325 ft"], ["Runways", "Multiple"], ["Known for", "Major Europe–Asia hub"]] },

  /* ---- Notable US airports ---- */
  { id: "osh", name: "Wittman Regional", code: "OSH / KOSH", city: "Oshkosh, Wisconsin", group: "Notable US airports", tag: "World's busiest tower during AirVenture",
    blurb: "Quiet most of the year — then AirVenture.",
    body: "For most of the year Wittman Regional is a calm Wisconsin field, but each summer it hosts EAA AirVenture and briefly becomes the busiest air traffic control operation in the world. Controllers famously clear pilots to land on colored dots painted on the runway to pack in the arrivals.",
    facts: [["Identifier", "OSH / KOSH"], ["Location", "Oshkosh, WI"], ["Elevation", "~808 ft"], ["Runways", "3"], ["Known for", "EAA AirVenture fly-in"]] },
  { id: "ase", name: "Aspen/Pitkin County", code: "ASE / KASE", city: "Aspen, Colorado", group: "Notable US airports", tag: "Demanding mountain ops",
    blurb: "A challenging high-altitude mountain airport.",
    body: "Aspen sits in a steep Colorado valley at about 7,820 feet, with terrain that demands specialized approaches and limits the types and sizes of aircraft that can operate. It is one of the more challenging US airports served by airline jets.",
    facts: [["Identifier", "ASE / KASE"], ["Location", "Aspen, CO"], ["Elevation", "~7,820 ft"], ["Runways", "1"], ["Known for", "Demanding mountain ops"]] },
  { id: "tex", name: "Telluride Regional", code: "TEX / KTEX", city: "Telluride, Colorado", group: "Notable US airports", tag: "Highest US commercial airport",
    blurb: "The highest commercial airport in the US.",
    body: "Perched on a mesa at about 9,070 feet, Telluride Regional is the highest-elevation commercial airport in the United States. The thin mountain air and sharp drop-offs at the runway ends make it a memorable and demanding place to fly.",
    facts: [["Identifier", "TEX / KTEX"], ["Location", "Telluride, CO"], ["Elevation", "~9,070 ft"], ["Runways", "1"], ["Known for", "Highest US commercial field"]] },
  { id: "lxv", name: "Leadville / Lake County", code: "LXV / KLXV", city: "Leadville, Colorado", group: "Notable US airports", tag: "Highest public airport in N. America",
    blurb: "North America's highest public-use airport.",
    body: "Leadville–Lake County is the highest public-use airport in North America at 9,934 feet in the Colorado Rockies. Pilots who land there can collect a certificate marking the feat, and the altitude makes it a center for high-altitude aircraft testing.",
    facts: [["Identifier", "LXV / KLXV"], ["Location", "Leadville, CO"], ["Elevation", "9,934 ft"], ["Runways", "1"], ["Known for", "Highest public airport in N. America"]] },
  { id: "sez", name: "Sedona", code: "SEZ / KSEZ", city: "Sedona, Arizona", group: "Notable US airports", tag: "Mesa-top runway",
    blurb: "The scenic mesa-top 'USS Sedona.'",
    body: "Sedona's single runway sits atop a mesa ringed by Arizona's red rock country, earning the nickname 'the USS Sedona' for its aircraft-carrier-like setting. The scenery is spectacular and the elevated, drop-off runway ends keep pilots sharp.",
    facts: [["Identifier", "SEZ / KSEZ"], ["Location", "Sedona, AZ"], ["Elevation", "~4,830 ft"], ["Runways", "1"], ["Known for", "Scenic mesa-top airport"]] },
  { id: "avx", name: "Catalina (Airport in the Sky)", code: "AVX / KAVX", city: "Santa Catalina Island, California", group: "Notable US airports", tag: "Airport in the Sky",
    blurb: "A mountaintop island airstrip with a famous hump.",
    body: "On Santa Catalina Island off California, this mountaintop airport sits at about 1,600 feet with a single runway famous for a hump in the middle that hides one end from the other. It is a classic, scenic general aviation destination reached mostly by small aircraft.",
    facts: [["Identifier", "AVX / KAVX"], ["Location", "Catalina Island, CA"], ["Elevation", "~1,602 ft"], ["Runways", "1"], ["Known for", "Mountaintop island strip"]] },
  { id: "jac", name: "Jackson Hole", code: "JAC / KJAC", city: "Jackson, Wyoming", group: "Notable US airports", tag: "Inside a national park",
    blurb: "The only airport inside a US national park.",
    body: "Jackson Hole is the only commercial airport located within a US national park, sitting inside Grand Teton National Park in Wyoming. Travelers arrive to sweeping mountain views, with the Tetons rising directly beyond the runway.",
    facts: [["Identifier", "JAC / KJAC"], ["Location", "Jackson, WY"], ["Elevation", "~6,450 ft"], ["Runways", "1"], ["Known for", "Only airport in a US national park"]] },
  { id: "dca", name: "Ronald Reagan Washington National", code: "DCA / KDCA", city: "Washington, D.C.", group: "Notable US airports", tag: "Potomac River Visual",
    blurb: "Famous for its winding river approach.",
    body: "Washington's close-in airport is known for the River Visual approach to Runway 19, which has pilots follow the bends of the Potomac River to avoid prohibited airspace over the capital. It is prized for its proximity to downtown Washington.",
    facts: [["Identifier", "DCA / KDCA"], ["Location", "Washington, DC"], ["Elevation", "~15 ft"], ["Runways", "3"], ["Known for", "Potomac River Visual approach"]] },
  { id: "vny", name: "Van Nuys", code: "VNY / KVNY", city: "Los Angeles, California", group: "Notable US airports", tag: "One of the busiest GA airports",
    blurb: "One of the world's busiest general aviation airports.",
    body: "Tucked into the San Fernando Valley of Los Angeles, Van Nuys handles no scheduled airlines yet is one of the busiest general aviation airports in the world. It is a major center for flight training, business aviation, and aircraft services.",
    facts: [["Identifier", "VNY / KVNY"], ["Location", "Los Angeles, CA"], ["Elevation", "~802 ft"], ["Runways", "2"], ["Known for", "Busy general aviation field"]] },

  /* ---- Iconic & extreme ---- */
  { id: "sxm", name: "Princess Juliana International", code: "SXM / TNCM", city: "Sint Maarten", group: "Iconic & extreme", tag: "Maho Beach approach",
    blurb: "Jets skim a beach on short final.",
    body: "On the island of Sint Maarten, Princess Juliana is world-famous for arrivals that pass just over Maho Beach, where spectators feel the jet blast as airliners cross the sand on short final. The beach approach makes it one of the most photographed airports anywhere.",
    facts: [["Identifier", "SXM / TNCM"], ["Location", "Sint Maarten"], ["Elevation", "~13 ft"], ["Runways", "1"], ["Known for", "Low approach over the beach"]] },
  { id: "lua", name: "Tenzing–Hillary (Lukla)", code: "LUA / VNLK", city: "Lukla, Nepal", group: "Iconic & extreme", tag: "Gateway to Everest",
    blurb: "A short, steeply sloped Himalayan strip.",
    body: "The gateway for Everest trekkers, Lukla sits high in the Himalayas at about 9,330 feet with a very short runway that slopes steeply uphill and ends against a mountainside. Often named among the world's most demanding airports, it is flown only by specially trained crews in small aircraft.",
    facts: [["Identifier", "LUA / VNLK"], ["Location", "Lukla, Nepal"], ["Elevation", "~9,330 ft"], ["Runways", "1, sloped"], ["Known for", "Everest gateway"]] },
  { id: "cvf", name: "Courchevel Altiport", code: "CVF / LFLJ", city: "Courchevel, France", group: "Iconic & extreme", tag: "Steep alpine altiport",
    blurb: "A very short, steeply sloped alpine runway.",
    body: "High in the French Alps, Courchevel has one of the most dramatic runways in the world: only about 540 meters long with a steep uphill gradient that helps arriving aircraft slow and departing aircraft accelerate downhill. Serving the ski resort, it requires a special mountain rating to fly.",
    facts: [["Identifier", "CVF / LFLJ"], ["Location", "Courchevel, France"], ["Elevation", "~6,560 ft"], ["Runways", "1, steep"], ["Known for", "Short sloped mountain runway"]] },
  { id: "gib", name: "Gibraltar International", code: "GIB / LXGB", city: "Gibraltar", group: "Iconic & extreme", tag: "Road crosses the runway",
    blurb: "A main road crosses the active runway.",
    body: "Gibraltar International has the rare feature of a public road, Winston Churchill Avenue, crossing directly over its single runway. Traffic and pedestrians are stopped by barriers each time an aircraft takes off or lands, beneath the famous Rock of Gibraltar.",
    facts: [["Identifier", "GIB / LXGB"], ["Location", "Gibraltar"], ["Elevation", "~15 ft"], ["Runways", "1"], ["Known for", "Road across the runway"]] },
  { id: "fnc", name: "Madeira (Cristiano Ronaldo)", code: "FNC / LPMA", city: "Madeira, Portugal", group: "Iconic & extreme", tag: "Runway on pillars",
    blurb: "Part of the runway stands on tall pillars.",
    body: "Madeira's airport in Portugal was extended on a platform over the ocean, with much of the runway supported by tall pillars. Strong, gusty winds funneling around the island's terrain make it a notably challenging approach.",
    facts: [["Identifier", "FNC / LPMA"], ["Location", "Madeira, Portugal"], ["Elevation", "~192 ft"], ["Runways", "1"], ["Known for", "Runway extended on pillars"]] },
  { id: "brr", name: "Barra", code: "BRR / EGPR", city: "Isle of Barra, Scotland", group: "Iconic & extreme", tag: "Beach runway, tidal schedule",
    blurb: "Scheduled flights land on a tidal beach.",
    body: "On the Scottish island of Barra, scheduled airline flights land directly on a tidal beach, the only such operation in the world. The timetable shifts with the tides, because the runway vanishes under the sea at high water.",
    facts: [["Identifier", "BRR / EGPR"], ["Location", "Barra, Scotland"], ["Elevation", "~5 ft"], ["Runways", "Beach"], ["Known for", "Scheduled flights on a beach"]] },
  { id: "pbh", name: "Paro International", code: "PBH / VQPR", city: "Paro, Bhutan", group: "Iconic & extreme", tag: "Few pilots certified",
    blurb: "A Himalayan approach few pilots may fly.",
    body: "Bhutan's main international airport sits in a deep Himalayan valley ringed by peaks, with an approach so demanding that only a small number of pilots are certified to fly it. Arrivals weave between mountainsides on the way down to the runway.",
    facts: [["Identifier", "PBH / VQPR"], ["Location", "Paro, Bhutan"], ["Elevation", "~7,330 ft"], ["Runways", "1"], ["Known for", "One of the hardest approaches"]] },
  { id: "sab", name: "Juancho E. Yrausquin (Saba)", code: "SAB / TNCS", city: "Saba, Caribbean Netherlands", group: "Iconic & extreme", tag: "World's shortest commercial runway",
    blurb: "The shortest commercial runway in the world.",
    body: "On the tiny Caribbean island of Saba, this airport has the shortest commercial runway in the world, roughly 400 meters, with cliffs dropping to the sea at both ends. Only small aircraft and specially trained pilots use it.",
    facts: [["Identifier", "SAB / TNCS"], ["Location", "Saba"], ["Elevation", "~60 ft"], ["Runways", "~400 m"], ["Known for", "Shortest commercial runway"]] }
];

window.__AV_PREFLIGHT__ = {
  fly: {
    title: "Before you fly",
    tagline: "The kind of checklist a pilot runs before every single flight.",
    phases: [
      { phase: "Plan the flight", note: "Before you reach the airplane",
        items: [
          "Get an official weather briefing and review winds and forecasts for your route.",
          "Check NOTAMs and TFRs, and confirm both departure and destination airports are usable.",
          "Confirm the aircraft is within weight and balance, with enough fuel plus reserves.",
          "Check yourself with IMSAFE: illness, medication, stress, alcohol, fatigue, emotion." ] },
      { phase: "Walkaround (exterior)", note: "Inspect nose to tail",
        items: [
          "Confirm required documents are aboard (ARROW) and required inspections are current.",
          "Drain a fuel sample and check quantity; look for water or the wrong grade or color.",
          "Check the oil level and look for leaks, loose fasteners, or damage.",
          "Move every flight control and confirm it is free and travels the correct direction.",
          "Check tires, brakes, and struts; inspect the pitot tube, static ports, and antennas.",
          "Remove tie-downs, chocks, covers, and all control locks." ] },
      { phase: "Cockpit and before start", note: "Settle in and set up",
        items: [
          "Adjust the seat, fasten the seatbelt and shoulder harness, and secure the doors.",
          "Set the brakes, confirm controls are free, and set the fuel selector.",
          "Set the altimeter, instruments, avionics, and radios; check the circuit breakers.",
          "Confirm the area is clear, then start using the engine-start procedure." ] },
      { phase: "Run-up and before takeoff", note: "The last check before the runway",
        items: [
          "Run up the engine; check magnetos, carburetor heat, and engine gauges in the green.",
          "Set flaps and trim for takeoff and re-check the flight controls free and correct.",
          "Confirm doors latched, fuel on the proper tank, and all instruments set.",
          "Brief the takeoff: airspeeds, your plan if the engine quits, and your departure path.",
          "Check the approach and runway clear, then line up and go." ] }
    ]
  },
  study: {
    title: "Before you study",
    byTier: {
      junior: {
        tagline: "Run your study mission check before you start learning.",
        phases: [
          { phase: "Your mission plan", note: "What's the plan?",
            items: [
              "Pick one thing you want to learn today.",
              "Tell a grown-up you're starting your study mission.",
              "Set a timer for a short session — about 10 to 15 minutes." ] },
          { phase: "Are you ready?", note: "Check yourself",
            items: [
              "Have a snack and some water so your brain has fuel.",
              "Put games, videos, and toys out of reach.",
              "Find a quiet spot where it's easy to think." ] },
          { phase: "Get your gear", note: "Everything ready",
            items: [
              "Open AvHype and grab something to write or draw with.",
              "Open the last thing you learned so you remember where you were.",
              "Keep a sticky note handy for any questions that pop up." ] },
          { phase: "Ready for takeoff", note: "Let's go!",
            items: [
              "Think about what you learned last time for a minute.",
              "Say your goal out loud — then begin!",
              "After, tell someone one cool thing you learned." ] }
        ]
      },
      teen: {
        tagline: "Run the same check a pilot would, before every study session.",
        phases: [
          { phase: "Set your target", note: "Your study flight plan",
            items: [
              "Pick one thing to own today: a topic, a lesson, or a quiz.",
              "Tie it to the certificate you're building toward so it counts for something.",
              "Block out a focused 20 to 30 minutes." ] },
          { phase: "Clear for focus", note: "Your study IMSAFE",
            items: [
              "Are you actually rested and fed enough to concentrate right now?",
              "Put your phone on Do Not Disturb and close the group chats.",
              "Pick a spot where you won't get pulled away." ] },
          { phase: "Load up", note: "Everything within reach",
            items: [
              "Open AvHype and have something to take notes with.",
              "Reopen last session's notes so you build on them, not restart.",
              "Have a place to park random questions for later." ] },
          { phase: "Launch", note: "Commit and begin",
            items: [
              "Spend two minutes reviewing last time to get back into it.",
              "Say today's target out loud, then start the first task.",
              "When you're done, leave a note on what to hit next session." ] }
        ]
      },
      adult: {
        tagline: "Run the same discipline before every study session.",
        phases: [
          { phase: "Plan the session", note: "Your study flight plan",
            items: [
              "Pick one clear goal: a single topic, lesson, or quiz to focus on today.",
              "Know why it matters — tie it to the rating or checkride you are working toward.",
              "Set a realistic time limit so the session has a beginning and an end." ] },
          { phase: "Check yourself", note: "Your study IMSAFE",
            items: [
              "Are you rested and fed enough to focus, or is this a short review at best?",
              "Silence your phone and close anything that will pull your attention away.",
              "Clear your space and keep water nearby so small needs do not interrupt you." ] },
          { phase: "Set up your cockpit", note: "Everything within reach",
            items: [
              "Gather your materials: AvHype, notes, a notebook, and anything you are referencing.",
              "Open your notes from last time so you start where you left off, not from zero.",
              "Decide how you will jot down stray questions instead of chasing them mid-session." ] },
          { phase: "Before takeoff", note: "Commit and begin",
            items: [
              "Spend two minutes reviewing last session to warm up before new material.",
              "Restate today's goal out loud or in writing, then start the first task.",
              "When you finish, note one thing to review next time — your next session's first checkpoint." ] }
        ]
      }
    }
  }
};

window.__AV_MILESTONES__ = [
  { id: "m-foundation", pathway: "foundation", units: ["foundation"], title: "Ground Foundations", cite: "%NAME% has completed the foundational ground-study block \u2014 aircraft categories and classes, airspace, weather basics, certificates, and aeronautical decision-making \u2014 and is ready to begin focused training in a chosen pathway." },

  { id: "m-af-airplane", pathway: "airplane", units: ["af-airplane"], title: "Airplane Familiarization", cite: "%NAME% understands how an airplane flies, the function of the primary flight controls and cockpit instruments, and what to expect from a first lesson." },
  { id: "m-a-entry", pathway: "airplane", units: ["a-entry"], title: "Sport & Recreational Pilot Knowledge", cite: "%NAME% understands the sport-pilot and recreational-pilot certificates, light-sport aircraft, and how to choose an entry path into aviation." },
  { id: "m-a-foundation", pathway: "airplane", units: ["a-foundation"], title: "Pre-Solo & Private Pilot Knowledge", cite: "%NAME% has completed the pre-solo and private-pilot knowledge core \u2014 the four forces, the traffic pattern, VFR airspace, weight and balance, weather reports, and slow flight \u2014 and is ready for first-solo concepts." },
  { id: "m-a-instrument", pathway: "airplane", units: ["a-instrument"], title: "Instrument Rating Knowledge", cite: "%NAME% has completed the instrument-rating knowledge block: the instrument scan, spatial disorientation, IFR weather, clearances, and approaches." },
  { id: "m-a-classratings", pathway: "airplane", units: ["a-classratings"], title: "Multi-Engine & Seaplane Knowledge", cite: "%NAME% understands multi-engine aerodynamics and engine-out control, plus the fundamentals of seaplane operations on and off the water." },
  { id: "m-a-commercial", pathway: "airplane", units: ["a-commercial"], title: "Commercial Pilot Knowledge", cite: "%NAME% has completed the commercial-pilot knowledge block: privileges and limitations, aeronautical experience, precision maneuvers, complex systems, the regulations, and professionalism." },
  { id: "m-a-cfi", pathway: "airplane", units: ["a-cfi"], title: "Flight Instructor Knowledge", cite: "%NAME% has completed the flight-instructor knowledge block: the CFI certificate, the fundamentals of instructing, the teaching process, and added ratings." },
  { id: "m-a-atp", pathway: "airplane", units: ["a-atp"], title: "Airline Transport Pilot Knowledge", cite: "%NAME% has completed the ATP knowledge block: eligibility and the restricted ATP, the aeronautical-experience breakdown, ATP-CTP, type ratings, and airline standards." },
  { id: "m-cap-airplane", pathway: "airplane", capstone: true, units: ["af-airplane", "a-entry", "a-foundation", "a-instrument", "a-classratings", "a-commercial", "a-cfi", "a-atp"], title: "Airplane Program \u2014 Zero to ATP", cite: "%NAME% has completed every airplane lesson in the program, from first principles through the Airline Transport Pilot knowledge core. An extraordinary achievement." },

  { id: "m-af-drone", pathway: "drone", units: ["af-drone"], title: "Drone Familiarization", cite: "%NAME% understands multirotor flight, the controller, and the basic rules for where a small drone may be flown." },
  { id: "m-d107", pathway: "drone", units: ["d107"], title: "Part 107 Knowledge \u2014 Test Ready", cite: "%NAME% has completed the knowledge core for the FAA Part 107 Remote Pilot certificate: operating limits, airspace, Remote ID, operations over people, and weather and performance." },
  { id: "m-d-advanced", pathway: "drone", units: ["d-advanced"], title: "Advanced Drone Operations", cite: "%NAME% has completed recurrent and advanced Part 107 operations: recurrency, waivers, airspace authorizations, operations over people, and Remote ID." },
  { id: "m-cap-drone", pathway: "drone", capstone: true, units: ["af-drone", "d107", "d-advanced"], title: "Drone Program \u2014 Complete", cite: "%NAME% has completed every drone lesson in the program, from multirotor fundamentals through advanced Part 107 operations." },

  { id: "m-af-helicopter", pathway: "helicopter", units: ["af-helicopter"], title: "Helicopter Familiarization", cite: "%NAME% understands rotary-wing flight, the four helicopter controls, torque and anti-torque, and the fundamentals of the hover." },
  { id: "m-h-private", pathway: "helicopter", units: ["h-private"], title: "Private Pilot Knowledge \u2014 Helicopter", cite: "%NAME% has completed the private-pilot rotorcraft knowledge block: maneuvers, autorotation, performance, and helicopter-specific emergencies." },
  { id: "m-h-instrument", pathway: "helicopter", units: ["h-instrument"], title: "Instrument Rating Knowledge \u2014 Helicopter", cite: "%NAME% understands rotary-wing instrument flight: the rating's requirements, why it is demanding, and real IFR helicopter operations." },
  { id: "m-h-commercial", pathway: "helicopter", units: ["h-commercial"], title: "Commercial Pilot Knowledge \u2014 Helicopter", cite: "%NAME% has completed the commercial rotorcraft knowledge block: privileges, advanced maneuvers, operations, performance, and professional judgment." },
  { id: "m-h-atp", pathway: "helicopter", units: ["h-atp"], title: "Airline Transport Pilot Knowledge \u2014 Helicopter", cite: "%NAME% understands the top rotary-wing certificate and the professional air-carrier operations it opens." },
  { id: "m-cap-helicopter", pathway: "helicopter", capstone: true, units: ["af-helicopter", "h-private", "h-instrument", "h-commercial", "h-atp"], title: "Helicopter Program \u2014 Complete", cite: "%NAME% has completed every helicopter lesson in the program, from rotary-wing fundamentals through the Airline Transport Pilot knowledge core." },

  { id: "m-g-soaring", pathway: "glider", units: ["g-soaring"], title: "Glider & Soaring Knowledge", cite: "%NAME% understands engineless flight: the glider category and no-medical rule, certificates, launch methods, finding lift, performance, and landing out." },
  { id: "m-b-balloon", pathway: "balloon", units: ["b-balloon"], title: "Balloon & Lighter-Than-Air Knowledge", cite: "%NAME% understands hot-air balloon flight: the category and no-medical rule, certificates, how a balloon flies and steers by wind, and operations." },
  { id: "m-gy-gyro", pathway: "gyroplane", units: ["gy-gyro"], title: "Gyroplane Knowledge", cite: "%NAME% understands the gyroplane: how the free-spinning rotor flies, the controls and prerotation, certificates, and handling safety." },
  { id: "m-pl-poweredlift", pathway: "poweredlift", units: ["pl-poweredlift"], title: "Powered-Lift & eVTOL Knowledge", cite: "%NAME% understands powered-lift flight: the category, the transition between vertical and winged flight, the certification path, and advanced air mobility." },
  { id: "m-ws-trike", pathway: "weightshift", units: ["ws-trike"], title: "Weight-Shift Control Knowledge", cite: "%NAME% understands weight-shift control: the trike, its reversed-feel handling, certificates, and operating safely." },
  { id: "m-pp-chute", pathway: "poweredchute", units: ["pp-chute"], title: "Powered Parachute Knowledge", cite: "%NAME% understands the powered parachute: the ram-air canopy wing, throttle-for-altitude control, certificates, and canopy safety." }
];
