# -*- coding: utf-8 -*-
"""PaleoHype taxa: pterosaurs (flying reptiles) and marine reptiles.
Tuple format: (key, name, sci, group, classGroup, periodKey, diet, art, trait)
"""

PTEROSAURS = [
 ("pteranodon","Pteranodon","Pteranodon longiceps","large pterosaur","pterosaur","latecret","piscivore","pterosaur",
  "A toothless flying reptile with a wingspan of up to about 7 metres and a long bony crest sweeping back from its head."),
 ("quetzalcoatlus","Quetzalcoatlus","Quetzalcoatlus northropi","giant pterosaur","pterosaur","latecret","carnivore","pterosaur",
  "One of the largest flying animals ever, with a wingspan near 10-11 metres; standing on the ground it was as tall as a giraffe."),
 ("rhamphorhynchus","Rhamphorhynchus","Rhamphorhynchus muensteri","long-tailed pterosaur","pterosaur","jurassic","piscivore","pterosaur",
  "An early pterosaur with a long, stiff tail ending in a diamond-shaped flap, and forward-pointing teeth for snatching fish."),
 ("pterodactylus","Pterodactylus","Pterodactylus antiquus","pterosaur","pterosaur","jurassic","piscivore","pterosaur",
  "The first pterosaur ever discovered and named, a small short-tailed flyer from the Jurassic of Germany."),
 ("dimorphodon","Dimorphodon","Dimorphodon macronyx","pterosaur","pterosaur","jurassic","carnivore","pterosaur",
  "An early pterosaur with a tall, deep, puffin-like head and two different kinds of teeth."),
 ("tropeognathus","Tropeognathus","Tropeognathus mesembrinus","large pterosaur","pterosaur","earlycret","piscivore","pterosaur",
  "Rounded keel-like crests on the tip of its upper and lower jaws may have helped it skim fish from the sea."),
 ("tapejara","Tapejara","Tapejara wellnhoferi","pterosaur","pterosaur","earlycret","omnivore","pterosaur",
  "It wore a tall, sail-like crest on its snout, probably brightly coloured for display."),
 ("dsungaripterus","Dsungaripterus","Dsungaripterus weii","pterosaur","pterosaur","earlycret","carnivore","pterosaur",
  "Its upturned, tweezer-like jaws and blunt back teeth were ideal for prising shellfish from rocks."),
 ("nyctosaurus","Nyctosaurus","Nyctosaurus gracilis","pterosaur","pterosaur","latecret","piscivore","pterosaur",
  "A toothless sea-going flyer with an enormous antler-like crest much larger than its own skull."),
 ("tupandactylus","Tupandactylus","Tupandactylus imperator","pterosaur","pterosaur","earlycret","omnivore","pterosaur",
  "It carried one of the largest crests of any pterosaur, a huge rounded sail rising high above its head."),
 ("anhanguera","Anhanguera","Anhanguera blittersdorffi","large pterosaur","pterosaur","earlycret","piscivore","pterosaur",
  "A fish-eating flyer with rounded crests on its jaws and a wingspan of around 4 metres."),
 ("eudimorphodon","Eudimorphodon","Eudimorphodon ranzii","early pterosaur","pterosaur","triassic","piscivore","pterosaur",
  "One of the earliest known pterosaurs, from the Triassic, already a capable flyer with many specialised teeth."),
 ("hatzegopteryx","Hatzegopteryx","Hatzegopteryx thambema","giant pterosaur","pterosaur","latecret","carnivore","pterosaur",
  "A huge, robustly built flying reptile that was likely the top predator on its Late Cretaceous island home."),
 ("ornithocheirus","Ornithocheirus","Ornithocheirus simus","large pterosaur","pterosaur","earlycret","piscivore","pterosaur",
  "A large sea-going pterosaur with keeled jaws, known from the chalk seas of ancient Europe."),
 ("istiodactylus","Istiodactylus","Istiodactylus latidens","pterosaur","pterosaur","earlycret","scavenger","pterosaur",
  "Its broad, duck-like snout was rimmed with razor teeth, perhaps for scavenging carcasses."),
 ("caelestiventus","Caelestiventus","Caelestiventus hanseni","early pterosaur","pterosaur","triassic","carnivore","pterosaur",
  "A surprisingly large Triassic pterosaur from a desert, showing these flyers were diverse very early on."),
 ("preondactylus","Preondactylus","Preondactylus buffarinii","early pterosaur","pterosaur","triassic","piscivore","pterosaur",
  "One of the most primitive known pterosaurs, small with a short neck and long tail."),
 ("campylognathoides","Campylognathoides","Campylognathoides liasicus","pterosaur","pterosaur","jurassic","carnivore","pterosaur",
  "An early Jurassic pterosaur with large eyes and a strong, lightweight body built for flight."),
 ("thalassodromeus","Thalassodromeus","Thalassodromeus sethi","large pterosaur","pterosaur","earlycret","carnivore","pterosaur",
  "A toothless flyer with an enormous bony crest running the full length of its long skull."),
 ("coloborhynchus","Coloborhynchus","Coloborhynchus clavirostris","large pterosaur","pterosaur","earlycret","piscivore","pterosaur",
  "A robust fish-eating pterosaur with stout jaws bearing large gripping teeth at the tip."),
 ("zhejiangopterus","Zhejiangopterus","Zhejiangopterus linhaiensis","large pterosaur","pterosaur","latecret","carnivore","pterosaur",
  "A long-necked, toothless azhdarchid that probably stalked small prey on the ground like its giant relatives."),
 ("germanodactylus","Germanodactylus","Germanodactylus cristatus","pterosaur","pterosaur","jurassic","piscivore","pterosaur",
  "A small Jurassic pterosaur notable for a low bony crest along the top of its snout."),
 ("darwinopterus","Darwinopterus","Darwinopterus modularis","pterosaur","pterosaur","jurassic","carnivore","pterosaur",
  "A 'missing link' pterosaur combining an early-style body with the longer skull and neck of later forms."),
 ("sordes","Sordes","Sordes pilosus","pterosaur","pterosaur","jurassic","insectivore","pterosaur",
  "Fossils preserve a coat of hair-like fibres, showing many pterosaurs were furry rather than scaly."),
 ("cearadactylus","Cearadactylus","Cearadactylus atrox","large pterosaur","pterosaur","earlycret","piscivore","pterosaur",
  "A large fish-eater whose interlocking front teeth formed a trap for slippery prey."),
]

MARINE = [
 ("mosasaurus","Mosasaurus","Mosasaurus hoffmannii","marine reptile","marine","latecret","carnivore","plesiosaur",
  "A giant sea lizard up to about 17 metres long that ruled the oceans at the very end of the dinosaur age; it was a close cousin of today's monitor lizards and snakes."),
 ("plesiosaurus","Plesiosaurus","Plesiosaurus dolichodeirus","marine reptile","marine","jurassic","carnivore","plesiosaur",
  "It swam with four wing-like flippers and had a long neck and small head, the classic body plan that inspired the Loch Ness legend."),
 ("elasmosaurus","Elasmosaurus","Elasmosaurus platyurus","marine reptile","marine","latecret","piscivore","plesiosaur",
  "Its neck held over seventy bones and made up more than half its length, the longest neck of any animal ever."),
 ("ichthyosaurus","Ichthyosaurus","Ichthyosaurus communis","marine reptile","marine","jurassic","piscivore","plesiosaur",
  "A dolphin-shaped reptile with huge eyes that gave birth to live young at sea rather than laying eggs on land."),
 ("liopleurodon","Liopleurodon","Liopleurodon ferox","marine reptile","marine","jurassic","carnivore","plesiosaur",
  "A powerful short-necked pliosaur with a crocodile-like head and four large flippers, a top hunter of the Jurassic seas."),
 ("kronosaurus","Kronosaurus","Kronosaurus queenslandicus","marine reptile","marine","earlycret","carnivore","plesiosaur",
  "A massive pliosaur whose skull alone was over 2 metres long, armed with conical teeth as big as bananas."),
 ("tylosaurus","Tylosaurus","Tylosaurus proriger","marine reptile","marine","latecret","carnivore","plesiosaur",
  "One of the largest mosasaurs, with a hard bony snout it may have used to ram prey."),
 ("shonisaurus","Shonisaurus","Shonisaurus popularis","marine reptile","marine","triassic","piscivore","plesiosaur",
  "A giant Triassic ichthyosaur up to about 15 metres long, one of the largest marine reptiles of its time."),
 ("nothosaurus","Nothosaurus","Nothosaurus mirabilis","marine reptile","marine","triassic","piscivore","plesiosaur",
  "A slender, semi-aquatic Triassic hunter with webbed feet and needle-like teeth for trapping fish."),
 ("pliosaurus","Pliosaurus","Pliosaurus funkei","marine reptile","marine","jurassic","carnivore","plesiosaur",
  "A colossal short-necked pliosaur, nicknamed 'Predator X', with a bite force among the strongest ever estimated."),
 ("temnodontosaurus","Temnodontosaurus","Temnodontosaurus platyodon","marine reptile","marine","jurassic","carnivore","plesiosaur",
  "A large ichthyosaur with eyes around 20 centimetres across, among the biggest eyes of any animal."),
 ("archelon","Archelon","Archelon ischyros","prehistoric sea turtle","marine","latecret","omnivore","plesiosaur",
  "The largest sea turtle ever known, over 4 metres from flipper to flipper, with a leathery rather than solid shell."),
 ("dakosaurus","Dakosaurus","Dakosaurus maximus","marine crocodile relative","marine","jurassic","carnivore","plesiosaur",
  "A sea-going crocodile relative with a deep skull and serrated teeth, fully adapted to ocean life with flippers and a finned tail."),
 ("ophthalmosaurus","Ophthalmosaurus","Ophthalmosaurus icenicus","marine reptile","marine","jurassic","piscivore","plesiosaur",
  "Its name means 'eye lizard' for its enormous eyes, which let it hunt squid in deep, dark water."),
 ("mixosaurus","Mixosaurus","Mixosaurus cornalianus","marine reptile","marine","triassic","piscivore","plesiosaur",
  "A small early ichthyosaur that blended primitive and advanced features as the group adapted to the sea."),
 ("placodus","Placodus","Placodus gigas","marine reptile","marine","triassic","none","plesiosaur",
  "A stout Triassic reptile with buck teeth at the front and flat crushing plates behind for eating shellfish."),
 ("tanystropheus","Tanystropheus","Tanystropheus longobardicus","long-necked reptile","marine","triassic","piscivore","plesiosaur",
  "Its astonishing neck was longer than its body and tail combined, perhaps used to ambush fish from the shore."),
 ("henodus","Henodus","Henodus chelyops","marine reptile","marine","triassic","none","plesiosaur",
  "A placodont so flat and square-shelled it looked remarkably like a turtle, though it was not closely related."),
 ("globidens","Globidens","Globidens alabamaensis","marine reptile","marine","latecret","none","plesiosaur",
  "A mosasaur with rounded, ball-like teeth built for crushing the shells of clams and ammonites."),
 ("styxosaurus","Styxosaurus","Styxosaurus snowii","marine reptile","marine","latecret","piscivore","plesiosaur",
  "A long-necked elasmosaur; preserved stomach stones show it swallowed pebbles, perhaps to aid digestion or buoyancy."),
 ("cryptoclidus","Cryptoclidus","Cryptoclidus eurymerus","marine reptile","marine","jurassic","piscivore","plesiosaur",
  "A medium plesiosaur whose fine, interlocking teeth formed a sieve for trapping small fish and shrimp."),
 ("hainosaurus","Hainosaurus","Hainosaurus bernardi","marine reptile","marine","latecret","carnivore","plesiosaur",
  "A giant European mosasaur that rivalled Tylosaurus as a top predator of the chalk seas."),
 ("attenborosaurus","Attenborosaurus","Attenborosaurus conybeari","marine reptile","marine","jurassic","piscivore","plesiosaur",
  "An early Jurassic plesiosaur named in honour of the naturalist David Attenborough."),
 ("excalibosaurus","Excalibosaurus","Excalibosaurus costini","marine reptile","marine","jurassic","piscivore","plesiosaur",
  "Its long upper jaw stuck out far beyond the lower like a swordfish, giving it its sword-themed name."),
 ("simolestes","Simolestes","Simolestes vorax","marine reptile","marine","jurassic","carnivore","plesiosaur",
  "A short-necked pliosaur with a powerful bite, probably a hunter of squid and other large prey."),
 ("thalassomedon","Thalassomedon","Thalassomedon haningtoni","marine reptile","marine","latecret","piscivore","plesiosaur",
  "A long-necked plesiosaur over 11 metres long whose name means 'lord of the seas'."),
 ("rhomaleosaurus","Rhomaleosaurus","Rhomaleosaurus cramptoni","marine reptile","marine","jurassic","carnivore","plesiosaur",
  "An early pliosaur with a medium neck and large head that hunted in the early Jurassic seas."),
 ("platecarpus","Platecarpus","Platecarpus tympaniticus","marine reptile","marine","latecret","piscivore","plesiosaur",
  "A mid-sized mosasaur known from fossils so complete they preserve skin outlines and a tail fluke."),
 ("clidastes","Clidastes","Clidastes liodontus","marine reptile","marine","latecret","carnivore","plesiosaur",
  "One of the smallest and most agile mosasaurs, a swift hunter in shallow coastal seas."),
 ("brachauchenius","Brachauchenius","Brachauchenius lucasi","marine reptile","marine","cretaceous","carnivore","plesiosaur",
  "A short-necked pliosaur that survived into the Cretaceous, hunting in the seaway across North America."),
 ("psephoderma","Psephoderma","Psephoderma alpinum","marine reptile","marine","triassic","none","plesiosaur",
  "A placodont with a long shell and a flat, crushing beak for feeding on shellfish on the sea floor."),
]
