# -*- coding: utf-8 -*-
SAUROPODS = [
 ("brachiosaurus","Brachiosaurus","Brachiosaurus altithorax","giant sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "Its front legs were longer than its back legs, lifting its head high like a crane to browse the tops of trees."),
 ("apatosaurus","Apatosaurus","Apatosaurus ajax","giant sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "A massively built long-necked giant; the famous name 'Brontosaurus' was once thought to be the same animal."),
 ("brontosaurus","Brontosaurus","Brontosaurus excelsus","giant sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "Its name means 'thunder lizard'; once dismissed as a duplicate of Apatosaurus, it was restored as its own kind in 2015."),
 ("diplodocus","Diplodocus","Diplodocus longus","giant sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "Extremely long and whip-tailed, it could crack its tail like a bullwhip and stripped leaves with peg-like teeth."),
 ("argentinosaurus","Argentinosaurus","Argentinosaurus huinculensis","titanic sauropod dinosaur","sauropod","latecret","herbivore","sauropod",
  "Among the largest animals ever to walk the Earth, it may have weighed as much as ten elephants."),
 ("patagotitan","Patagotitan","Patagotitan mayorum","titanic sauropod dinosaur","sauropod","latecret","herbivore","sauropod",
  "Known from many bones, it is one of the largest dinosaurs reliably measured, longer than a basketball court."),
 ("dreadnoughtus","Dreadnoughtus","Dreadnoughtus schrani","titanic sauropod dinosaur","sauropod","latecret","herbivore","sauropod",
  "Its name means 'fears nothing'; it is known from an unusually complete giant skeleton."),
 ("camarasaurus","Camarasaurus","Camarasaurus supremus","large sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "The most common sauropod of Jurassic North America, with a short, boxy skull and spoon-shaped teeth."),
 ("mamenchisaurus","Mamenchisaurus","Mamenchisaurus hochuanensis","giant sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "It had perhaps the longest neck of any animal ever, making up nearly half its total length."),
 ("amargasaurus","Amargasaurus","Amargasaurus cazaui","sauropod dinosaur","sauropod","earlycret","herbivore","sauropod",
  "Two rows of tall spines ran down its neck and back, possibly supporting a sail or a pair of skin ridges."),
 ("nigersaurus","Nigersaurus","Nigersaurus taqueti","sauropod dinosaur","sauropod","earlycret","herbivore","sauropod",
  "It had a wide, straight-edged mouth like a vacuum cleaner, packed with hundreds of tiny teeth for cropping low plants."),
 ("saltasaurus","Saltasaurus","Saltasaurus loricatus","armoured sauropod dinosaur","sauropod","latecret","herbivore","sauropod",
  "A smaller sauropod whose back was studded with bony plates for protection, unusual armour for a long-neck."),
 ("shunosaurus","Shunosaurus","Shunosaurus lii","sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "Unusually for a sauropod, it had a small bony club on the end of its tail to swing at attackers."),
 ("europasaurus","Europasaurus","Europasaurus holgeri","dwarf sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "A dwarf long-neck only about the size of a cow, shrunk by living on a small prehistoric island."),
 ("alamosaurus","Alamosaurus","Alamosaurus sanjuanensis","titanic sauropod dinosaur","sauropod","latecret","herbivore","sauropod",
  "The last giant sauropod in North America, living right up to the end of the dinosaur age."),
 ("supersaurus","Supersaurus","Supersaurus vivianae","giant sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "One of the longest dinosaurs known, a Diplodocus relative that may have stretched over 30 metres."),
 ("barosaurus","Barosaurus","Barosaurus lentus","giant sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "A very long-necked relative of Diplodocus; its heart had to pump blood an enormous height to its head."),
 ("cetiosaurus","Cetiosaurus","Cetiosaurus oxoniensis","large sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "Its name means 'whale lizard'; it was one of the first sauropods ever discovered."),
 ("plateosaurus","Plateosaurus","Plateosaurus trossingensis","early long-necked dinosaur","earlydino","triassic","herbivore","sauropod",
  "One of the first large plant-eating dinosaurs, it could rear up on its back legs to reach high foliage."),
 ("riojasaurus","Riojasaurus","Riojasaurus incertus","early long-necked dinosaur","earlydino","triassic","herbivore","sauropod",
  "An early heavy plant-eater from Argentina, an ancestor-type of the later giant sauropods."),
 ("massospondylus","Massospondylus","Massospondylus carinatus","early long-necked dinosaur","earlydino","jurassic","herbivore","sauropod",
  "Known from some of the oldest dinosaur eggs and embryos ever found, revealing how its babies grew."),
 ("mussaurus","Mussaurus","Mussaurus patagonicus","early long-necked dinosaur","earlydino","triassic","herbivore","sauropod",
  "Its name means 'mouse lizard' from tiny hatchlings, but the adults grew to several metres long."),
 ("melanorosaurus","Melanorosaurus","Melanorosaurus readi","early long-necked dinosaur","earlydino","triassic","herbivore","sauropod",
  "A heavy early plant-eater that walked on all fours, close to the true giant sauropods."),
 ("brachytrachelopan","Brachytrachelopan","Brachytrachelopan mesai","short-necked sauropod dinosaur","sauropod","jurassic","herbivore","sauropod",
  "Strangely for a sauropod, it had an unusually short neck, likely to graze on low plants."),
 ("sauroposeidon","Sauroposeidon","Sauroposeidon proteles","giant sauropod dinosaur","sauropod","earlycret","herbivore","sauropod",
  "One of the tallest animals ever, its head may have reached six storeys above the ground."),
 ("rapetosaurus","Rapetosaurus","Rapetosaurus krausei","sauropod dinosaur","sauropod","latecret","herbivore","sauropod",
  "Known from a well-preserved skeleton from Madagascar, including a complete skull, which is rare for sauropods."),
 ("futalognkosaurus","Futalognkosaurus","Futalognkosaurus dukei","titanic sauropod dinosaur","sauropod","latecret","herbivore","sauropod",
  "A giant from Patagonia known from a very complete neck and body."),
]

STEGOSAURS = [
 ("stegosaurus","Stegosaurus","Stegosaurus stenops","plated dinosaur","stegosaur","jurassic","herbivore","stegosaur",
  "Two rows of tall bony plates lined its back, and four sharp spikes on its tail, nicknamed the 'thagomizer', were its main weapon."),
 ("kentrosaurus","Kentrosaurus","Kentrosaurus aethiopicus","plated dinosaur","stegosaur","jurassic","herbivore","stegosaur",
  "An African stegosaur bristling with paired spikes from its hips to the tip of its tail."),
 ("tuojiangosaurus","Tuojiangosaurus","Tuojiangosaurus multispinus","plated dinosaur","stegosaur","jurassic","herbivore","stegosaur",
  "A Chinese stegosaur with pointed plates and a spiked tail, well known from Asia."),
 ("huayangosaurus","Huayangosaurus","Huayangosaurus taibaii","plated dinosaur","stegosaur","jurassic","herbivore","stegosaur",
  "One of the earliest and most primitive stegosaurs, it still had small teeth at the front of its beak."),
 ("gigantspinosaurus","Gigantspinosaurus","Gigantspinosaurus sichuanensis","plated dinosaur","stegosaur","jurassic","herbivore","stegosaur",
  "It had enormous shoulder spikes far larger than its small back plates."),
 ("miragaia","Miragaia","Miragaia longicollum","plated dinosaur","stegosaur","jurassic","herbivore","stegosaur",
  "A stegosaur with a surprisingly long neck holding many more bones than most of its relatives."),
 ("dacentrurus","Dacentrurus","Dacentrurus armatus","plated dinosaur","stegosaur","jurassic","herbivore","stegosaur",
  "One of the first stegosaurs discovered, a large spiky plant-eater of Europe."),
 ("scelidosaurus","Scelidosaurus","Scelidosaurus harrisonii","early armoured dinosaur","ankylosaur","jurassic","herbivore","ankylosaur",
  "An early armoured plant-eater whose body was covered in rows of small bony studs."),
]

ANKYLOSAURS = [
 ("ankylosaurus","Ankylosaurus","Ankylosaurus magniventris","armoured dinosaur","ankylosaur","latecret","herbivore","ankylosaur",
  "Covered head to tail in bony armour, it swung a huge club of solid bone on the end of its tail like a sledgehammer."),
 ("euoplocephalus","Euoplocephalus","Euoplocephalus tutus","armoured dinosaur","ankylosaur","latecret","herbivore","ankylosaur",
  "Even its eyelids were armoured with bony shutters, and it carried a heavy tail club."),
 ("edmontonia","Edmontonia","Edmontonia rugosidens","armoured dinosaur","ankylosaur","latecret","herbivore","ankylosaur",
  "A nodosaur with rows of large forward-pointing shoulder spikes but no tail club."),
 ("sauropelta","Sauropelta","Sauropelta edwardsorum","armoured dinosaur","ankylosaur","earlycret","herbivore","ankylosaur",
  "Long spikes lined its neck and shoulders, guarding it from the predators of its day."),
 ("borealopelta","Borealopelta","Borealopelta markmitchelli","armoured dinosaur","ankylosaur","earlycret","herbivore","ankylosaur",
  "One of the best-preserved dinosaurs ever found, with skin and armour intact, even revealing it was reddish-brown with a pale belly."),
 ("gastonia","Gastonia","Gastonia burgei","armoured dinosaur","ankylosaur","earlycret","herbivore","ankylosaur",
  "A spiky armoured dinosaur with blade-like plates running along its tail."),
 ("nodosaurus","Nodosaurus","Nodosaurus textilis","armoured dinosaur","ankylosaur","earlycret","herbivore","ankylosaur",
  "It gave its family, the nodosaurs, its name; these armoured dinosaurs lacked a tail club."),
 ("pinacosaurus","Pinacosaurus","Pinacosaurus grangeri","armoured dinosaur","ankylosaur","latecret","herbivore","ankylosaur",
  "Known from many young skeletons found together, hinting that the youngsters may have lived in groups."),
 ("saichania","Saichania","Saichania chulsanensis","armoured dinosaur","ankylosaur","latecret","herbivore","ankylosaur",
  "Its name means 'beautiful one'; it was heavily armoured and built to survive the dry deserts of Mongolia."),
 ("polacanthus","Polacanthus","Polacanthus foxii","armoured dinosaur","ankylosaur","earlycret","herbivore","ankylosaur",
  "An early armoured dinosaur of Europe with tall spikes over its shoulders and a shield of bone over its hips."),
 ("zuul","Zuul","Zuul crurivastator","armoured dinosaur","ankylosaur","latecret","herbivore","ankylosaur",
  "Named after a monster from the film Ghostbusters; its species name means 'destroyer of shins' for its heavy tail club."),
 ("ankylonodosaurus","Panoplosaurus","Panoplosaurus mirus","armoured dinosaur","ankylosaur","latecret","herbivore","ankylosaur",
  "A well-armoured nodosaur with a broad, shielded head and spiky shoulders."),
]
