# -*- coding: utf-8 -*-
"""PaleoHype taxa: Cenozoic mammals, prehistoric birds, and early humans.
Tuple format: (key, name, sci, group, classGroup, periodKey, diet, art, trait)
"""

MAMMALS = [
 ("woolly-mammoth","Woolly mammoth","Mammuthus primigenius","prehistoric elephant","mammal","pleistocene","herbivore","mammoth",
  "Covered in shaggy hair with long curving tusks, it grazed the cold steppes of the Ice Age; some frozen bodies are so well preserved they still have skin and hair."),
 ("columbian-mammoth","Columbian mammoth","Mammuthus columbi","prehistoric elephant","mammal","pleistocene","herbivore","mammoth",
  "A larger, less hairy mammoth of warmer North America, standing up to about 4 metres tall at the shoulder."),
 ("mastodon","American mastodon","Mammut americanum","prehistoric relative of elephants","mammal","pleistocene","herbivore","mammoth",
  "A stocky, forest-dwelling cousin of mammoths whose cone-shaped cheek teeth were built for crushing twigs and leaves."),
 ("smilodon","Smilodon","Smilodon fatalis","sabre-toothed cat","mammal","pleistocene","carnivore","sabertooth",
  "The famous sabre-toothed cat, with canine teeth up to 18 centimetres long and powerful forelimbs for wrestling down prey."),
 ("woolly-rhino","Woolly rhinoceros","Coelodonta antiquitatis","prehistoric rhinoceros","mammal","pleistocene","herbivore","mammoth",
  "A thick-furred Ice Age rhino with two horns; it used its flattened front horn to sweep snow off the grass."),
 ("megatherium","Megatherium","Megatherium americanum","giant ground sloth","mammal","pleistocene","herbivore","groundsloth",
  "A giant ground sloth as big as an elephant that reared up on its hind legs to pull down branches with huge claws."),
 ("glyptodon","Glyptodon","Glyptodon clavipes","giant armoured mammal","mammal","pleistocene","herbivore","groundsloth",
  "A car-sized relative of armadillos encased in a domed shell of bony plates, with an armoured tail."),
 ("andrewsarchus","Andrewsarchus","Andrewsarchus mongoliensis","prehistoric hoofed carnivore","mammal","eocene","carnivore","sabertooth",
  "Known mainly from one enormous skull, it may have been the largest meat-eating land mammal ever, related to hoofed animals."),
 ("megacerops","Megacerops","Megacerops coloradensis","brontothere","mammal","eocene","herbivore","mammoth",
  "A rhino-like giant with a large Y-shaped bony horn on its nose, browsing the forests of ancient North America."),
 ("uintatherium","Uintatherium","Uintatherium anceps","prehistoric hoofed mammal","mammal","eocene","herbivore","mammoth",
  "An elephant-sized plant-eater with six blunt horns on its head and long sabre-like canine teeth in the males."),
 ("basilosaurus","Basilosaurus","Basilosaurus cetoides","prehistoric whale","mammal","eocene","carnivore","plesiosaur",
  "An early whale up to about 18 metres long with an eel-like body and tiny back legs left over from its land-living ancestors."),
 ("dorudon","Dorudon","Dorudon atrox","prehistoric whale","mammal","eocene","piscivore","plesiosaur",
  "A 5-metre early whale that swam with a tail fluke and still had small, useless hind legs."),
 ("doedicurus","Doedicurus","Doedicurus clavicaudatus","giant armoured mammal","mammal","pleistocene","herbivore","groundsloth",
  "A huge glyptodont whose tail ended in a heavy, spiked club it could swing like a mace."),
 ("macrauchenia","Macrauchenia","Macrauchenia patachonica","prehistoric hoofed mammal","mammal","pleistocene","herbivore","mammoth",
  "A camel-like animal with a long neck and a short trunk, belonging to a group of hoofed mammals unique to South America."),
 ("paraceratherium","Paraceratherium","Paraceratherium transouralicum","giant hornless rhino","mammal","oligocene","herbivore","mammoth",
  "The largest land mammal ever known, a hornless rhino that stood nearly 5 metres at the shoulder and browsed treetops like a giraffe."),
 ("megaloceros","Irish elk","Megaloceros giganteus","giant deer","mammal","pleistocene","herbivore","mammoth",
  "A giant Ice Age deer whose magnificent antlers could span 3.5 metres from tip to tip, the largest of any known deer."),
 ("gomphotherium","Gomphotherium","Gomphotherium angustidens","prehistoric relative of elephants","mammal","miocene","herbivore","mammoth",
  "An early elephant relative with four tusks, two curving up and two flattened ones pointing forward like a shovel."),
 ("arsinoitherium","Arsinoitherium","Arsinoitherium zitteli","prehistoric horned mammal","mammal","oligocene","herbivore","mammoth",
  "A rhino-like plant-eater that carried an enormous pair of hollow horns side by side on its snout."),
 ("entelodon","Entelodon","Entelodon magnus","entelodont","mammal","oligocene","omnivore","sabertooth",
  "A fierce pig relative the size of a cow, nicknamed the 'terminator pig', with bony knobs on its huge jaws."),
 ("hyaenodon","Hyaenodon","Hyaenodon horridus","creodont predator","mammal","oligocene","carnivore","sabertooth",
  "A powerful meat-eater from an extinct order of mammals, with shearing teeth and a strong bite."),
 ("chalicotherium","Chalicotherium","Chalicotherium goldfussi","clawed hoofed mammal","mammal","miocene","herbivore","groundsloth",
  "An odd relative of horses that walked on its knuckles and used long-clawed arms to hook branches like a ground sloth."),
 ("platybelodon","Platybelodon","Platybelodon grangeri","shovel-tusked relative of elephants","mammal","miocene","herbivore","mammoth",
  "An elephant relative whose flat, broad lower tusks formed a shovel-like 'chin' for scooping up water plants."),
 ("dire-wolf","Dire wolf","Aenocyon dirus","prehistoric wolf","mammal","pleistocene","carnivore","sabertooth",
  "A heavily built Ice Age wolf; thousands have been recovered from the La Brea tar pits in California."),
 ("american-lion","American lion","Panthera atrox","prehistoric big cat","mammal","pleistocene","carnivore","sabertooth",
  "One of the largest cats ever, an Ice Age lion noticeably bigger than today's African lions."),
 ("short-faced-bear","Giant short-faced bear","Arctodus simus","prehistoric bear","mammal","pleistocene","omnivore","sabertooth",
  "A towering Ice Age bear that stood over 3 metres tall on its hind legs, with unusually long legs for its size."),
 ("cave-bear","Cave bear","Ursus spelaeus","prehistoric bear","mammal","pleistocene","herbivore","sabertooth",
  "A large, mostly plant-eating Ice Age bear whose bones fill many European caves where it hibernated."),
 ("toxodon","Toxodon","Toxodon platensis","prehistoric hoofed mammal","mammal","pleistocene","herbivore","mammoth",
  "A hippo-like South American plant-eater collected by Charles Darwin during his voyage on the Beagle."),
 ("diprotodon","Diprotodon","Diprotodon optatum","giant marsupial","mammal","pleistocene","herbivore","groundsloth",
  "The largest marsupial that ever lived, a rhino-sized relative of wombats that roamed Ice Age Australia."),
 ("thylacoleo","Thylacoleo","Thylacoleo carnifex","marsupial lion","mammal","pleistocene","carnivore","sabertooth",
  "A pouched 'marsupial lion' with huge slicing cheek teeth and a thumb claw, and one of the strongest bites for its size."),
 ("procoptodon","Procoptodon","Procoptodon goliah","giant short-faced kangaroo","mammal","pleistocene","herbivore","groundsloth",
  "A giant Ice Age kangaroo, taller than a person, with a short flat face and long arms for reaching leaves."),
 ("castoroides","Castoroides","Castoroides ohioensis","giant beaver","mammal","pleistocene","herbivore","groundsloth",
  "A bear-sized beaver up to about 2 metres long, the largest rodent ever to live in North America."),
 ("deinotherium","Deinotherium","Deinotherium giganteum","prehistoric relative of elephants","mammal","miocene","herbivore","mammoth",
  "A huge elephant relative whose tusks grew from its lower jaw and curved downward and back."),
 ("stegodon","Stegodon","Stegodon zdanskyi","prehistoric relative of elephants","mammal","pliocene","herbivore","mammoth",
  "A relative of elephants with tusks so long and close together that its trunk had to drape over the side."),
 ("elasmotherium","Elasmotherium","Elasmotherium sibiricum","giant prehistoric rhino","mammal","pleistocene","herbivore","mammoth",
  "A giant rhino sometimes called the 'Siberian unicorn' for the single enormous horn it likely bore on its forehead."),
 ("hyracotherium","Hyracotherium","Hyracotherium leporinum","dawn horse","mammal","eocene","herbivore","groundsloth",
  "A dog-sized early horse with several toes on each foot, showing how horses began small in ancient forests."),
 ("mesohippus","Mesohippus","Mesohippus bairdii","prehistoric horse","mammal","oligocene","herbivore","groundsloth",
  "A three-toed early horse the size of a sheep, a step along the long road to modern horses."),
 ("ambulocetus","Ambulocetus","Ambulocetus natans","walking whale","mammal","eocene","carnivore","plesiosaur",
  "A crocodile-like early whale with strong legs, able to both walk on land and swim, capturing whales' move to the sea."),
 ("pakicetus","Pakicetus","Pakicetus inachus","earliest whale relative","mammal","eocene","carnivore","sabertooth",
  "A wolf-sized, four-legged land animal whose ear bones reveal it was one of the very first relatives of whales."),
 ("indricotherium","Indricotherium","Paraceratherium bugtiense","giant hornless rhino","mammal","oligocene","herbivore","mammoth",
  "Another name used for the colossal hornless rhinos that were the tallest land mammals of all time."),
 ("synthetoceras","Synthetoceras","Synthetoceras tricornatus","prehistoric hoofed mammal","mammal","miocene","herbivore","mammoth",
  "A deer-like animal with a remarkable Y-shaped horn growing from its nose, found only in North America."),
 ("megistotherium","Megistotherium","Megistotherium osteothlastes","creodont predator","mammal","miocene","carnivore","sabertooth",
  "One of the largest meat-eating land mammals, a giant hyaenodont that may have hunted early elephants."),
 ("daeodon","Daeodon","Daeodon shoshonensis","entelodont","mammal","miocene","omnivore","sabertooth",
  "A giant North American 'hell pig' standing about 2 metres at the shoulder with a massive, knob-cheeked skull."),
 ("phorusrhacos-mammal-placeholder","Coryphodon","Coryphodon eocaenus","prehistoric hoofed mammal","mammal","eocene","herbivore","mammoth",
  "A hippo-like swamp dweller, one of the first large plant-eating mammals after the dinosaurs disappeared."),
 ("thylacosmilus","Thylacosmilus","Thylacosmilus atrox","sabre-toothed marsupial relative","mammal","pliocene","carnivore","sabertooth",
  "A South American pouched mammal that evolved sabre teeth separately from true cats, with ever-growing fangs."),
 ("repenomamus","Repenomamus","Repenomamus robustus","prehistoric mammal","mammal","earlycret","carnivore","sabertooth",
  "A badger-sized mammal that lived among the dinosaurs; one fossil preserves a baby dinosaur in its stomach."),
 ("megalonyx","Megalonyx","Megalonyx jeffersonii","giant ground sloth","mammal","pleistocene","herbivore","groundsloth",
  "A bear-sized ground sloth first studied by Thomas Jefferson, who gave the science of fossils an early boost in America."),
 ("eremotherium","Eremotherium","Eremotherium laurillardi","giant ground sloth","mammal","pleistocene","herbivore","groundsloth",
  "A giant ground sloth as large as Megatherium that ranged from South America up into the southern United States."),
 ("notiomastodon","Notiomastodon","Notiomastodon platensis","prehistoric relative of elephants","mammal","pleistocene","herbivore","mammoth",
  "A South American relative of elephants that survived until the end of the last Ice Age."),
 ("amphicyon","Amphicyon","Amphicyon major","bear-dog","mammal","miocene","carnivore","sabertooth",
  "A 'bear-dog' that was neither quite bear nor dog, a powerful predator built like a heavy wolf."),
 ("moropus","Moropus","Moropus elatus","clawed hoofed mammal","mammal","miocene","herbivore","groundsloth",
  "A horse relative with clawed feet instead of hooves, using its claws to hook and strip vegetation."),
 ("palaeoloxodon","Straight-tusked elephant","Palaeoloxodon antiquus","prehistoric elephant","mammal","pleistocene","herbivore","mammoth",
  "A huge elephant of warm Ice Age Europe, even larger than today's African elephants, with long straight tusks."),
 ("sivatherium","Sivatherium","Sivatherium giganteum","prehistoric giraffe relative","mammal","pliocene","herbivore","mammoth",
  "A heavily built relative of giraffes with a short neck and large, branching antler-like horns."),
 ("kelenken-mammal-placeholder","Embolotherium","Embolotherium andrewsi","brontothere","mammal","eocene","herbivore","mammoth",
  "A brontothere with a large, hollow, ram-like bony plate rising from its snout instead of paired horns."),
 ("borophagus","Borophagus","Borophagus secundus","bone-crushing dog","mammal","pliocene","carnivore","sabertooth",
  "A hyena-like dog with massive teeth and jaws strong enough to crack open bones for the marrow."),
 ("megantereon","Megantereon","Megantereon cultridens","sabre-toothed cat","mammal","pliocene","carnivore","sabertooth",
  "A leopard-sized sabre-toothed cat, an early member of the group that later produced the famous Smilodon."),
]

BIRDS = [
 ("archaeopteryx","Archaeopteryx","Archaeopteryx lithographica","early bird","bird","jurassic","carnivore","terrorbird",
  "A crow-sized animal with feathered wings but also teeth, claws and a bony tail, a famous link between dinosaurs and birds."),
 ("phorusrhacos","Phorusrhacos","Phorusrhacos longissimus","terror bird","bird","miocene","carnivore","terrorbird",
  "A giant flightless 'terror bird' up to 2.5 metres tall with a huge hooked beak, a top predator of ancient South America."),
 ("gastornis","Gastornis","Gastornis parisiensis","giant flightless bird","bird","eocene","herbivore","terrorbird",
  "A massive flightless bird with a deep, powerful beak; once thought a fierce hunter, it may have eaten tough plants and seeds."),
 ("argentavis","Argentavis","Argentavis magnificens","giant prehistoric bird","bird","miocene","scavenger","terrorbird",
  "One of the largest flying birds ever, with a wingspan around 6 to 7 metres, soaring over the plains of ancient Argentina."),
 ("pelagornis","Pelagornis","Pelagornis sandersi","giant seabird","bird","miocene","piscivore","terrorbird",
  "A seabird with the largest known wingspan of any bird, perhaps over 6 metres, and bony tooth-like spikes on its beak."),
 ("aepyornis","Elephant bird","Aepyornis maximus","giant flightless bird","bird","pleistocene","herbivore","terrorbird",
  "A huge flightless bird of Madagascar standing about 3 metres tall that laid the largest eggs of any known animal."),
 ("dinornis","Giant moa","Dinornis robustus","giant flightless bird","bird","pleistocene","herbivore","terrorbird",
  "A towering flightless bird of New Zealand reaching about 3.6 metres with neck outstretched, hunted to extinction by people."),
 ("hesperornis","Hesperornis","Hesperornis regalis","prehistoric diving bird","bird","latecret","piscivore","terrorbird",
  "A large flightless diving bird of the dinosaur age that swam with powerful feet and still had teeth in its beak."),
 ("ichthyornis","Ichthyornis","Ichthyornis dispar","prehistoric seabird","bird","latecret","piscivore","terrorbird",
  "A tern-like seabird from the time of the dinosaurs that could fly well but still had small teeth."),
 ("confuciusornis","Confuciusornis","Confuciusornis sanctus","early bird","bird","earlycret","omnivore","terrorbird",
  "An early bird with a true toothless beak; males had a pair of very long ribbon-like tail feathers."),
 ("titanis","Titanis","Titanis walleri","terror bird","bird","pliocene","carnivore","terrorbird",
  "The only terror bird known to have reached North America, a tall flightless predator from Florida and Texas."),
 ("kelenken","Kelenken","Kelenken guillermoi","terror bird","bird","miocene","carnivore","terrorbird",
  "A terror bird with one of the largest bird skulls ever, around 70 centimetres long, ending in a great hooked beak."),
 ("microraptor-bird-placeholder","Sinornis","Sinornis santensis","early bird","bird","earlycret","insectivore","terrorbird",
  "A sparrow-sized early bird that, unlike Archaeopteryx, could already fold its wings and perch much like modern birds."),
 ("genyornis","Genyornis","Genyornis newtoni","giant flightless bird","bird","pleistocene","herbivore","terrorbird",
  "A heavy flightless bird of Ice Age Australia; its broken eggshells are among the clues to its disappearance."),
 ("presbyornis","Presbyornis","Presbyornis pervetus","prehistoric waterbird","bird","eocene","filter","terrorbird",
  "A long-legged early relative of ducks that gathered in huge flocks around ancient lakes."),
 ("osteodontornis","Osteodontornis","Osteodontornis orri","giant seabird","bird","miocene","piscivore","terrorbird",
  "A giant soaring seabird with bony tooth-like points lining its beak for gripping slippery fish."),
]

HUMANS = [
 ("australopithecus","Australopithecus (Lucy)","Australopithecus afarensis","early human relative","human","pliocene","omnivore","earlyhuman",
  "Known from the famous skeleton 'Lucy', this small ape-like relative already walked upright on two legs over 3 million years ago."),
 ("homo-habilis","Homo habilis","Homo habilis","early human","human","pleistocene","omnivore","earlyhuman",
  "An early member of our own genus whose name means 'handy man' for the simple stone tools found alongside it."),
 ("homo-erectus","Homo erectus","Homo erectus","early human","human","pleistocene","omnivore","earlyhuman",
  "A tall, fully upright early human that spread out of Africa across Asia and likely learned to use fire."),
 ("neanderthal","Neanderthal","Homo neanderthalensis","early human","human","pleistocene","omnivore","earlyhuman",
  "Stocky, strong, cold-adapted relatives of ours who made tools, used fire, cared for their sick and buried their dead."),
 ("homo-floresiensis","Homo floresiensis","Homo floresiensis","early human","human","pleistocene","omnivore","earlyhuman",
  "A tiny human species barely a metre tall, nicknamed 'the Hobbit', that lived on the Indonesian island of Flores."),
 ("paranthropus","Paranthropus","Paranthropus boisei","early human relative","human","pleistocene","herbivore","earlyhuman",
  "A heavy-jawed relative nicknamed 'Nutcracker Man' for the huge molars and crested skull it used to chew tough plants."),
 ("ardipithecus","Ardipithecus","Ardipithecus ramidus","early human relative","human","pliocene","omnivore","earlyhuman",
  "An early relative from over 4 million years ago, known from a skeleton called 'Ardi', that climbed trees yet walked upright."),
 ("sahelanthropus","Sahelanthropus","Sahelanthropus tchadensis","early human relative","human","miocene","omnivore","earlyhuman",
  "One of the oldest known members of the human family, living around 7 million years ago near the dawn of our lineage."),
 ("homo-heidelbergensis","Homo heidelbergensis","Homo heidelbergensis","early human","human","pleistocene","omnivore","earlyhuman",
  "A large-brained early human, likely a shared ancestor of both Neanderthals and our own species."),
 ("gigantopithecus","Gigantopithecus","Gigantopithecus blacki","giant prehistoric ape","human","pleistocene","herbivore","earlyhuman",
  "The largest ape that ever lived, perhaps 3 metres tall, known mainly from enormous teeth and jaws found in China."),
 ("australopithecus-africanus","Australopithecus africanus","Australopithecus africanus","early human relative","human","pliocene","omnivore","earlyhuman",
  "Known from the 'Taung Child', the first early human relative ever found in Africa, proving our family began there."),
 ("homo-naledi","Homo naledi","Homo naledi","early human relative","human","pleistocene","omnivore","earlyhuman",
  "A small-brained relative whose many bones were found deep in a South African cave, hinting it may have placed its dead there."),
 ("denisovan","Denisovan","Homo sp. (Denisova)","early human","human","pleistocene","omnivore","earlyhuman",
  "A mysterious cousin of Neanderthals known mostly from DNA in a few bones, who once lived across Asia."),
]
