# -*- coding: utf-8 -*-
"""PaleoHype taxa: ceratopsians, pachycephalosaurs, ornithopods/hadrosaurs.
Tuple format: (key, name, sci, group, classGroup, periodKey, diet, art, trait)
Only well-established paleontology.
"""

CERATOPSIANS = [
 ("triceratops","Triceratops","Triceratops horridus","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "It carried two long brow horns and a shorter nose horn above a huge bony neck frill, and shared its world with Tyrannosaurus rex."),
 ("styracosaurus","Styracosaurus","Styracosaurus albertensis","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "A long nose horn and a fan of straight spikes around its frill made it one of the most spectacular horned dinosaurs."),
 ("pentaceratops","Pentaceratops","Pentaceratops sternbergii","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "It had one of the largest skulls of any land animal, with a frill that could be over a metre tall."),
 ("centrosaurus","Centrosaurus","Centrosaurus apertus","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Huge bone-beds show it lived in herds of thousands, with a single hooked horn on its nose."),
 ("protoceratops","Protoceratops","Protoceratops andrewsi","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "A sheep-sized early relative of the horned dinosaurs, it had a frill but no true horns, and is famous from a fossil locked in battle with a Velociraptor."),
 ("psittacosaurus","Psittacosaurus","Psittacosaurus mongoliensis","early horned dinosaur","ceratopsian","earlycret","herbivore","ceratopsian",
  "Its name means 'parrot lizard' for its deep beak, and rare fossils preserve a fan of bristles on its tail."),
 ("einiosaurus","Einiosaurus","Einiosaurus procurvicornis","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Its forward-curving nose horn bent down like a bottle-opener, a shape seen in no other dinosaur."),
 ("kosmoceratops","Kosmoceratops","Kosmoceratops richardsoni","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "It bore fifteen horns and hornlets on its head, including a row that curled down over its frill like a fringe."),
 ("chasmosaurus","Chasmosaurus","Chasmosaurus belli","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Its enormous frill was pierced by two large openings, making it lighter than it looked."),
 ("pachyrhinosaurus","Pachyrhinosaurus","Pachyrhinosaurus canadensis","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Instead of a horn it had a thick, flat pad of rough bone on its snout called a boss."),
 ("torosaurus","Torosaurus","Torosaurus latus","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "It had one of the longest skulls of any land animal that ever lived, much of it taken up by its huge frill."),
 ("achelousaurus","Achelousaurus","Achelousaurus horneri","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Rough bosses replaced the horns on its nose and brow, and a pair of spikes pointed back from its frill."),
 ("diabloceratops","Diabloceratops","Diabloceratops eatoni","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Two long, devil-like spikes rose from the top of its frill, giving it its name."),
 ("regaliceratops","Regaliceratops","Regaliceratops peterhewsi","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Its frill was ringed with plates shaped like a crown, earning it the nickname 'Hellboy'."),
 ("nasutoceratops","Nasutoceratops","Nasutoceratops titusi","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "It had an unusually large nose and long, forward-curving horns like those of a modern cow."),
 ("zuniceratops","Zuniceratops","Zuniceratops christopheri","early horned dinosaur","ceratopsian","cretaceous","herbivore","ceratopsian",
  "One of the earliest known horned dinosaurs with brow horns, helping show how the group's horns first appeared."),
 ("leptoceratops","Leptoceratops","Leptoceratops gracilis","small horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "A small, lightly built relative of the giant horned dinosaurs that could probably run on two legs."),
 ("anchiceratops","Anchiceratops","Anchiceratops ornatus","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Its rectangular frill was lined with bony knobs along the edge."),
 ("albertaceratops","Albertaceratops","Albertaceratops nesmoi","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "It combined long brow horns with the curled frill hooks of its short-horned relatives."),
 ("medusaceratops","Medusaceratops","Medusaceratops lokii","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Its name honours Medusa for the long, snaking hooks that curled from the edges of its frill."),
 ("bagaceratops","Bagaceratops","Bagaceratops rozhdestvenskyi","small horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "A small Mongolian relative of Protoceratops with a tiny nose horn and a short frill."),
 ("avaceratops","Avaceratops","Avaceratops lammersi","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "A small horned dinosaur first known from a single young individual found in Montana."),
 ("coronosaurus","Coronosaurus","Coronosaurus brinkmani","horned dinosaur","ceratopsian","latecret","herbivore","ceratopsian",
  "Clusters of small horns crowded together at the top of its frill like a crown."),
]

PACHYCEPHALOSAURS = [
 ("pachycephalosaurus","Pachycephalosaurus","Pachycephalosaurus wyomingensis","bone-headed dinosaur","pachy","latecret","herbivore","pachy",
  "The dome of solid bone on top of its skull was up to 25 centimetres thick, ringed with small bony spikes."),
 ("stegoceras","Stegoceras","Stegoceras validum","bone-headed dinosaur","pachy","latecret","herbivore","pachy",
  "A smaller dome-headed dinosaur whose many skulls have helped scientists study how the thick domes grew."),
 ("dracorex","Dracorex","Dracorex hogwartsia","bone-headed dinosaur","pachy","latecret","herbivore","pachy",
  "Its flat, spiky skull earned the name 'dragon king of Hogwarts'; some scientists think it is a young Pachycephalosaurus."),
 ("stygimoloch","Stygimoloch","Stygimoloch spinifer","bone-headed dinosaur","pachy","latecret","herbivore","pachy",
  "It sported long spikes at the back of its skull; like Dracorex it may be a growth stage of Pachycephalosaurus."),
 ("homalocephale","Homalocephale","Homalocephale calathocercos","bone-headed dinosaur","pachy","latecret","herbivore","pachy",
  "Instead of a tall dome it had a flat, thick, wedge-shaped skull roof."),
 ("prenocephale","Prenocephale","Prenocephale prenes","bone-headed dinosaur","pachy","latecret","herbivore","pachy",
  "Its rounded dome was edged with a row of small bony bumps and spikes."),
 ("wannanosaurus","Wannanosaurus","Wannanosaurus yansiensis","bone-headed dinosaur","pachy","latecret","herbivore","pachy",
  "One of the smallest and most primitive bone-headed dinosaurs, with a nearly flat skull."),
]

ORNITHOPODS = [
 ("iguanodon","Iguanodon","Iguanodon bernissartensis","ornithopod dinosaur","ornithopod","earlycret","herbivore","hadrosaur",
  "It had a spike on each thumb for defence and could walk on two legs or all fours; it was one of the first dinosaurs ever named."),
 ("parasaurolophus","Parasaurolophus","Parasaurolophus walkeri","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "The long, hollow tube curving back from its head may have worked like a trumpet to make deep calls."),
 ("edmontosaurus","Edmontosaurus","Edmontosaurus regalis","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A large, flat-headed hadrosaur with hundreds of grinding teeth, it is among the best-known dinosaurs from skin and even soft-tissue fossils."),
 ("maiasaura","Maiasaura","Maiasaura peeblesorum","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "Its name means 'good mother lizard'; nests, eggs and babies show it cared for its young after they hatched."),
 ("corythosaurus","Corythosaurus","Corythosaurus casuarius","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A tall, rounded crest like a helmet sat on its head, hollow inside and linked to its nose."),
 ("lambeosaurus","Lambeosaurus","Lambeosaurus lambei","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "Its hatchet-shaped hollow crest leaned forward over its snout."),
 ("shantungosaurus","Shantungosaurus","Shantungosaurus giganteus","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "One of the largest known duck-billed dinosaurs, it could reach about 15 metres in length."),
 ("hypsilophodon","Hypsilophodon","Hypsilophodon foxii","small ornithopod dinosaur","ornithopod","earlycret","herbivore","hadrosaur",
  "A small, fast plant-eater built for running, once wrongly thought to live in trees."),
 ("tenontosaurus","Tenontosaurus","Tenontosaurus tilletti","ornithopod dinosaur","ornithopod","earlycret","herbivore","hadrosaur",
  "This medium-sized plant-eater had an unusually long, stiff tail and is often found near the raptor Deinonychus."),
 ("ouranosaurus","Ouranosaurus","Ouranosaurus nigeriensis","ornithopod dinosaur","ornithopod","earlycret","herbivore","hadrosaur",
  "Tall spines along its back may have held a sail or a fatty hump, useful in its hot African home."),
 ("saurolophus","Saurolophus","Saurolophus osborni","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A solid, spike-like crest pointed up and back from the top of its skull."),
 ("brachylophosaurus","Brachylophosaurus","Brachylophosaurus canadensis","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A famous mummified specimen nicknamed 'Leonardo' preserved its skin, muscles and last meal."),
 ("gryposaurus","Gryposaurus","Gryposaurus notabilis","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "It had a distinctive arched, roman-nosed snout instead of a hollow crest."),
 ("tsintaosaurus","Tsintaosaurus","Tsintaosaurus spinorhinus","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A tall, hollow crest rose straight up from between its eyes like a unicorn's horn."),
 ("kritosaurus","Kritosaurus","Kritosaurus navajovius","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A flat-headed hadrosaur with a humped, roman nose, named from fossils in New Mexico."),
 ("hadrosaurus","Hadrosaurus","Hadrosaurus foulkii","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "Found in New Jersey in 1858, it was the first nearly complete dinosaur skeleton ever discovered and proved some dinosaurs walked on two legs."),
 ("camptosaurus","Camptosaurus","Camptosaurus dispar","ornithopod dinosaur","ornithopod","jurassic","herbivore","hadrosaur",
  "A sturdy Jurassic plant-eater and early relative of Iguanodon, it had a beak and rows of grinding cheek teeth."),
 ("dryosaurus","Dryosaurus","Dryosaurus altus","small ornithopod dinosaur","ornithopod","jurassic","herbivore","hadrosaur",
  "A small, long-legged Jurassic runner with no front teeth, cropping plants with its beak."),
 ("muttaburrasaurus","Muttaburrasaurus","Muttaburrasaurus langdoni","ornithopod dinosaur","ornithopod","earlycret","herbivore","hadrosaur",
  "This Australian plant-eater had a hollow, bony bump on its snout that may have boosted its calls."),
 ("olorotitan","Olorotitan","Olorotitan arharensis","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "Its broad, fan-shaped hollow crest swept back like a hatchet from a remarkably long-necked body."),
 ("heterodontosaurus","Heterodontosaurus","Heterodontosaurus tucki","early ornithischian dinosaur","ornithopod","jurassic","omnivore","hadrosaur",
  "A small early plant-eater unusual for its three kinds of teeth, including a pair of tusks like a boar's."),
 ("tethyshadros","Tethyshadros","Tethyshadros insularis","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A small island-dwelling hadrosaur from what is now Italy, an example of animals shrinking on islands."),
 ("mantellisaurus","Mantellisaurus","Mantellisaurus atherfieldensis","ornithopod dinosaur","ornithopod","earlycret","herbivore","hadrosaur",
  "A lighter, more lightly built cousin of Iguanodon, also armed with a thumb spike."),
 ("nipponosaurus","Nipponosaurus","Nipponosaurus sachalinensis","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A small crested hadrosaur and one of the few dinosaurs first described from Japanese-held territory."),
 ("bactrosaurus","Bactrosaurus","Bactrosaurus johnsoni","duck-billed dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "An early, primitive hadrosaur that helps show how the duck-billed dinosaurs first arose in Asia."),
 ("rhabdodon","Rhabdodon","Rhabdodon priscus","ornithopod dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A stocky plant-eater that lived on the chain of islands that was Late Cretaceous Europe."),
 ("thescelosaurus","Thescelosaurus","Thescelosaurus neglectus","small ornithopod dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A heavily built small plant-eater that was among the last of its kind before the great extinction."),
 ("orodromeus","Orodromeus","Orodromeus makelai","small ornithopod dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A small, swift plant-eater whose name means 'mountain runner', found near Maiasaura nesting grounds."),
 ("lurdusaurus","Lurdusaurus","Lurdusaurus arenatus","ornithopod dinosaur","ornithopod","earlycret","herbivore","hadrosaur",
  "An unusually heavy, hippo-like relative of Iguanodon from the rivers of ancient Africa."),
 ("zalmoxes","Zalmoxes","Zalmoxes robustus","ornithopod dinosaur","ornithopod","latecret","herbivore","hadrosaur",
  "A small, robust plant-eater from the dwarf-dinosaur island fauna of Late Cretaceous Romania."),
]
