# -*- coding: utf-8 -*-
"""PaleoHype taxa: Ediacaran life, Paleozoic invertebrates/arthropods/trilobites,
prehistoric fish and sharks, and prehistoric plants.
Tuple format: (key, name, sci, group, classGroup, periodKey, diet, art, trait)
"""

EDIACARAN = [
 ("dickinsonia","Dickinsonia","Dickinsonia costata","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A flat, oval, ribbed creature among the earliest large animals known; chemical traces in fossils confirm it was an animal."),
 ("charnia","Charnia","Charnia masoni","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A feather-shaped frond anchored to the deep sea floor; it was one of the first complex fossils found in rocks older than the Cambrian."),
 ("spriggina","Spriggina","Spriggina floundersi","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A small, segmented, worm-like animal with a crescent-shaped head end, possibly an early relative of arthropods."),
 ("kimberella","Kimberella","Kimberella quadrata","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A slug-like animal that left scratch marks where it scraped food off the sea floor, hinting at an early mollusc."),
 ("tribrachidium","Tribrachidium","Tribrachidium heraldicum","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A disc-shaped creature with three arms spiralling out from its centre, a body plan with no living equal."),
 ("rangea","Rangea","Rangea schneiderhoehni","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A three-dimensional frond built from repeating branch units, one of the classic Ediacaran 'rangeomorphs'."),
 ("cyclomedusa","Cyclomedusa","Cyclomedusa davidi","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A round fossil with concentric rings, once thought to be a jellyfish but probably a holdfast or colony."),
 ("yorgia","Yorgia","Yorgia waggoneri","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A flat, segmented animal that left a trail of body imprints as it fed, capturing its own movements in stone."),
 ("parvancorina","Parvancorina","Parvancorina minchami","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A tiny shield-shaped animal with a raised anchor-like ridge, perhaps related to early arthropods."),
 ("pteridinium","Pteridinium","Pteridinium simplex","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A three-vaned, tube-like organism that lived partly buried in the sea floor sediment."),
 ("arkarua","Arkarua","Arkarua adami","Ediacaran life-form","ediacaran","ediacaran","filter","ediacaran",
  "A small disc with a five-pointed star on top, possibly an early relative of starfish and sea urchins."),
]

INVERTS = [
 ("anomalocaris","Anomalocaris","Anomalocaris canadensis","prehistoric arthropod","arthropod","cambrian","carnivore","anomalocaris",
  "A metre-long Cambrian predator with two grasping arms and a circle of plates for a mouth; it was one of the first large hunters on Earth."),
 ("opabinia","Opabinia","Opabinia regalis","prehistoric arthropod","arthropod","cambrian","carnivore","anomalocaris",
  "A bizarre Cambrian animal with five eyes and a long flexible nozzle ending in a grasping claw."),
 ("hallucigenia","Hallucigenia","Hallucigenia sparsa","prehistoric arthropod","arthropod","cambrian","filter","anomalocaris",
  "A spiny worm-like animal so strange that scientists at first reconstructed it upside down and back to front."),
 ("wiwaxia","Wiwaxia","Wiwaxia corrugata","prehistoric invertebrate","invert","cambrian","filter","anomalocaris",
  "A small slug-like Cambrian animal armoured with overlapping scales and two rows of upright spines."),
 ("marrella","Marrella","Marrella splendens","prehistoric arthropod","arthropod","cambrian","filter","anomalocaris",
  "The most common animal in the Burgess Shale, a delicate arthropod with two pairs of swept-back head spines."),
 ("trilobite","Trilobite","Elrathia kingii","trilobite","trilobite","cambrian","filter","trilobite",
  "Trilobites were sea arthropods whose hard shell was divided into three lengthwise lobes; they thrived for almost 300 million years."),
 ("calymene","Calymene","Calymene blumenbachii","trilobite","trilobite","silurian","filter","trilobite",
  "A trilobite nicknamed the 'Dudley locust' that could roll into a ball to protect its soft underside."),
 ("phacops","Phacops","Phacops rana","trilobite","trilobite","devonian","filter","trilobite",
  "A trilobite famous for its large, complex compound eyes made of many calcite lenses."),
 ("isotelus","Isotelus","Isotelus rex","giant trilobite","trilobite","ordovician","filter","trilobite",
  "One of the largest trilobites known, reaching over 70 centimetres long in the Ordovician seas."),
 ("redlichia","Redlichia","Redlichia takooensis","trilobite","trilobite","cambrian","filter","trilobite",
  "A large early Cambrian trilobite; some fossils even show bite marks, evidence of ancient predators."),
 ("cameroceras","Cameroceras","Cameroceras trentonense","prehistoric cephalopod","invert","ordovician","carnivore","ammonite",
  "A giant straight-shelled relative of squid whose cone-shaped shell may have reached several metres, a top Ordovician predator."),
 ("orthoceras","Orthoceras","Orthoceras regulare","prehistoric cephalopod","invert","ordovician","carnivore","ammonite",
  "A squid-like animal that lived inside a long, straight, chambered shell, common in ancient seas."),
 ("eurypterus","Eurypterus","Eurypterus remipes","sea scorpion","arthropod","silurian","carnivore","eurypterid",
  "A sea scorpion with paddle-like back legs for swimming; it is the state fossil of New York."),
 ("jaekelopterus","Jaekelopterus","Jaekelopterus rhenaniae","giant sea scorpion","arthropod","devonian","carnivore","eurypterid",
  "The largest arthropod ever known, a sea scorpion whose grasping claws alone suggest a body over 2.5 metres long."),
 ("pterygotus","Pterygotus","Pterygotus anglicus","giant sea scorpion","arthropod","silurian","carnivore","eurypterid",
  "A huge sea scorpion with large eyes and toothed claws, a fearsome hunter of early fish."),
 ("arthropleura","Arthropleura","Arthropleura armata","giant millipede","arthropod","carbonif","herbivore","eurypterid",
  "The largest land invertebrate ever, a millipede relative up to about 2.5 metres long that roamed the coal forests."),
 ("meganeura","Meganeura","Meganeura monyi","giant dragonfly","arthropod","carbonif","carnivore","eurypterid",
  "A dragonfly relative with a wingspan around 70 centimetres, able to grow huge in the oxygen-rich Carboniferous air."),
 ("pulmonoscorpius","Pulmonoscorpius","Pulmonoscorpius kirktonensis","giant scorpion","arthropod","carbonif","carnivore","eurypterid",
  "A land scorpion up to about 70 centimetres long that breathed air and hunted in the coal swamps."),
 ("ammonite","Ammonite","Ammonoidea","prehistoric cephalopod","invert","jurassic","carnivore","ammonite",
  "Ammonites were squid relatives that lived in beautiful coiled shells; their fossils are so widespread they help date the rocks."),
 ("belemnite","Belemnite","Belemnitida","prehistoric cephalopod","invert","jurassic","carnivore","ammonite",
  "Squid-like animals whose bullet-shaped internal shells are common fossils; they swam the seas of the dinosaur age."),
 ("helicoprion","Helicoprion","Helicoprion bessonowi","prehistoric cartilaginous fish","shark","permian","carnivore","shark",
  "A shark relative whose lower jaw held a bizarre circular saw-like spiral of teeth, called a tooth-whorl."),
 ("dunkleosteus","Dunkleosteus","Dunkleosteus terrelli","armoured fish","fish","devonian","carnivore","dunkleosteus",
  "A giant armoured fish up to about 6 metres long whose head was sheathed in bony plates; instead of teeth it had self-sharpening bony blades."),
 ("tiktaalik","Tiktaalik","Tiktaalik roseae","lobe-finned fish","fish","devonian","carnivore","dunkleosteus",
  "A famous 'fishapod' with a flat head, neck and sturdy fins, capturing the moment fish began moving onto land."),
 ("eusthenopteron","Eusthenopteron","Eusthenopteron foordi","lobe-finned fish","fish","devonian","carnivore","dunkleosteus",
  "A lobe-finned fish with limb-like bones in its fins, close to the ancestors of the first four-legged animals."),
 ("cephalaspis","Cephalaspis","Cephalaspis lyelli","jawless fish","fish","devonian","filter","dunkleosteus",
  "An early jawless fish whose head was covered by a single broad, horseshoe-shaped bony shield."),
 ("bothriolepis","Bothriolepis","Bothriolepis canadensis","armoured fish","fish","devonian","filter","dunkleosteus",
  "A small armoured fish with bony, jointed, arm-like fins, one of the most common Devonian fossils worldwide."),
 ("xiphactinus","Xiphactinus","Xiphactinus audax","prehistoric bony fish","fish","latecret","piscivore","dunkleosteus",
  "A fierce 5-metre bony fish; some fossils preserve another large fish swallowed whole inside it."),
 ("leedsichthys","Leedsichthys","Leedsichthys problematicus","giant filter-feeding fish","fish","jurassic","filter","dunkleosteus",
  "Possibly the largest bony fish ever, this gentle giant filtered tiny plankton from Jurassic seas like a whale shark."),
 ("megalodon","Megalodon","Otodus megalodon","giant prehistoric shark","shark","miocene","carnivore","shark",
  "The largest shark that ever lived, perhaps 15 to 18 metres long, with triangular teeth bigger than a human hand."),
 ("cladoselache","Cladoselache","Cladoselache fyleri","prehistoric shark","shark","devonian","piscivore","shark",
  "One of the best-known early sharks, a fast Devonian swimmer with a streamlined body and forked tail."),
 ("stethacanthus","Stethacanthus","Stethacanthus altonensis","prehistoric shark","shark","devonian","piscivore","shark",
  "A small shark whose males had a strange flat-topped, brush-like fin shaped like an anvil on their backs."),
 ("hybodus","Hybodus","Hybodus fraasi","prehistoric shark","shark","jurassic","carnivore","shark",
  "A common shark of the dinosaur age with two kinds of teeth, sharp ones for grabbing and flat ones for crushing."),
 ("coelacanth","Coelacanth","Latimeria chalumnae","lobe-finned fish","fish","cretaceous","piscivore","dunkleosteus",
  "Known first from fossils and thought long extinct, a living coelacanth was caught in 1938, making it a famous 'living fossil'."),
 ("ctenacanthus","Ctenacanthus","Ctenacanthus major","prehistoric shark","shark","carbonif","piscivore","shark",
  "An early shark known largely from its grooved, comb-like fin spines found in Carboniferous rocks."),
 ("drepanaspis","Drepanaspis","Drepanaspis gemuenden","jawless fish","fish","devonian","filter","dunkleosteus",
  "A flat, broad jawless fish that lived on the sea floor, sifting food from the mud."),
]

PLANTS = [
 ("cooksonia","Cooksonia","Cooksonia pertoni","early land plant","plant","silurian","none","fern",
  "Among the earliest known land plants, a tiny leafless stalk that branched into Y-shapes tipped with spore capsules."),
 ("lepidodendron","Lepidodendron","Lepidodendron aculeatum","scale tree","plant","carbonif","none","fern",
  "A giant 'scale tree' up to 30 metres tall whose bark was covered in diamond-shaped leaf scars; its remains helped form coal."),
 ("sigillaria","Sigillaria","Sigillaria scutellata","scale tree","plant","carbonif","none","fern",
  "A tall coal-forest tree with a tufted crown of grass-like leaves and vertical rows of leaf scars on its trunk."),
 ("calamites","Calamites","Calamites suckowii","giant horsetail","plant","carbonif","none","fern",
  "A tree-sized relative of today's small horsetails, growing up to 20 metres tall in the swampy coal forests."),
 ("glossopteris","Glossopteris","Glossopteris indica","seed fern","plant","permian","none","fern",
  "A tongue-leaved seed fern whose fossils on widely separated continents helped prove they were once joined as one landmass."),
 ("archaeopteris","Archaeopteris","Archaeopteris hibernica","early tree","plant","devonian","none","fern",
  "Often called the first modern tree, it had a real woody trunk and fern-like fronds and formed Earth's earliest forests."),
 ("cordaites","Cordaites","Cordaites principalis","early conifer relative","plant","carbonif","none","fern",
  "A tall tree with long, strap-shaped leaves, an early relative of conifers that grew in and around the coal swamps."),
 ("williamsonia","Williamsonia","Williamsonia sewardiana","bennettitalean plant","plant","jurassic","none","fern",
  "A stout, cycad-like plant of the dinosaur age bearing flower-like cones among its crown of leaves."),
 ("prototaxites","Prototaxites","Prototaxites loganii","giant prehistoric organism","plant","devonian","none","mushroom",
  "A mysterious trunk-like organism up to 8 metres tall that towered over a world whose other life was barely knee-high; it may have been a giant fungus."),
 ("wattieza","Wattieza","Wattieza sp.","early tree","plant","devonian","none","fern",
  "One of the oldest known true trees, a fern-like plant that grew about 8 metres tall and helped build the first forests."),
 ("medullosa","Medullosa","Medullosa noei","seed fern","plant","carbonif","none","fern",
  "A seed fern of the coal forests with very large fronds and surprisingly big seeds for its time."),
 ("dicroidium","Dicroidium","Dicroidium odontopteroides","seed fern","plant","triassic","none","fern",
  "A forked-leaved seed fern that dominated the forests of the southern continents in the Triassic."),
 ("ginkgo","Ginkgo","Ginkgo biloba","prehistoric tree","plant","jurassic","none","fern",
  "Ginkgo trees flourished in the dinosaur age and the living species is so little changed it is called a 'living fossil'."),
 ("sphenophyllum","Sphenophyllum","Sphenophyllum emarginatum","prehistoric plant","plant","carbonif","none","fern",
  "A small scrambling plant of the coal swamps with whorls of wedge-shaped leaves around slender stems."),
 ("baragwanathia","Baragwanathia","Baragwanathia longifolia","early clubmoss","plant","silurian","none","fern",
  "A surprisingly advanced early land plant clothed in spirals of needle-like leaves along its stems."),
 ("annularia","Annularia","Annularia stellata","horsetail foliage","plant","carbonif","none","fern",
  "The star-shaped whorls of leaves of the giant horsetail Calamites, among the most beautiful coal-forest fossils."),
 ("pachypteris","Pachypteris","Pachypteris lanceolata","seed fern","plant","jurassic","none","fern",
  "A small seed fern with thick, leathery leaves suited to dry or salty coastal habitats in the dinosaur age."),
 ("rhynia","Rhynia","Rhynia gwynne-vaughanii","early land plant","plant","devonian","none","fern",
  "A simple early land plant of leafless green stems, beautifully preserved in the famous Rhynie chert of Scotland."),
]
