# -*- coding: utf-8 -*-
"""PaleoHype taxa: synapsids (proto-mammals), early amphibians/tetrapods,
early reptiles, and Triassic archosaurs/crocodile-line reptiles.
Tuple format: (key, name, sci, group, classGroup, periodKey, diet, art, trait)
"""

SYNAPSIDS = [
 ("dimetrodon","Dimetrodon","Dimetrodon limbatus","sail-backed synapsid","synapsid","permian","carnivore","dimetrodon",
  "The tall sail on its back, held up by long bony spines, may have helped control its body temperature; it lived long before the dinosaurs and was closer to mammals than to reptiles."),
 ("edaphosaurus","Edaphosaurus","Edaphosaurus pogonias","sail-backed synapsid","synapsid","permian","herbivore","dimetrodon",
  "A plant-eating relative of Dimetrodon whose sail was studded with little crossbars along its spines."),
 ("lystrosaurus","Lystrosaurus","Lystrosaurus murrayi","dicynodont synapsid","synapsid","triassic","herbivore","dimetrodon",
  "A stout, pig-sized plant-eater with two tusks and a beak that became one of the most common land animals just after Earth's greatest extinction."),
 ("gorgonops","Gorgonops","Gorgonops torvus","gorgonopsian synapsid","synapsid","permian","carnivore","dimetrodon",
  "A sabre-toothed proto-mammal and a top predator of the Permian, long before true cats existed."),
 ("inostrancevia","Inostrancevia","Inostrancevia alexandri","gorgonopsian synapsid","synapsid","permian","carnivore","dimetrodon",
  "The largest known gorgonopsian, with sabre teeth up to 15 centimetres long for hunting big Permian prey."),
 ("cynognathus","Cynognathus","Cynognathus crateronotus","cynodont synapsid","synapsid","triassic","carnivore","dimetrodon",
  "A dog-sized hunter with mammal-like teeth and jaws, very close to the ancestry of true mammals."),
 ("moschops","Moschops","Moschops capensis","dinocephalian synapsid","synapsid","permian","herbivore","dimetrodon",
  "A bulky, barrel-bodied plant-eater with a remarkably thick skull roof, perhaps used in head-butting."),
 ("thrinaxodon","Thrinaxodon","Thrinaxodon liorhinus","cynodont synapsid","synapsid","triassic","carnivore","dimetrodon",
  "A small burrowing proto-mammal with pits in its snout that hint it may have had whiskers and fur."),
 ("estemmenosuchus","Estemmenosuchus","Estemmenosuchus uralensis","dinocephalian synapsid","synapsid","permian","omnivore","dimetrodon",
  "A large Permian beast whose skull bore strange horn-like growths sticking out to the sides and above the eyes."),
 ("cotylorhynchus","Cotylorhynchus","Cotylorhynchus romeri","caseid synapsid","synapsid","permian","herbivore","dimetrodon",
  "A huge, barrel-bodied plant-eater with a comically tiny head perched on a massive body."),
 ("sphenacodon","Sphenacodon","Sphenacodon ferox","synapsid predator","synapsid","permian","carnivore","dimetrodon",
  "A close relative of Dimetrodon but with only a low ridge along its back instead of a tall sail."),
 ("diictodon","Diictodon","Diictodon feliceps","dicynodont synapsid","synapsid","permian","herbivore","dimetrodon",
  "A small, tusked burrower known from spiral burrows it dug to escape the harsh Permian climate."),
 ("titanophoneus","Titanophoneus","Titanophoneus potens","dinocephalian synapsid","synapsid","permian","carnivore","dimetrodon",
  "A large carnivorous proto-mammal with a long skull and sharp teeth, its name meaning 'titanic murderer'."),
 ("anteosaurus","Anteosaurus","Anteosaurus magnificus","dinocephalian synapsid","synapsid","permian","carnivore","dimetrodon",
  "One of the largest Permian predators, a bulky synapsid with a thick, bony skull and powerful jaws."),
 ("scymnognathus","Scymnognathus","Scymnognathus whaitsi","gorgonopsian synapsid","synapsid","permian","carnivore","dimetrodon",
  "A sabre-toothed gorgonopsian hunter from the Permian rocks of southern Africa."),
 ("robertia","Robertia","Robertia broomiana","dicynodont synapsid","synapsid","permian","herbivore","dimetrodon",
  "A small, tusked, beaked plant-eater, one of the most abundant little synapsids of the Permian."),
 ("oligokyphus","Oligokyphus","Oligokyphus major","tritylodont synapsid","synapsid","jurassic","herbivore","dimetrodon",
  "A small, weasel-like plant-eater so mammal-like that it survived alongside the early dinosaurs."),
 ("procynosuchus","Procynosuchus","Procynosuchus delaharpeae","cynodont synapsid","synapsid","permian","carnivore","dimetrodon",
  "An early cynodont with a flexible body that may have been a capable swimmer."),
 ("ophiacodon","Ophiacodon","Ophiacodon uniformis","early synapsid","synapsid","permian","piscivore","dimetrodon",
  "A long-skulled early synapsid that probably hunted fish and amphibians near the water's edge."),
]

AMPHIBIANS = [
 ("ichthyostega","Ichthyostega","Ichthyostega stensioei","early tetrapod","amphibian","devonian","carnivore","amphibian",
  "One of the first animals with four limbs to leave the water, it had sturdy legs but still a fish-like tail and gills."),
 ("acanthostega","Acanthostega","Acanthostega gunnari","early tetrapod","amphibian","devonian","carnivore","amphibian",
  "An early four-legged animal whose limbs each had eight fingers; it likely still lived mostly in water."),
 ("diplocaulus","Diplocaulus","Diplocaulus magnicornis","prehistoric amphibian","amphibian","permian","carnivore","amphibian",
  "Its wide, boomerang-shaped head may have worked like a hydrofoil to help it glide through the water."),
 ("eryops","Eryops","Eryops megacephalus","prehistoric amphibian","amphibian","permian","carnivore","amphibian",
  "A heavy, crocodile-like amphibian over 1.5 metres long that hunted near Permian swamps and rivers."),
 ("seymouria","Seymouria","Seymouria baylorensis","early tetrapod","amphibian","permian","carnivore","amphibian",
  "A sturdy land animal showing a mix of amphibian and reptile features, blurring the line between the two groups."),
 ("mastodonsaurus","Mastodonsaurus","Mastodonsaurus giganteus","giant amphibian","amphibian","triassic","piscivore","amphibian",
  "A giant Triassic amphibian with a metre-long flat skull and tusks that poked through holes in its snout."),
 ("prionosuchus","Prionosuchus","Prionosuchus plummeri","giant amphibian","amphibian","permian","piscivore","amphibian",
  "A crocodile-shaped amphibian that may have reached several metres long, one of the largest amphibians ever."),
 ("gerrothorax","Gerrothorax","Gerrothorax pulcherrimus","prehistoric amphibian","amphibian","triassic","piscivore","amphibian",
  "A flat, bottom-dwelling amphibian that kept its feathery gills for life and ambushed prey by snapping its head upward."),
 ("cacops","Cacops","Cacops aspidephorus","prehistoric amphibian","amphibian","permian","insectivore","amphibian",
  "A small land amphibian protected by a row of bony armour plates running down its back."),
 ("metoposaurus","Metoposaurus","Metoposaurus diagnosticus","prehistoric amphibian","amphibian","triassic","piscivore","amphibian",
  "A large, flat-headed amphibian that lived in herds in Triassic lakes, with eyes set near the front of its skull."),
 ("crassigyrinus","Crassigyrinus","Crassigyrinus scoticus","early tetrapod","amphibian","carbonif","piscivore","amphibian",
  "An eel-like aquatic predator with tiny, almost useless legs and a big toothy mouth."),
 ("platyhystrix","Platyhystrix","Platyhystrix rugosus","prehistoric amphibian","amphibian","permian","insectivore","amphibian",
  "A small land amphibian that, like Dimetrodon, carried a tall sail of skin along its back."),
 ("koolasuchus","Koolasuchus","Koolasuchus cleelandi","giant amphibian","amphibian","earlycret","piscivore","amphibian",
  "A late-surviving giant amphibian that lived in cool southern rivers tens of millions of years after most of its kind died out."),
 ("eucritta","Eucritta","Eucritta melanolimnetes","early tetrapod","amphibian","carbonif","carnivore","amphibian",
  "A small early tetrapod whose name means 'creature from the black lagoon', mixing features of several groups."),
]

ARCHOSAURS = [
 ("postosuchus","Postosuchus","Postosuchus kirkpatricki","rauisuchian archosaur","archosaur","triassic","carnivore","croc",
  "A large crocodile-line predator that walked on upright legs and was a top hunter before the dinosaurs took over."),
 ("saurosuchus","Saurosuchus","Saurosuchus galilei","rauisuchian archosaur","archosaur","triassic","carnivore","croc",
  "A giant Triassic predator up to 7 metres long, one of the largest land hunters of its day."),
 ("desmatosuchus","Desmatosuchus","Desmatosuchus spurensis","aetosaur archosaur","archosaur","triassic","herbivore","croc",
  "An armoured, plant-eating crocodile relative covered in bony plates and long shoulder spikes."),
 ("rutiodon","Rutiodon","Rutiodon carolinensis","phytosaur","archosaur","triassic","piscivore","croc",
  "A crocodile-like phytosaur whose nostrils sat far back near its eyes rather than at the tip of its snout."),
 ("euparkeria","Euparkeria","Euparkeria capensis","early archosaur","archosaur","triassic","carnivore","croc",
  "A small, agile reptile close to the ancestry of both dinosaurs and crocodiles, able to run on its hind legs."),
 ("proterosuchus","Proterosuchus","Proterosuchus fergusi","early archosaur","archosaur","triassic","carnivore","croc",
  "A sprawling, crocodile-shaped survivor of the great Permian extinction with a distinctive hooked upper jaw."),
 ("sarcosuchus","Sarcosuchus","Sarcosuchus imperator","giant crocodile relative","archosaur","earlycret","carnivore","croc",
  "Nicknamed 'SuperCroc', this giant relative of crocodiles grew to about 12 metres and could have ambushed dinosaurs."),
 ("deinosuchus","Deinosuchus","Deinosuchus riograndensis","giant crocodilian","archosaur","latecret","carnivore","croc",
  "A huge alligator relative whose powerful jaws could tackle dinosaurs; bite marks on dinosaur bones reveal its attacks."),
 ("prestosuchus","Prestosuchus","Prestosuchus chiniquensis","rauisuchian archosaur","archosaur","triassic","carnivore","croc",
  "A large, deep-skulled crocodile-line predator that walked with its legs held upright beneath its body."),
 ("ornithosuchus","Ornithosuchus","Ornithosuchus longidens","early archosaur","archosaur","triassic","carnivore","croc",
  "A predatory crocodile-line reptile once mistaken for a dinosaur because it could rear up on two legs."),
 ("typothorax","Typothorax","Typothorax coccinarum","aetosaur archosaur","archosaur","triassic","herbivore","croc",
  "A wide, heavily armoured plant-eating crocodile relative shaped a little like a Triassic armadillo."),
 ("parasuchus","Parasuchus","Parasuchus hislopi","phytosaur","archosaur","triassic","piscivore","croc",
  "A slender, fish-eating phytosaur with long crocodile-like jaws lined with sharp teeth."),
 ("smok","Smok","Smok wawelski","large archosaur","archosaur","triassic","carnivore","croc",
  "A large Late Triassic predator from Poland, named after a legendary dragon, that fed on other reptiles."),
]
