# -*- coding: utf-8 -*-
"""PaleoHype taxa database. Tuple format:
(key, name, sci, group, classGroup, periodKey, diet, art, trait)
Facts are kept to well-established paleontology.
"""

# classGroup -> track / family resolved in expander
THEROPODS = [
 ("tyrannosaurus","Tyrannosaurus rex","Tyrannosaurus rex","giant theropod dinosaur","theropod","latecret","carnivore","theropod",
  "About 12 metres long with banana-sized teeth, it had one of the most powerful bites of any land animal ever known."),
 ("giganotosaurus","Giganotosaurus","Giganotosaurus carolinii","giant theropod dinosaur","theropod","latecret","carnivore","theropod",
  "One of the largest meat-eating dinosaurs, it was slightly longer than T. rex but had a slimmer, blade-like skull."),
 ("spinosaurus","Spinosaurus","Spinosaurus aegyptiacus","giant theropod dinosaur","theropod","latecret","piscivore","theropod",
  "It wore a tall sail of skin on its back and had a long crocodile-like snout for catching fish, and may have been the largest meat-eating dinosaur of all."),
 ("allosaurus","Allosaurus","Allosaurus fragilis","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "The top predator of Jurassic North America, it had short brow horns above its eyes and a wide gape for slashing at prey."),
 ("carcharodontosaurus","Carcharodontosaurus","Carcharodontosaurus saharicus","giant theropod dinosaur","theropod","latecret","carnivore","theropod",
  "Its name means 'shark-toothed lizard' for its blade-like serrated teeth, and it rivalled T. rex in size."),
 ("carnotaurus","Carnotaurus","Carnotaurus sastrei","large theropod dinosaur","theropod","latecret","carnivore","theropod",
  "It had a pair of bull-like horns above its eyes and tiny, almost useless arms even shorter than those of T. rex."),
 ("ceratosaurus","Ceratosaurus","Ceratosaurus nasicornis","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "It carried a distinctive blade-like horn on its snout and a row of bony armour down its back."),
 ("tarbosaurus","Tarbosaurus","Tarbosaurus bataar","giant theropod dinosaur","theropod","latecret","carnivore","theropod",
  "A close Asian cousin of T. rex, it was the largest predator of Late Cretaceous Mongolia."),
 ("albertosaurus","Albertosaurus","Albertosaurus sarcophagus","large theropod dinosaur","theropod","latecret","carnivore","theropod",
  "A lighter, faster relative of T. rex, fossils suggest it may have hunted in groups."),
 ("gorgosaurus","Gorgosaurus","Gorgosaurus libratus","large theropod dinosaur","theropod","latecret","carnivore","theropod",
  "A swift tyrannosaur of western North America, often found alongside its prey of horned and duck-billed dinosaurs."),
 ("daspletosaurus","Daspletosaurus","Daspletosaurus torosus","large theropod dinosaur","theropod","latecret","carnivore","theropod",
  "A heavily built tyrannosaur whose name means 'frightful lizard'."),
 ("acrocanthosaurus","Acrocanthosaurus","Acrocanthosaurus atokensis","giant theropod dinosaur","theropod","earlycret","carnivore","theropod",
  "Tall ridges along its backbone may have supported a low ridge of muscle or a small sail."),
 ("baryonyx","Baryonyx","Baryonyx walkeri","large theropod dinosaur","theropod","earlycret","piscivore","theropod",
  "It had a long, narrow, crocodile-like snout and a huge curved claw on each thumb for hooking fish."),
 ("suchomimus","Suchomimus","Suchomimus tenerensis","large theropod dinosaur","theropod","earlycret","piscivore","theropod",
  "A fish-eating relative of Spinosaurus with a low sail and a snout full of cone-shaped teeth."),
 ("megalosaurus","Megalosaurus","Megalosaurus bucklandii","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "In 1824 it became the very first dinosaur ever to be scientifically named."),
 ("torvosaurus","Torvosaurus","Torvosaurus tanneri","giant theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "One of the largest land predators of the Jurassic, with powerful arms and long teeth."),
 ("dilophosaurus","Dilophosaurus","Dilophosaurus wetherilli","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "It wore a pair of thin, rounded crests on its head; the real animal was far larger than the small frilled hunter shown in films."),
 ("cryolophosaurus","Cryolophosaurus","Cryolophosaurus ellioti","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "Found in Antarctica, it had a strange crest that rose sideways across its head like a curled comb."),
 ("majungasaurus","Majungasaurus","Majungasaurus crenatissimus","large theropod dinosaur","theropod","latecret","carnivore","theropod",
  "From Madagascar, fossil bite marks show it sometimes ate others of its own kind."),
 ("yangchuanosaurus","Yangchuanosaurus","Yangchuanosaurus shangyouensis","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "A large Allosaurus-like predator from Jurassic China."),
 ("metriacanthosaurus","Metriacanthosaurus","Metriacanthosaurus parkeri","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "Its name means 'moderately spined lizard' for the tall spines along its back."),
 ("mapusaurus","Mapusaurus","Mapusaurus roseae","giant theropod dinosaur","theropod","latecret","carnivore","theropod",
  "Found in a bone bed of many individuals, hinting it may have hunted the giant Argentinosaurus in packs."),
 ("siats","Siats","Siats meekerorum","giant theropod dinosaur","theropod","latecret","carnivore","theropod",
  "A huge predator of North America that lived before tyrannosaurs grew to giant size there."),
 ("coelophysis","Coelophysis","Coelophysis bauri","small theropod dinosaur","theropod","triassic","carnivore","theropod",
  "One of the earliest dinosaurs, this slender hunter is known from hundreds of skeletons found together in New Mexico."),
 ("compsognathus","Compsognathus","Compsognathus longipes","small theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "About the size of a turkey, it was long thought to be one of the smallest dinosaurs, chasing lizards and insects."),
 ("ornithomimus","Ornithomimus","Ornithomimus velox","ostrich-like theropod dinosaur","theropod","latecret","omnivore","theropod",
  "Built like an ostrich, this toothless, long-legged dinosaur was one of the fastest, and was covered in feathers."),
 ("gallimimus","Gallimimus","Gallimimus bullatus","ostrich-like theropod dinosaur","theropod","latecret","omnivore","theropod",
  "The largest of the ostrich-mimic dinosaurs, it could likely sprint at high speed on its long legs."),
 ("struthiomimus","Struthiomimus","Struthiomimus altus","ostrich-like theropod dinosaur","theropod","latecret","omnivore","theropod",
  "Its name means 'ostrich mimic', and it had a toothless beak and long grasping arms."),
 ("therizinosaurus","Therizinosaurus","Therizinosaurus cheloniformis","theropod dinosaur","theropod","latecret","herbivore","theropod",
  "This odd plant-eating theropod had the longest claws of any known animal, nearly a metre long, likely used to pull down branches."),
 ("deinocheirus","Deinocheirus","Deinocheirus mirificus","theropod dinosaur","theropod","latecret","omnivore","theropod",
  "Known for decades only from giant arms, it turned out to be a humpbacked, duck-billed oddity over 11 metres long."),
 ("oviraptor","Oviraptor","Oviraptor philoceratops","small theropod dinosaur","theropod","latecret","omnivore","theropod",
  "Its name means 'egg thief', but the eggs it was found with were actually its own, which it was guarding in a nest."),
 ("citipati","Citipati","Citipati osmolska","small theropod dinosaur","theropod","latecret","omnivore","theropod",
  "Famous fossils show it sitting on its nest exactly like a brooding bird, arms spread over the eggs."),
 ("anzu","Anzu","Anzu wyliei","feathered theropod dinosaur","theropod","latecret","omnivore","theropod",
  "Nicknamed the 'chicken from hell', it was a tall, feathered, crested dinosaur with a toothless beak."),
 ("troodon","Troodon","Troodon formosus","small theropod dinosaur","theropod","latecret","omnivore","theropod",
  "With large eyes and a big brain for its size, it was among the smartest dinosaurs and could likely see well in dim light."),
 ("velociraptor","Velociraptor","Velociraptor mongoliensis","raptor dinosaur","theropod","latecret","carnivore","raptor",
  "The real animal was only about the size of a turkey, covered in feathers, with a deadly sickle-shaped claw on each foot."),
 ("deinonychus","Deinonychus","Deinonychus antirrhopus","raptor dinosaur","theropod","earlycret","carnivore","raptor",
  "Its 'terrible claw' and active build helped change how scientists pictured dinosaurs as fast, bird-like animals."),
 ("utahraptor","Utahraptor","Utahraptor ostrommaysi","raptor dinosaur","theropod","earlycret","carnivore","raptor",
  "The largest known raptor, the size of a bear, with foot claws longer than a human hand."),
 ("microraptor","Microraptor","Microraptor gui","raptor dinosaur","theropod","earlycret","carnivore","raptor",
  "A tiny raptor with feathers on all four limbs, giving it four wings to glide between trees; fossils even reveal its glossy black colour."),
 ("dromaeosaurus","Dromaeosaurus","Dromaeosaurus albertensis","raptor dinosaur","theropod","latecret","carnivore","raptor",
  "The raptor that gave its family its name, with a stronger, more powerful bite than most of its relatives."),
 ("sinosauropteryx","Sinosauropteryx","Sinosauropteryx prima","small theropod dinosaur","theropod","earlycret","carnivore","raptor",
  "The first dinosaur found with clear evidence of feathers, and the first whose colour, a ginger-and-white striped tail, was worked out."),
 ("sinornithosaurus","Sinornithosaurus","Sinornithosaurus millenii","raptor dinosaur","theropod","earlycret","carnivore","raptor",
  "An early feathered raptor from China whose fossils preserve a fuzzy coat of downy filaments."),
 ("bambiraptor","Bambiraptor","Bambiraptor feinbergi","raptor dinosaur","theropod","latecret","carnivore","raptor",
  "A small, bird-like raptor with a large brain, known from a remarkably complete young skeleton."),
 ("austroraptor","Austroraptor","Austroraptor cabazai","raptor dinosaur","theropod","latecret","carnivore","raptor",
  "A large raptor from Argentina with short arms and a long, slim snout for catching fish."),
 ("buitreraptor","Buitreraptor","Buitreraptor gonzalezorum","raptor dinosaur","theropod","latecret","carnivore","raptor",
  "A slender South American raptor with a long, narrow snout full of small teeth."),
 ("pyroraptor","Pyroraptor","Pyroraptor olympius","raptor dinosaur","theropod","latecret","carnivore","raptor",
  "Its name means 'fire thief' because its bones were found after a forest fire in France."),
 ("eoraptor","Eoraptor","Eoraptor lunensis","early dinosaur","earlydino","triassic","omnivore","theropod",
  "One of the earliest known dinosaurs, a small, light runner from the dawn of the dinosaur age."),
 ("herrerasaurus","Herrerasaurus","Herrerasaurus ischigualastensis","early predatory dinosaur","earlydino","triassic","carnivore","theropod",
  "An early meat-eating dinosaur from Argentina that hunted at the very start of the dinosaurs' rise."),
 ("staurikosaurus","Staurikosaurus","Staurikosaurus pricei","early predatory dinosaur","earlydino","triassic","carnivore","theropod",
  "A slim, fast early dinosaur from Brazil, one of the oldest known."),
 ("masiakasaurus","Masiakasaurus","Masiakasaurus knopfleri","small theropod dinosaur","theropod","latecret","piscivore","theropod",
  "Its front teeth jutted straight forward like a comb, perfect for grabbing fish and small prey."),
 ("guanlong","Guanlong","Guanlong wucaii","early tyrannosaur dinosaur","theropod","jurassic","carnivore","theropod",
  "An early ancestor of T. rex, small and crested, showing tyrannosaurs began as modest hunters."),
 ("monolophosaurus","Monolophosaurus","Monolophosaurus jiangi","large theropod dinosaur","theropod","jurassic","carnivore","theropod",
  "It carried a single tall crest running along the top of its skull."),
 ("concavenator","Concavenator","Concavenator corcovatus","large theropod dinosaur","theropod","earlycret","carnivore","theropod",
  "It had a strange pointed hump on its back and bumps on its arm that may have anchored feathers."),
 ("qianzhousaurus","Qianzhousaurus","Qianzhousaurus sinensis","large theropod dinosaur","theropod","latecret","carnivore","theropod",
  "Nicknamed 'Pinocchio rex' for its unusually long, slim snout."),
 ("austrocheirus","Megaraptor","Megaraptor namunhuaiquii","large theropod dinosaur","theropod","latecret","carnivore","theropod",
  "Named for a huge sickle claw first thought to be from its foot, which actually came from its hand."),
]
