R = [
("seahype-lessons.js",
 "Seawater is water plus dissolved salts. Average salinity is about 35 grams of salt per kilogram of water — written 35 parts per thousand (ppt or ‰), or about 3.5% by weight. The two most abundant ions are sodium and chloride (ordinary table salt), followed by sulfate, magnesium, calcium and potassium.",
 "Seawater is water plus dissolved salts. On average, it holds about 35 grams of salt per kilogram of water. That is written as 35 parts per thousand, or about 3.5% by weight. The two most common ions are sodium and chloride, which together make ordinary table salt. After those come sulfate, magnesium, calcium, and potassium."),
("seahype-lessons.js",
 "The ocean is salty because rivers and rain slowly weather rock on land and carry dissolved minerals to the sea, while undersea vents and hydrothermal activity add more. Water leaves by evaporation but the salts stay behind and accumulate over geologic time, so the sea stays salty even though the rivers feeding it are fresh.",
 "The ocean is salty because of a slow process. Rivers and rain slowly wear down rock on land and carry dissolved minerals to the sea. Undersea vents add more. Water leaves the ocean by evaporation, but the salts stay behind and build up over a very long time. So the sea stays salty even though the rivers feeding it are fresh."),
("seahype-lessons.js",
 "Salinity is not uniform. It rises where evaporation is high (warm, dry subtropics) and falls where rivers, rain or melting ice add fresh water (the poles, estuaries). These differences in salt — together with temperature — change the density of seawater and help drive ocean currents.",
 "Saltiness is not the same everywhere. It rises where lots of water evaporates, like the warm, dry subtropics. It falls where rivers, rain, or melting ice add fresh water, like the poles and estuaries. These differences in salt, along with temperature, change how dense seawater is. That helps drive ocean currents."),
("seahype-lessons-extra4.js",
 "When a great whale dies and sinks to the deep seafloor, its enormous body becomes a sudden feast in a place where food is normally scarce. Scientists call this a whale fall, and a single carcass can support a thriving community for years or even decades — a rare burst of life on the cold, dark, food-poor abyssal plain.",
 "When a great whale dies, it sinks to the deep seafloor. Down there, food is usually scarce, so its huge body becomes a sudden feast. Scientists call this a whale fall. A single body can feed a busy community for years or even decades. It is a rare burst of life on the cold, dark, food-poor abyssal plain."),
("seahype-lessons-extra4.js",
 "A whale fall passes through stages. First, mobile scavengers — hagfish, sleeper sharks, and swarms of amphipods — strip the soft tissue within months to a couple of years. Next, 'enrichment opportunists' such as worms and snails colonize the bones and the organically enriched sediment around them. Finally, in the long sulfophilic stage, bacteria break down the fats locked inside the bones, producing hydrogen sulfide and supporting chemosynthetic life much like a hydrothermal vent.",
 "A whale fall goes through stages. First, mobile scavengers strip the soft flesh within months to a couple of years. These include hagfish, sleeper sharks, and swarms of amphipods. Next, worms and snails move in to feed on the bones and the rich sediment around them. Finally, in a long last stage, bacteria break down the fats locked inside the bones. This makes hydrogen sulfide and supports chemosynthetic life, much like a hydrothermal vent."),
("seahype-lessons-extra4.js",
 "Whale falls even have specialists found almost nowhere else, like the bone-eating Osedax worms — sometimes called zombie worms — that bore into bone to reach the lipids inside. Because they host chemosynthetic communities, whale falls may act as stepping stones, helping deep-sea species disperse between distant vents and seeps across the ocean floor.",
 "Whale falls even have specialists found almost nowhere else. One is the bone-eating Osedax worm, sometimes called the zombie worm. It bores into bone to reach the fats inside. Because they host chemosynthetic communities, whale falls may act as stepping stones. They could help deep-sea species spread between distant vents and seeps across the ocean floor."),
("seahype-lessons.js",
 "Biodiversity is the variety of life — the number of species, their genetic variation, and the range of ecosystems they form. The ocean is the cradle of biodiversity: most major animal groups (phyla) appear there, and several live nowhere else. Scientists have formally described more than 250,000 living marine species, and add roughly two thousand new ones each year.",
 "Biodiversity is the variety of life. It includes the number of species, their genetic differences, and the range of ecosystems they form. The ocean is the cradle of biodiversity. Most major animal groups, called phyla, appear there, and several live nowhere else. Scientists have formally named more than 250,000 living marine species, and they add about two thousand new ones each year."),
("seahype-lessons.js",
 "Yet that is only a slice of what exists. Estimates suggest the true number of ocean species may run into the millions, with most still undiscovered — especially among microbes and in the deep sea. The authoritative running census of named marine species is the World Register of Marine Species (WoRMS).",
 "Yet that is only a slice of what exists. Scientists think the true number of ocean species may be in the millions, with most still undiscovered. This is especially true for microbes and life in the deep sea. The main running count of named marine species is the World Register of Marine Species, or WoRMS."),
("seahype-lessons.js",
 "Biodiversity is not spread evenly. It generally peaks in the warm tropics and falls toward the poles, and it concentrates in structurally complex habitats like coral reefs. The 'Coral Triangle' of Southeast Asia is the single richest marine region on Earth. Where physical conditions and history allow more niches, more species can coexist.",
 "Biodiversity is not spread evenly. It is usually highest in the warm tropics and drops off toward the poles. It is also packed into complex habitats like coral reefs. The 'Coral Triangle' of Southeast Asia is the single richest marine region on Earth. Where the conditions and history allow more niches, more species can live together."),
("seahype-lessons-extra2.js",
 "Many marine animals reproduce by broadcast spawning: they release eggs and sperm into the water, where fertilization happens externally. To make this work in a vast ocean, spawners synchronize — often cued by the moon, tides, season or temperature — so that everyone releases at once, as in the famous mass coral spawning events. Others fertilize internally and may lay eggs or give live birth.",
 "Many sea animals reproduce by broadcast spawning. They release eggs and sperm into the water, and fertilization happens outside the body. For this to work in a huge ocean, spawners time it together. They are often cued by the moon, tides, season, or temperature, so everyone releases at once. The famous mass coral spawning events work this way. Other animals fertilize inside the body and may lay eggs or give live birth."),
("seahype-lessons-extra2.js",
 "A great many marine animals begin life as tiny drifting larvae that look nothing like the adult. These larvae float in the plankton, feeding and developing, sometimes for weeks, before settling and transforming (metamorphosing) into the adult form. This larval stage is how slow or attached animals such as corals, barnacles and many fish disperse to new places.",
 "Many sea animals begin life as tiny drifting larvae that look nothing like the adult. These larvae float in the plankton, feeding and growing, sometimes for weeks. Then they settle and transform into the adult form, a change called metamorphosis. This larval stage is how slow or attached animals like corals, barnacles, and many fish spread to new places."),
("seahype-lessons-extra2.js",
 "Different species gamble differently on offspring. Some follow a 'many cheap young' strategy — releasing millions of eggs and investing nothing further, trusting that a few survive. Others have few young but care for them heavily, improving each one's odds. Both strategies, and everything between, persist because each suits a particular way of life.",
 "Different species bet on their young in different ways. Some use a 'many cheap young' plan. They release millions of eggs and do nothing more, trusting that a few will survive. Others have few young but care for them a lot, raising each one's chances. Both plans, and everything in between, last because each fits a certain way of life."),
("seahype-lessons-extra4.js",
 "Sea turtles live long lives that span entire ocean basins. Females often return to nest on or near the very beach where they hatched — a feat called natal homing — sometimes after decades and thousands of kilometers away. The sex of their hatchlings is set not by genes but by temperature: warmer sand tends to produce more females, cooler sand more males, which makes turtles sensitive to a warming climate.",
 "Sea turtles live long lives that cross entire ocean basins. Females often return to nest on or near the very beach where they hatched. This is called natal homing. It can happen decades later and thousands of kilometers away. The sex of their hatchlings is not set by genes but by temperature. Warmer sand tends to make more females, and cooler sand more males. This makes turtles sensitive to a warming climate."),
("seahype-lessons-extra4.js",
 "Newly hatched turtles scramble to the sea and disappear into the open ocean for years — the so-called lost years — before returning to coastal feeding grounds as juveniles. To find their way across featureless seas, turtles use Earth's magnetic field. They can sense both its strength and the angle at which it dips, reading the field like a map and compass to locate regions and even specific coastlines.",
 "Newly hatched turtles rush to the sea and vanish into the open ocean for years. These are called the 'lost years.' They return to coastal feeding grounds later as juveniles. To find their way across featureless seas, turtles use Earth's magnetic field. They can sense both its strength and the angle at which it dips. They read the field like a map and compass to find regions and even specific coastlines."),
("seahype-lessons-extra4.js",
 "These journeys face many hazards. Hatchlings can be fatally disoriented by artificial lights that draw them away from the sea; adults are caught accidentally in fishing gear; and turtles mistake floating plastic for food. Understanding how turtles navigate and reproduce helps guide protections, from shielded beach lighting to gear that lets turtles escape nets.",
 "These journeys face many dangers. Hatchlings can be fatally confused by artificial lights that draw them away from the sea. Adults get caught by accident in fishing gear. And turtles mistake floating plastic for food. Understanding how turtles navigate and breed helps guide protections, from shielded beach lighting to gear that lets turtles escape nets."),
("seahype-lessons-extra.js",
 "Fishes are aquatic vertebrates that breathe with gills and (usually) have fins. They are the most diverse vertebrates by far, with more than 30,000 species. There are three living groups: jawless fishes (hagfishes and lampreys), cartilaginous fishes (sharks, rays and chimaeras), and bony fishes — by far the largest group, containing almost all familiar fish.",
 "Fishes are water-living vertebrates that breathe with gills and usually have fins. They are by far the most varied vertebrates, with more than 30,000 species. There are three living groups: jawless fishes (hagfishes and lampreys), cartilaginous fishes (sharks, rays, and chimaeras), and bony fishes. The bony fishes are by far the largest group and include almost all familiar fish."),
("seahype-lessons-extra.js",
 "A fish breathes by pumping water over its gills, where blood absorbs dissolved oxygen and releases carbon dioxide. Most bony fishes also have a gas-filled swim bladder that they adjust to stay buoyant at a given depth without constant effort, an innovation sharks lack.",
 "A fish breathes by pumping water over its gills. There, its blood takes in dissolved oxygen and releases carbon dioxide. Most bony fishes also have a gas-filled swim bladder. They adjust it to float at a chosen depth without constant effort. Sharks do not have this organ."),
("seahype-lessons-extra.js",
 "Fishes sense their world in ways land animals cannot. The lateral line, a row of sensors along the body, detects water movement and pressure changes, letting fish school tightly and feel approaching predators or prey in the dark. Fins provide thrust and steering, and body shape reflects lifestyle — torpedo-shaped open-ocean sprinters versus flattened bottom-dwellers.",
 "Fishes sense their world in ways land animals cannot. The lateral line is a row of sensors along the body. It detects water movement and pressure changes. This lets fish school tightly and feel predators or prey in the dark. Fins give thrust and steering. A fish's body shape fits its lifestyle, from torpedo-shaped open-ocean sprinters to flattened bottom-dwellers."),
]
from collections import defaultdict
edits = defaultdict(list)
for f, old, new in R: edits[f].append((old, new))
ok = 0; fail = 0
for f, lst in edits.items():
    s = open(f, encoding="utf-8").read()
    for old, new in lst:
        c = s.count(old)
        if c == 1: s = s.replace(old, new); ok += 1
        else: fail += 1; print("  !! match=%d in %s :: %s" % (c, f, old[:50]))
    open(f, "w", encoding="utf-8").write(s)
print("applied OK:", ok, "| failed:", fail)
