R = [
("seahype-lessons.js",
 "Marine biology is the study of living things in the ocean. That means everything from tiny bacteria too small to see, all the way up to the blue whale — the biggest animal that has ever lived. The ocean covers most of our planet and shapes our weather, our air, and our food, so marine biologists get to explore a little bit of everything.",
 "Marine biology is the study of living things in the ocean. That covers everything from bacteria too tiny to see all the way up to the blue whale, the biggest animal that has ever lived. The ocean covers most of our planet. It shapes our weather, our air, and our food. So marine biologists get to explore a little bit of everything."),
("seahype-lessons.js",
 "SeaHype teaches it the way you'd really learn it: in short lessons grouped into a roadmap, each one followed by a quick quiz so the ideas stick. You'll start with how the ocean itself works, then move on to ocean food webs, the major groups of sea life, ocean habitats, how animals survive down there, protecting the ocean, and how scientists actually study it.",
 "SeaHype teaches it the way you would really learn it: in short lessons grouped into a roadmap, each one followed by a quick quiz so the ideas stick. You will start with how the ocean itself works. Then you will move on to ocean food webs, the major groups of sea life, ocean habitats, how animals survive down there, how to protect the ocean, and how scientists actually study it."),
("seahype-lessons.js",
 "Think of SeaHype as your study buddy — a place to learn and explore, not a replacement for school or real diving training. When a lesson states a fact, it links to a trusted website where you can read more. Tap any source link when you want to dig deeper.",
 "Think of SeaHype as your study buddy. It is a place to learn and explore, not a replacement for school or real diving training. When a lesson states a fact, it links to a trusted website where you can read more. Tap any source link when you want to dig deeper."),
("seahype-lessons.js",
 "When you see how the pieces fit together — the water, the chemistry, the animals, the whole system — you start thinking like a real marine biologist, not just memorizing facts.",
 "When you see how the pieces fit together, the water, the chemistry, the animals, the whole system, you start to think like a real marine biologist instead of just memorizing facts."),
("seahype-lessons-extra.js",
 "True flowering plants are rare in the sea, but the few that succeed are mighty. Seagrasses are the only flowering plants that live fully submerged in seawater; they grow from roots in the seabed and form vast underwater meadows in shallow, sunlit water. Despite the name, they are not seaweeds — they have roots, stems, flowers and seeds.",
 "True flowering plants are rare in the sea, but the few that make it are mighty. Seagrasses are the only flowering plants that live fully underwater in seawater. They grow from roots in the seabed and form vast underwater meadows in shallow, sunny water. Despite the name, they are not seaweeds. They have roots, stems, flowers, and seeds."),
("seahype-lessons-extra.js",
 "Mangroves are salt-tolerant trees and shrubs that grow along tropical and subtropical coasts, in the zone between land and sea. They cope with salt, low oxygen and shifting tides using specialized roots, and they hold the shoreline together against waves and storms.",
 "Mangroves are salt-tolerant trees and shrubs. They grow along warm coasts, in the zone between land and sea. They handle salt, low oxygen, and shifting tides using special roots. They also hold the shoreline together against waves and storms."),
("seahype-lessons-extra.js",
 "Both habitats are nurseries and carbon stores. Seagrass meadows and mangrove forests shelter young fish, crabs and shrimp, and they bury carbon in their sediments far faster per area than most forests on land — part of what is called 'blue carbon'.",
 "Both habitats are nurseries and carbon stores. Seagrass meadows and mangrove forests shelter young fish, crabs, and shrimp. They also bury carbon in their sediments far faster, for their size, than most forests on land. This is part of what is called 'blue carbon.'"),
("seahype-lessons-extra2.js",
 "Staying at a chosen depth without constant effort is a real challenge, because flesh and bone are denser than water and tend to sink. Many bony fish solve this with a swim bladder — a gas-filled sac whose volume they adjust to hover weightlessly. Sharks lack a swim bladder; instead they rely on a large, oil-rich liver (oil is lighter than water) and lift generated by swimming and their fins.",
 "Staying at a chosen depth without constant effort is hard. Flesh and bone are denser than water, so they tend to sink. Many bony fish solve this with a swim bladder, a gas-filled sac. They adjust how much gas is in it to hover weightlessly. Sharks have no swim bladder. Instead they rely on a large, oil-rich liver, since oil is lighter than water, plus lift from swimming and their fins."),
("seahype-lessons-extra2.js",
 "Gas under pressure causes its own problems. As an animal descends, the increasing pressure compresses any gas in its body; as it rises, that gas expands. A fish hauled up too fast can suffer a ruptured or over-expanded swim bladder. The same physics governs why scuba divers must ascend slowly.",
 "Gas under pressure causes its own problems. As an animal goes down, the rising pressure squeezes any gas in its body. As it rises, that gas expands. A fish pulled up too fast can suffer a burst or over-stretched swim bladder. The same physics is why scuba divers must come up slowly."),
("seahype-lessons-extra2.js",
 "Air-breathing divers such as whales and seals manage gases cleverly to avoid decompression sickness, 'the bends.' Many exhale before diving and have lungs that collapse under pressure, limiting how much gas dissolves into the blood. They also store large amounts of oxygen in their muscles using a protein called myoglobin, letting them stay down far longer than their lung volume alone would allow.",
 "Air-breathing divers like whales and seals handle gases cleverly to avoid 'the bends,' or decompression sickness. Many breathe out before diving, and their lungs collapse under pressure. This limits how much gas dissolves into the blood. They also store lots of oxygen in their muscles using a protein called myoglobin. This lets them stay down far longer than their lungs alone would allow."),
("seahype-lessons.js",
 "The ocean covers about 71% of Earth's surface and holds roughly 97% of the planet's water. We name five basins — Pacific, Atlantic, Indian, Southern and Arctic — but they are one connected body of water, the global ocean, with no real walls between them. The Pacific is the largest and deepest of the basins.",
 "The ocean covers about 71% of Earth's surface and holds about 97% of the planet's water. We name five basins: the Pacific, Atlantic, Indian, Southern, and Arctic. But they are really one connected body of water, the global ocean, with no real walls between them. The Pacific is the largest and deepest basin."),
("seahype-lessons.js",
 "It is also enormous in volume, not just area: the ocean's average depth is about 3,682 meters (12,080 feet), and more than 90% of it lies deeper than 200 meters — the dark, cold, high-pressure realm we call the deep sea. That makes the ocean by far the largest livable space on Earth.",
 "The ocean is huge in volume, not just area. Its average depth is about 3,682 meters (12,080 feet). More than 90% of it lies deeper than 200 meters. That is the dark, cold, high-pressure realm we call the deep sea. It makes the ocean by far the largest livable space on Earth."),
("seahype-lessons.js",
 "Despite its size, most of it is unseen. As of recent surveys only a small fraction of the deep seafloor has been directly observed, and roughly a quarter to a third has been mapped at high resolution. Scientists keep describing about two thousand new marine species every year.",
 "Despite its size, most of the ocean is unseen. So far, only a small part of the deep seafloor has been directly observed. About a quarter to a third has been mapped in fine detail. Scientists keep describing about two thousand new sea species every year."),
("seahype-lessons.js",
 "Water is heavy, and it piles up. Pressure increases by about one atmosphere for every 10 meters (about 33 feet) of depth. At the surface you feel 1 atmosphere; at 1,000 meters you feel about 100; at the bottom of the deepest trench, pressure is more than a thousand times that at sea level.",
 "Water is heavy, and it piles up. Pressure rises by about one atmosphere for every 10 meters (about 33 feet) of depth. At the surface you feel 1 atmosphere. At 1,000 meters you feel about 100. At the bottom of the deepest trench, the pressure is more than a thousand times what it is at sea level."),
("seahype-lessons.js",
 "The deepest known point is the Challenger Deep in the Mariana Trench, about 10,935 meters (around 35,876 feet) down — deeper than Mount Everest is tall. Animals live even there, in total darkness and crushing pressure.",
 "The deepest known point is the Challenger Deep, in the Mariana Trench. It is about 10,935 meters (around 35,876 feet) down, deeper than Mount Everest is tall. Animals live even there, in total darkness and crushing pressure."),
("seahype-lessons.js",
 "Deep-sea animals survive because they are not full of air to be crushed. Their bodies are mostly water and gel, which barely compress, and their cells and enzymes are biochemically tuned to work under high pressure. The same pressure that would implode a hollow vessel passes harmlessly through a soft, water-filled body.",
 "Deep-sea animals survive because they are not full of air to be crushed. Their bodies are mostly water and gel, which barely squeeze. Their cells and enzymes are tuned to work under high pressure. The same pressure that would crush a hollow container passes harmlessly through a soft, water-filled body."),
]
from collections import defaultdict
edits = defaultdict(list)
for f, old, new in R: edits[f].append((old, new))
ok = 0; fail = 0
for f, lst in edits.items():
    s = open(f, encoding="utf-8").read()
    for old, new in lst:
        c = s.count(old)
        if c == 1: s = s.replace(old, new); ok += 1
        else: fail += 1; print("  !! match=%d in %s :: %s" % (c, f, old[:50]))
    open(f, "w", encoding="utf-8").write(s)
print("applied OK:", ok, "| failed:", fail)
