/* SeaHype — common shoreline shells, filterable by region.
   regions tags: Atlantic, Gulf, Pacific, Caribbean, Mediterranean, Indo-Pacific, Worldwide.
   "art" matches a key in window.SEA_ART. Facts are general beachcombing knowledge. */
window.__SEA_SHELLS__ = [
  { name: "Lightning whelk", sci: "Sinistrofulgur perversum", group: "Sea snail (gastropod)", art: "whelk",
    regions: ["Atlantic", "Gulf"], size: "to 16 cm",
    desc: "One of the few shells that coils to the LEFT — hold it with the opening facing you and the spire points up while the aperture is on the left. A prized find on Gulf and southeast U.S. beaches." },
  { name: "Knobbed whelk", sci: "Busycon carica", group: "Sea snail (gastropod)", art: "whelk",
    regions: ["Atlantic"], size: "to 23 cm",
    desc: "Large right-handed whelk with blunt knobs along the shoulder. The state shell of New Jersey and Georgia; egg cases wash up as long, papery 'mermaid necklaces.'" },
  { name: "Channeled whelk", sci: "Busycotypus canaliculatus", group: "Sea snail (gastropod)", art: "whelk",
    regions: ["Atlantic"], size: "to 18 cm",
    desc: "Pear-shaped shell with a deep, squared channel running along the suture between whorls. Smoother than the knobbed whelk." },
  { name: "Florida fighting conch", sci: "Strombus alatus", group: "Sea snail (gastropod)", art: "conch",
    regions: ["Atlantic", "Gulf"], size: "to 11 cm",
    desc: "Heavy orange-brown shell with a flared lip. Despite the name it eats algae — the 'fighting' refers to how the living snail leaps and twists using a claw-like foot." },
  { name: "Queen conch", sci: "Aliger gigas", group: "Sea snail (gastropod)", art: "conch",
    regions: ["Caribbean"], size: "to 30 cm",
    desc: "Iconic large conch with a glossy pink interior. Protected in many areas from overharvest — buy only legal, and never collect a live one." },
  { name: "Shark eye moon snail", sci: "Neverita duplicata", group: "Sea snail (gastropod)", art: "moonsnail",
    regions: ["Atlantic", "Gulf"], size: "to 7 cm",
    desc: "Smooth, round, blue-grey shell with a dark 'eye' at the center of the spiral. The snail drills neat round holes in clams — that perfect hole in a beach shell is often its work." },
  { name: "Atlantic moon snail", sci: "Euspira heros", group: "Sea snail (gastropod)", art: "moonsnail",
    regions: ["Atlantic"], size: "to 11 cm",
    desc: "Larger, paler northern moon snail. Lays eggs in a stiff, collar-shaped 'sand collar' that puzzles many beachcombers." },
  { name: "Lettered olive", sci: "Americoliva sayana", group: "Sea snail (gastropod)", art: "olive",
    regions: ["Atlantic", "Gulf"], size: "to 6 cm",
    desc: "Glossy, cylindrical shell with fine zigzag 'lettering.' State shell of South Carolina; the high polish comes from the snail's mantle wrapping the shell in life." },
  { name: "Auger shell", sci: "Terebra dislocata", group: "Sea snail (gastropod)", art: "auger",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 5 cm",
    desc: "Long, slender, screw-like spire of many tight whorls. Common but easy to overlook among broken shell hash." },
  { name: "Common periwinkle", sci: "Littorina littorea", group: "Sea snail (gastropod)", art: "periwinkle",
    regions: ["Atlantic", "Mediterranean"], size: "to 2.5 cm",
    desc: "Small, sturdy rounded snail of rocky shores and jetties. Grazes algae in the splash zone and can seal itself in to survive low tide." },
  { name: "True tulip", sci: "Fasciolaria tulipa", group: "Sea snail (gastropod)", art: "tulip",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 13 cm",
    desc: "Spindle-shaped shell with smooth whorls and fine spiral lines, often streaked orange and grey. A predator that hunts other snails." },
  { name: "Chestnut turban", sci: "Turbo castanea", group: "Sea snail (gastropod)", art: "turban",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 4 cm",
    desc: "Solid, beaded turban-shaped shell. Its round, stony trapdoor (operculum) — a 'cat's eye' — often washes up separately." },
  { name: "Atlantic bay scallop", sci: "Argopecten irradians", group: "Bivalve (two shells)", art: "scallop",
    regions: ["Atlantic", "Gulf"], size: "to 8 cm",
    desc: "Classic fan shape with radiating ribs and 'ears' at the hinge. Scallops can swim by clapping their shells, and have dozens of tiny blue eyes along the mantle." },
  { name: "Calico scallop", sci: "Argopecten gibbus", group: "Bivalve (two shells)", art: "scallop",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 6 cm",
    desc: "Smaller scallop mottled in red, purple and white 'calico' patches. Extremely common on southeastern beaches." },
  { name: "Atlantic cockle", sci: "Dinocardium robustum", group: "Bivalve (two shells)", art: "cockle",
    regions: ["Atlantic", "Gulf"], size: "to 13 cm",
    desc: "Plump, strongly ribbed heart-shaped shell (the 'giant Atlantic cockle'). Viewed end-on, the paired valves form a heart." },
  { name: "Eastern oyster", sci: "Crassostrea virginica", group: "Bivalve (two shells)", art: "oyster",
    regions: ["Atlantic", "Gulf"], size: "to 20 cm",
    desc: "Rough, irregular grey shell that cements into reefs. Oyster reefs filter water and shelter countless young fish and crabs." },
  { name: "Jingle shell", sci: "Anomia simplex", group: "Bivalve (two shells)", art: "jingle",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 5 cm",
    desc: "Thin, translucent, pearly shell in gold, silver or peach. Strung together they 'jingle' — also called mermaid's toenails." },
  { name: "Blue mussel", sci: "Mytilus edulis", group: "Bivalve (two shells)", art: "mussel",
    regions: ["Atlantic", "Pacific", "Mediterranean"], size: "to 10 cm",
    desc: "Blue-black teardrop shell of cool rocky shores. Anchors with tough 'byssal' threads and clusters in dense beds between the tides." },
  { name: "Atlantic razor clam", sci: "Ensis leei", group: "Bivalve (two shells)", art: "razor",
    regions: ["Atlantic"], size: "to 15 cm",
    desc: "Long, narrow, slightly curved shell like an old straight razor. The living clam is a champion burrower, vanishing into wet sand in seconds." },
  { name: "Atlantic slipper limpet", sci: "Crepidula fornicata", group: "Sea snail (gastropod)", art: "limpet",
    regions: ["Atlantic", "Pacific"], size: "to 5 cm",
    desc: "Arched, cap-like shell with a little inner shelf — flip it over and it looks like a slipper or a tiny boat. Often stacks in chains, one atop another." },
  { name: "Keyhole limpet", sci: "Diodora aspera", group: "Sea snail (gastropod)", art: "limpet",
    regions: ["Pacific"], size: "to 5 cm",
    desc: "Cone-shaped shell with a small hole at the very top that vents water and waste. Clamps tight to Pacific rocks against the surf." },
  { name: "Atlantic yellow cowrie", sci: "Naria spurca", group: "Sea snail (gastropod)", art: "cowrie",
    regions: ["Atlantic", "Caribbean", "Mediterranean"], size: "to 3 cm",
    desc: "Glossy, egg-shaped shell with a toothed slit underneath. The shine comes from the mantle, which the snail folds up over the shell." },
  { name: "Money cowrie", sci: "Monetaria moneta", group: "Sea snail (gastropod)", art: "cowrie",
    regions: ["Indo-Pacific"], size: "to 2.5 cm",
    desc: "Small golden cowrie once used as currency across Africa, Asia and the Pacific — among the most historically traded shells on Earth." },
  { name: "Apple murex", sci: "Chicoreus pomum", group: "Sea snail (gastropod)", art: "murex",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 11 cm",
    desc: "Knobby, frilled shell with three ridges of spines. Murexes are predators; some Mediterranean species were the source of ancient royal 'Tyrian purple' dye." },
  { name: "Chambered nautilus", sci: "Nautilus pompilius", group: "Cephalopod shell", art: "nautilus",
    regions: ["Indo-Pacific"], size: "to 20 cm",
    desc: "A living-fossil cephalopod whose coiled shell is divided into gas-filled chambers for buoyancy — a textbook logarithmic spiral. Rare as a beach find." },
  { name: "Common sand dollar", sci: "Echinarachnius parma", group: "Echinoderm (urchin relative)", art: "sanddollar",
    regions: ["Atlantic", "Pacific"], size: "to 8 cm",
    desc: "Flattened relative of sea urchins. The white 'test' you find on the beach is the bleached skeleton; live ones are fuzzy purple-brown and should be left alone." },
  { name: "Florida horse conch", sci: "Triplofusus giganteus", group: "Sea snail (gastropod)", art: "conch",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 60 cm",
    desc: "The largest sea snail in American Atlantic waters, with a striking orange aperture. It is the state shell of Florida and a fierce predator of other snails." },
  { name: "Scotch bonnet", sci: "Semicassis granulata", group: "Sea snail (gastropod)", art: "moonsnail",
    regions: ["Atlantic", "Caribbean"], size: "to 10 cm",
    desc: "Helmet-shaped shell patterned with squarish spots in neat spiral rows. It is the state shell of North Carolina and a favorite beachcombing trophy." },
  { name: "Banded tulip", sci: "Cinctura lilium", group: "Sea snail (gastropod)", art: "tulip",
    regions: ["Atlantic", "Gulf"], size: "to 10 cm",
    desc: "Smooth, spindle-shaped shell crossed by thin dark spiral 'threads,' often in soft grey, peach and blue tones. Smaller and smoother than the true tulip." },
  { name: "Coquina", sci: "Donax variabilis", group: "Bivalve (two shells)", art: "scallop",
    regions: ["Atlantic", "Gulf"], size: "to 2.5 cm",
    desc: "Tiny, glossy clams in an endless rainbow of colors and rays. They burrow by the thousands in the wave-washed swash zone; open pairs look like butterfly wings." },
  { name: "Angel wing", sci: "Cyrtopleura costata", group: "Bivalve (two shells)", art: "razor",
    regions: ["Atlantic", "Gulf"], size: "to 18 cm",
    desc: "A fragile, chalk-white shell ribbed like a feathered wing. The living clam burrows deep into mud, so intact beach finds are a treat." },
  { name: "Turkey wing ark", sci: "Arca zebra", group: "Bivalve (two shells)", art: "cockle",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 9 cm",
    desc: "Boxy ark clam streaked in brown and cream like a turkey's wing. It anchors to rocks with tough byssal threads rather than burrowing." },
  { name: "Atlantic wing oyster", sci: "Pteria colymbus", group: "Bivalve (two shells)", art: "oyster",
    regions: ["Atlantic", "Caribbean"], size: "to 7 cm",
    desc: "A pearly-lined shell with a long, wing-like hinge. It often grows attached to sea whips and soft corals out on the reef." },
  { name: "Common nutmeg", sci: "Cancellaria reticulata", group: "Sea snail (gastropod)", art: "whelk",
    regions: ["Atlantic", "Gulf", "Caribbean"], size: "to 5 cm",
    desc: "Named for its nutmeg-like look, with a crisscross 'cancellate' surface of fine ridges in grey and tan. A common but handsome shoreline find." }
];
