# Scientific names for the 444 species lessons. Used to (a) enrich each lesson's
# text and (b) make the photo fetch match the EXACT taxon on iNaturalist.
# Binomial where the lesson is one species; genus/family/order where it's a group.
# A few microbes are left blank on purpose (no good photo taxon -> vector art).
SCI = {
# --- reef & coastal fishes ---
"fish-clownfish": "Amphiprion ocellaris", "fish-mandarinfish": "Synchiropus splendidus",
"fish-parrotfish": "Scaridae", "fish-wrasse": "Labroides dimidiatus",
"fish-angelfish": "Holacanthus ciliaris", "fish-butterflyfish": "Chaetodontidae",
"fish-surgeonfish": "Acanthuridae", "fish-tang": "Paracanthurus hepatus",
"fish-triggerfish": "Balistidae", "fish-pufferfish": "Tetraodontidae",
"fish-porcupinefish": "Diodontidae", "fish-boxfish": "Ostraciidae",
"fish-lionfish": "Pterois", "fish-stonefish": "Synanceia",
"fish-scorpionfish": "Scorpaenidae", "fish-frogfish": "Antennariidae",
"fish-grouper": "Epinephelus itajara", "fish-snapper": "Lutjanus campechanus",
"fish-grunt": "Haemulidae", "fish-goatfish": "Mullidae",
"fish-moorishidol": "Zanclus cornutus", "fish-damselfish": "Pomacentridae",
"fish-anthias": "Pseudanthias", "fish-cardinalfish": "Apogonidae",
"fish-goby": "Gobiidae", "fish-blenny": "Blenniidae", "fish-hawkfish": "Cirrhitidae",
"fish-pipefish": "Syngnathus", "fish-seahorse": "Hippocampus",
"fish-razorfish": "Aeoliscus strigatus", "fish-filefish": "Monacanthidae",
"fish-rabbitfish": "Siganus", "fish-sweetlips": "Plectorhinchus",
"fish-fusilier": "Caesionidae", "fish-soldierfish": "Myripristis",
"fish-squirrelfish": "Holocentridae", "fish-bigeye": "Priacanthidae",
"fish-batfish": "Platax", "fish-jackfish": "Caranx ignobilis",
"fish-pompano": "Trachinotus", "fish-remora": "Echeneidae",
"fish-cobia": "Rachycentron canadum", "fish-mullet": "Mugilidae",
"fish-mudskipper": "Periophthalmus", "fish-archerfish": "Toxotes",
"fish-flounder": "Paralichthys", "fish-halibut": "Hippoglossus",
"fish-sole": "Soleidae", "fish-stargazer": "Uranoscopidae",
"fish-toadfish": "Batrachoididae", "fish-flyingfish": "Exocoetidae",
"fish-needlefish": "Belonidae", "fish-halfbeak": "Hemiramphidae",
"fish-tarpon": "Megalops atlanticus", "fish-snook": "Centropomus",
# --- pelagic & open-ocean fishes ---
"fish-tuna-bluefin": "Thunnus thynnus", "fish-tuna-yellowfin": "Thunnus albacares",
"fish-mackerel": "Scomber scombrus", "fish-wahoo": "Acanthocybium solandri",
"fish-kingmackerel": "Scomberomorus cavalla", "fish-bonito": "Sarda",
"fish-mahimahi": "Coryphaena hippurus", "fish-marlin-blue": "Makaira nigricans",
"fish-sailfish": "Istiophorus platypterus", "fish-swordfish": "Xiphias gladius",
"fish-bluefish": "Pomatomus saltatrix", "fish-jackmackerel": "Trachurus",
"fish-opah": "Lampris guttatus", "fish-sunfish-mola": "Mola mola",
"fish-oarfish": "Regalecus glesne", "fish-herring": "Clupea harengus",
"fish-sardine": "Sardinops sagax", "fish-anchovy": "Engraulis",
"fish-menhaden": "Brevoortia", "fish-capelin": "Mallotus villosus",
"fish-barracuda": "Sphyraena barracuda",
# --- deep-sea fishes ---
"fish-anglerfish-deep": "Melanocetus", "fish-viperfish": "Chauliodus",
"fish-dragonfish": "Idiacanthus", "fish-gulper": "Eurypharynx pelecanoides",
"fish-hatchetfish": "Argyropelecus", "fish-lanternfish": "Myctophidae",
"fish-bristlemouth": "Cyclothone", "fish-fangtooth": "Anoplogaster cornuta",
"fish-tripod": "Bathypterois grallator", "fish-grenadier": "Macrouridae",
"fish-blobfish": "Psychrolutes", "fish-coffinfish": "Chaunax",
"fish-lizardfish": "Bathysaurus", "fish-snailfish-deep": "Pseudoliparis",
"fish-cusk-eel": "Ophidiidae", "fish-coelacanth": "Latimeria chalumnae",
"fish-chimaera": "Chimaeridae",
# --- eels & odd fishes ---
"fish-moray": "Muraenidae", "fish-gardeneel": "Heteroconger",
"fish-conger": "Conger", "fish-electriceel": "Electrophorus electricus",
"fish-freshwater-eel": "Anguilla rostrata", "fish-lamprey": "Petromyzon marinus",
"fish-hagfish": "Myxinidae", "fish-sturgeon": "Acipenser",
"fish-seadragon": "Phycodurus eques",
# --- sharks ---
"shark-greatwhite": "Carcharodon carcharias", "shark-tiger": "Galeocerdo cuvier",
"shark-bull": "Carcharhinus leucas", "shark-hammerhead": "Sphyrna mokarran",
"shark-mako": "Isurus oxyrinchus", "shark-blue": "Prionace glauca",
"shark-whaleshark": "Rhincodon typus", "shark-basking": "Cetorhinus maximus",
"shark-megamouth": "Megachasma pelagios", "shark-thresher": "Alopias",
"shark-nurse": "Ginglymostoma cirratum", "shark-lemon": "Negaprion brevirostris",
"shark-reef-blacktip": "Carcharhinus melanopterus", "shark-reef-whitetip": "Triaenodon obesus",
"shark-sandtiger": "Carcharias taurus", "shark-goblin": "Mitsukurina owstoni",
"shark-frilled": "Chlamydoselachus anguineus", "shark-cookiecutter": "Isistius brasiliensis",
"shark-greenland": "Somniosus microcephalus", "shark-wobbegong": "Orectolobus",
"shark-angel": "Squatina", "shark-saw": "Pristiophorus",
"shark-dogfish": "Squalus acanthias", "shark-catshark": "Scyliorhinidae",
"shark-port-jackson": "Heterodontus portusjacksoni", "shark-zebra": "Stegostoma tigrinum",
"shark-epaulette": "Hemiscyllium ocellatum", "shark-silky": "Carcharhinus falciformis",
"shark-oceanic-whitetip": "Carcharhinus longimanus", "shark-bonnethead": "Sphyrna tiburo",
"shark-salmon": "Lamna ditropis", "shark-porbeagle": "Lamna nasus",
"shark-sixgill": "Hexanchus griseus", "shark-sevengill": "Notorynchus cepedianus",
"shark-swell": "Cephaloscyllium ventriosum", "shark-horn": "Heterodontus francisci",
"shark-bamboo": "Chiloscyllium", "shark-leopard-pacific": "Triakis semifasciata",
"shark-smoothhound": "Mustelus",
# --- rays ---
"ray-manta": "Mobula birostris", "ray-devil": "Mobula",
"ray-eagle": "Aetobatus narinari", "ray-stingray-southern": "Hypanus americanus",
"ray-bluespotted": "Taeniura lymma", "ray-electric": "Torpedo",
"ray-cownose": "Rhinoptera bonasus", "ray-sawfish": "Pristis",
"ray-guitarfish": "Rhinobatos", "ray-skate": "Rajidae",
"ray-manta-reef": "Mobula alfredi", "ray-torpedo-marbled": "Torpedo marmorata",
"ray-batray": "Myliobatis californica", "ray-pelagic-stingray": "Pteroplatytrygon violacea",
# --- whales ---
"mammal-bluewhale": "Balaenoptera musculus", "mammal-finwhale": "Balaenoptera physalus",
"mammal-humpback": "Megaptera novaeangliae", "mammal-graywhale": "Eschrichtius robustus",
"mammal-rightwhale": "Eubalaena glacialis", "mammal-bowhead": "Balaena mysticetus",
"mammal-minke": "Balaenoptera acutorostrata", "mammal-seiwhale": "Balaenoptera borealis",
"mammal-spermwhale": "Physeter macrocephalus", "mammal-pygmysperm": "Kogia breviceps",
"mammal-beaked": "Ziphius cavirostris", "mammal-narwhal": "Monodon monoceros",
"mammal-beluga": "Delphinapterus leucas",
# --- dolphins & porpoises ---
"mammal-orca": "Orcinus orca", "mammal-bottlenose": "Tursiops truncatus",
"mammal-common-dolphin": "Delphinus delphis", "mammal-spinner": "Stenella longirostris",
"mammal-spotted-dolphin": "Stenella frontalis", "mammal-risso": "Grampus griseus",
"mammal-pilot": "Globicephala", "mammal-falsekiller": "Pseudorca crassidens",
"mammal-harborporpoise": "Phocoena phocoena", "mammal-dalls": "Phocoenoides dalli",
"mammal-vaquita": "Phocoena sinus", "mammal-amazon-river": "Inia geoffrensis",
# --- seals, sea lions & walrus ---
"mammal-harborseal": "Phoca vitulina", "mammal-graysealatl": "Halichoerus grypus",
"mammal-elephantseal": "Mirounga", "mammal-leopardseal": "Hydrurga leptonyx",
"mammal-weddell": "Leptonychotes weddellii", "mammal-crabeater": "Lobodon carcinophaga",
"mammal-ross": "Ommatophoca rossii", "mammal-harp": "Pagophilus groenlandicus",
"mammal-ringed": "Pusa hispida", "mammal-monkseal": "Neomonachus schauinslandi",
"mammal-bearded": "Erignathus barbatus", "mammal-californiasealion": "Zalophus californianus",
"mammal-stellersealion": "Eumetopias jubatus", "mammal-fursealnorth": "Callorhinus ursinus",
"mammal-walrus": "Odobenus rosmarus",
# --- other mammals ---
"mammal-seaotter": "Enhydra lutris", "mammal-manatee": "Trichechus",
"mammal-dugong": "Dugong dugon", "mammal-polarbear": "Ursus maritimus",
# --- sea turtles & reptiles ---
"reptile-greenturtle": "Chelonia mydas", "reptile-loggerhead": "Caretta caretta",
"reptile-leatherback": "Dermochelys coriacea", "reptile-hawksbill": "Eretmochelys imbricata",
"reptile-oliveridley": "Lepidochelys olivacea", "reptile-kempsridley": "Lepidochelys kempii",
"reptile-flatback": "Natator depressus", "reptile-seasnake": "Hydrophis",
"reptile-seakrait": "Laticauda", "reptile-marineiguana": "Amblyrhynchus cristatus",
"reptile-saltwatercroc": "Crocodylus porosus",
# --- seabirds ---
"bird-wanderingalbatross": "Diomedea exulans", "bird-laysanalbatross": "Phoebastria immutabilis",
"bird-emperorpenguin": "Aptenodytes forsteri", "bird-kingpenguin": "Aptenodytes patagonicus",
"bird-adeliepenguin": "Pygoscelis adeliae", "bird-gentoo": "Pygoscelis papua",
"bird-galapagospenguin": "Spheniscus mendiculus", "bird-littleblue": "Eudyptula minor",
"bird-atlanticpuffin": "Fratercula arctica", "bird-commonmurre": "Uria aalge",
"bird-razorbill": "Alca torda", "bird-northerngannet": "Morus bassanus",
"bird-bluefoocedbooby": "Sula nebouxii", "bird-brownpelican": "Pelecanus occidentalis",
"bird-frigatebird": "Fregata magnificens", "bird-tropicbird": "Phaethon rubricauda",
"bird-arctictern": "Sterna paradisaea", "bird-sootytern": "Onychoprion fuscatus",
"bird-commontern": "Sterna hirundo", "bird-herringgull": "Larus argentatus",
"bird-kittiwake": "Rissa tridactyla", "bird-cormorant": "Phalacrocorax",
"bird-shag": "Gulosus aristotelis", "bird-skua": "Stercorarius skua",
"bird-petrel-storm": "Hydrobates", "bird-shearwater": "Puffinus",
"bird-fulmar": "Fulmarus glacialis", "bird-pelagic-auklet": "Aethia",
"bird-oystercatcher": "Haematopus",
# --- cnidarians ---
"cnid-moonjelly": "Aurelia aurita", "cnid-lionsmane": "Cyanea capillata",
"cnid-boxjelly": "Chironex fleckeri", "cnid-portuguese": "Physalia physalis",
"cnid-seawasp": "Carukia barnesi", "cnid-cannonball": "Stomolophus meleagris",
"cnid-seaanemone": "Actiniaria", "cnid-tubeanemone": "Cerianthus",
"cnid-staghorn": "Acropora cervicornis", "cnid-elkhorn": "Acropora palmata",
"cnid-braincoral": "Diploria", "cnid-firecoral": "Millepora",
"cnid-softcoral": "Alcyonium", "cnid-seafan": "Gorgonia",
"cnid-seapen": "Pennatula", "cnid-blackcoral": "Antipatharia",
"cnid-hydroid": "Aglaophenia", "cnid-bluebottle-bythewind": "Velella velella",
"cnid-combjelly": "Ctenophora",
# --- cephalopods ---
"ceph-giantpacific": "Enteroctopus dofleini", "ceph-common": "Octopus vulgaris",
"ceph-bluering": "Hapalochlaena", "ceph-mimic": "Thaumoctopus mimicus",
"ceph-dumbo": "Grimpoteuthis", "ceph-coconut": "Amphioctopus marginatus",
"ceph-giantsquid": "Architeuthis dux", "ceph-colossal": "Mesonychoteuthis hamiltoni",
"ceph-humboldt": "Dosidicus gigas", "ceph-vampire": "Vampyroteuthis infernalis",
"ceph-bobtail": "Euprymna", "ceph-reefsquid": "Sepioteuthis sepioidea",
"ceph-cuttlefish": "Sepia", "ceph-flamboyant": "Metasepia pfefferi",
"ceph-nautilus": "Nautilus pompilius", "ceph-paper-nautilus": "Argonauta",
# --- gastropods & sea slugs ---
"gast-conch": "Aliger gigas", "gast-coneshell": "Conus",
"gast-cowrie": "Cypraea", "gast-abalone": "Haliotis",
"gast-limpet": "Patella", "gast-periwinkle": "Littorina",
"gast-whelk": "Buccinum", "gast-murex": "Murex",
"gast-tritontrumpet": "Charonia tritonis", "gast-nudibranch": "Nudibranchia",
"gast-spanishdancer": "Hexabranchus sanguineus", "gast-seahare": "Aplysia",
"gast-seabutterfly": "Limacina", "gast-blueglaucus": "Glaucus atlanticus",
"gast-seaslug-lettuce": "Elysia crispata", "gast-turbansnail": "Turbo",
"gast-topshell": "Trochus", "gast-nerite": "Nerita",
"gast-drupe": "Drupa", "gast-bubbleshell": "Bulla", "gast-tunshell": "Tonna",
# --- bivalves & chitons ---
"biv-giantclam": "Tridacna gigas", "biv-scallop": "Pecten",
"biv-oyster": "Ostreidae", "biv-mussel": "Mytilus edulis",
"biv-cockle": "Cerastoderma", "biv-razor": "Ensis",
"biv-shipworm": "Teredo", "biv-pen-shell": "Pinna",
"biv-quahog": "Arctica islandica", "biv-angelwing": "Cyrtopleura costata",
"moll-chiton": "Polyplacophora",
# --- crustaceans ---
"crus-hermitcrab": "Paguroidea", "crus-fiddlercrab": "Uca",
"crus-ghostcrab": "Ocypode", "crus-bluecrab": "Callinectes sapidus",
"crus-dungeness": "Metacarcinus magister", "crus-kingcrab": "Paralithodes",
"crus-snowcrab": "Chionoecetes opilio", "crus-spidercrab": "Macrocheira kaempferi",
"crus-coconutcrab": "Birgus latro", "crus-porcelaincrab": "Porcellanidae",
"crus-decoratorcrab": "Majidae", "crus-spinylobster": "Panulirus",
"crus-americanlobster": "Homarus americanus", "crus-slipperlobster": "Scyllaridae",
"crus-mantisshrimp": "Stomatopoda", "crus-pistolshrimp": "Alpheus",
"crus-cleanershrimp": "Lysmata amboinensis", "crus-krill": "Euphausia superba",
"crus-copepod": "Copepoda", "crus-amphipod": "Amphipoda",
"crus-isopod-giant": "Bathynomus", "crus-barnacle": "Balanus",
"crus-goosebarnacle": "Lepas", "crus-horseshoecrab": "Limulus polyphemus",
"crus-sandhopper": "Talitrus", "crus-stonecrab": "Menippe mercenaria",
"crus-mudcrab": "Scylla serrata", "crus-arrowcrab": "Stenorhynchus seticornis",
"crus-sallylightfoot": "Grapsus grapsus", "crus-peacrab": "Pinnotheres",
"crus-boxercrab": "Lybia", "crus-kelpcrab": "Pugettia",
"crus-boxcrab": "Calappa", "crus-harlequinshrimp": "Hymenocera picta",
"crus-bandedcoralshrimp": "Stenopus hispidus", "crus-peppermintshrimp": "Lysmata wurdemanni",
"crus-ghostshrimp": "Callianassidae", "crus-anemoneshrimp": "Periclimenes",
"crus-emperorshrimp": "Periclimenes",
# --- echinoderms ---
"echi-seastar": "Asterias", "echi-crownofthorns": "Acanthaster planci",
"echi-sunflowerstar": "Pycnopodia helianthoides", "echi-brittlestar": "Ophiuroidea",
"echi-basketstar": "Gorgonocephalus", "echi-seaurchin": "Echinoidea",
"echi-pencilurchin": "Heterocentrotus mamillatus", "echi-sanddollar": "Clypeasteroida",
"echi-seacucumber": "Holothuroidea", "echi-featherstar": "Crinoidea",
"echi-seapig": "Scotoplanes", "echi-seaapple": "Pseudocolochirus",
"echi-cushionstar": "Culcita", "echi-fireurchin": "Asthenosoma varium",
"echi-flowerurchin": "Toxopneustes pileolus", "echi-hearturchin": "Echinocardium cordatum",
# --- worms ---
"worm-bristle": "Polychaeta", "worm-christmastree": "Spirobranchus giganteus",
"worm-featherduster": "Sabellidae", "worm-tubeworm-vent": "Riftia pachyptila",
"worm-osedax": "Osedax", "worm-flatworm": "Polycladida",
"worm-ribbonworm": "Nemertea", "worm-arrowworm": "Chaetognatha",
"worm-peanutworm": "Sipuncula", "worm-innkeeper": "Urechis", "worm-palolo": "Palola",
# --- sponges & tunicates ---
"spng-barrelsponge": "Xestospongia muta", "spng-glasssponge": "Hexactinellida",
"spng-venusflower": "Euplectella aspergillum", "spng-encrusting": "Demospongiae",
"tuni-seasquirt": "Ascidiacea", "tuni-salp": "Salpidae",
"tuni-pyrosome": "Pyrosoma", "tuni-lightbulb": "Clavelina lepadiformis",
# --- plankton & microbes (some blank on purpose -> vector art) ---
"plank-diatom": "Bacillariophyta", "plank-dinoflagellate": "Dinoflagellata",
"plank-coccolithophore": "Coccolithophyceae", "plank-cyanobacteria": "Prochlorococcus",
"plank-foram": "Foraminifera", "plank-radiolaria": "Radiolaria",
"plank-noctiluca": "Noctiluca scintillans", "plank-trichodesmium": "Trichodesmium",
"microbe-virus": "", "microbe-archaea": "", "microbe-bacterioplankton": "",
"plank-larva": "",
# --- algae & marine plants ---
"algae-giantkelp": "Macrocystis pyrifera", "algae-bullkelp": "Nereocystis luetkeana",
"algae-sargassum": "Sargassum", "algae-sealettuce": "Ulva",
"algae-coralline": "Corallinales", "algae-nori": "Porphyra",
"algae-kombu": "Saccharina", "algae-caulerpa": "Caulerpa",
"algae-halimeda": "Halimeda", "algae-irishmoss": "Chondrus crispus",
"plant-eelgrass": "Zostera marina", "plant-turtlegrass": "Thalassia testudinum",
"plant-posidonia": "Posidonia oceanica", "plant-manateegrass": "Syringodium filiforme",
"plant-redmangrove": "Rhizophora mangle", "plant-blackmangrove": "Avicennia germinans",
"plant-cordgrass": "Spartina",
}

# --- remaining fishes & cnidarians ---
SCI.update({
"fish-hogfish": "Lachnolaimus maximus", "fish-napoleonwrasse": "Cheilinus undulatus",
"fish-dottyback": "Pseudochromidae", "fish-jawfish": "Opistognathus",
"fish-firefish": "Nemateleotris", "fish-tilefish": "Malacanthidae",
"fish-wolffish": "Anarhichas lupus", "fish-lumpsucker": "Cyclopterus lumpus",
"fish-sculpin": "Cottidae", "fish-rockfish": "Sebastes",
"fish-greenling": "Hexagrammos", "fish-cod": "Gadus morhua",
"fish-haddock": "Melanogrammus aeglefinus", "fish-pollock": "Gadus chalcogrammus",
"fish-hake": "Merluccius", "fish-surfperch": "Embiotocidae",
"fish-blackdrum": "Pogonias cromis", "fish-croaker": "Micropogonias undulatus",
"fish-reddrum": "Sciaenops ocellatus", "fish-sheepshead": "Archosargus probatocephalus",
"fish-porgy": "Sparidae", "fish-trumpetfish": "Aulostomus",
"fish-cornetfish": "Fistularia", "fish-pineconefish": "Monocentris",
"fish-grunion": "Leuresthes tenuis", "fish-sandlance": "Ammodytes",
"fish-icefish": "Channichthyidae", "fish-silverside": "Atherinidae",
"cnid-mushroomcoral": "Fungiidae", "cnid-bubblecoral": "Plerogyra sinuosa",
"cnid-suncoral": "Tubastraea", "cnid-pillarcoral": "Dendrogyra cylindrus",
"cnid-carpetanemone": "Stichodactyla", "cnid-magnificentanemone": "Heteractis magnifica",
"cnid-zoanthid": "Zoanthus",
})
