# -*- coding: utf-8 -*-
# Supporting reference content for AstroHype. Field shapes match the engine exactly.

GLOSSARY = [
 {"term":"Asteroid","cat":"Solar System","def":"A small rocky body that orbits the Sun, most found in the belt between Mars and Jupiter."},
 {"term":"Astronomical unit","cat":"Measurement","def":"The average distance from Earth to the Sun, about 150 million kilometres."},
 {"term":"Atmosphere","cat":"Planets","def":"The layer of gases held around a world by its gravity."},
 {"term":"Aurora","cat":"Phenomena","def":"Glowing lights near a planet's poles caused by particles from the Sun hitting the air."},
 {"term":"Axis","cat":"Motion","def":"The imaginary line through a planet's poles that it spins around."},
 {"term":"Big Bang","cat":"Cosmology","def":"The leading theory that the universe began hot and dense and has been expanding for about 13.8 billion years."},
 {"term":"Black hole","cat":"Exotic objects","def":"A region where gravity is so strong that not even light can escape."},
 {"term":"Celestial sphere","cat":"Sky","def":"An imaginary dome of sky around Earth used to map where objects appear."},
 {"term":"Comet","cat":"Solar System","def":"An icy body that grows a glowing head and tail when it nears the Sun."},
 {"term":"Constellation","cat":"Sky","def":"One of 88 official regions of the sky, traditionally seen as a star pattern."},
 {"term":"Corona","cat":"The Sun","def":"The Sun's faint outer atmosphere, visible during a total solar eclipse."},
 {"term":"Cosmic microwave background","cat":"Cosmology","def":"Faint leftover radiation from the early universe, evidence for the Big Bang."},
 {"term":"Cosmology","cat":"Cosmology","def":"The study of the universe as a whole, its origin, structure and fate."},
 {"term":"Crater","cat":"Surfaces","def":"A bowl-shaped pit made when a space rock strikes a world's surface."},
 {"term":"Dark energy","cat":"Cosmology","def":"An unknown influence that is causing the universe's expansion to speed up."},
 {"term":"Dark matter","cat":"Cosmology","def":"Invisible matter detected only by its gravity, far more common than ordinary matter."},
 {"term":"Declination","cat":"Coordinates","def":"A star's north-south position in the sky, similar to latitude on Earth."},
 {"term":"Dwarf planet","cat":"Solar System","def":"A round world orbiting the Sun that shares its zone with other bodies, like Pluto."},
 {"term":"Eclipse","cat":"Phenomena","def":"When one body's shadow falls on another, as in a solar or lunar eclipse."},
 {"term":"Ellipse","cat":"Motion","def":"A stretched oval, the true shape of an orbit."},
 {"term":"Escape velocity","cat":"Motion","def":"The speed needed to break free of a world's gravity for good."},
 {"term":"Event horizon","cat":"Exotic objects","def":"The boundary of a black hole, past which nothing can return."},
 {"term":"Exoplanet","cat":"Other worlds","def":"A planet that orbits a star other than our Sun."},
 {"term":"Galaxy","cat":"Galaxies","def":"A huge system of stars, gas, dust and dark matter held together by gravity."},
 {"term":"Gas giant","cat":"Planets","def":"A large planet made mostly of gas, like Jupiter or Saturn."},
 {"term":"Globular cluster","cat":"Star groups","def":"An ancient, tightly packed ball of hundreds of thousands of stars."},
 {"term":"Gravity","cat":"Forces","def":"The attractive force between any two objects that have mass."},
 {"term":"Habitable zone","cat":"Other worlds","def":"The region around a star where a planet could have liquid water."},
 {"term":"Kuiper Belt","cat":"Solar System","def":"A broad ring of icy bodies beyond Neptune, home to Pluto and many small worlds."},
 {"term":"Light-year","cat":"Measurement","def":"The distance light travels in one year, about 9.5 trillion kilometres."},
 {"term":"Lunar eclipse","cat":"Phenomena","def":"When the Moon passes into Earth's shadow and often turns red."},
 {"term":"Magnitude","cat":"Measurement","def":"A number measuring brightness, where smaller means brighter."},
 {"term":"Main sequence","cat":"Stars","def":"The long, stable stage when a star fuses hydrogen in its core."},
 {"term":"Meteor","cat":"Phenomena","def":"The streak of light made when a bit of space dust burns up in the atmosphere."},
 {"term":"Meteorite","cat":"Solar System","def":"A piece of space rock that survives its fall and lands on the ground."},
 {"term":"Milky Way","cat":"Galaxies","def":"The barred spiral galaxy that contains our Solar System."},
 {"term":"Moon","cat":"Solar System","def":"A natural object that orbits a planet, dwarf planet or asteroid."},
 {"term":"Nebula","cat":"Deep sky","def":"A cloud of gas and dust in space, where stars are born or where they die."},
 {"term":"Neutron star","cat":"Exotic objects","def":"An incredibly dense stellar core left behind by a supernova."},
 {"term":"Nuclear fusion","cat":"Stars","def":"Joining light atoms into heavier ones, the process that powers stars."},
 {"term":"Oort Cloud","cat":"Solar System","def":"A vast spherical shell of comets far surrounding the Solar System."},
 {"term":"Orbit","cat":"Motion","def":"The curved path one object follows around another under gravity."},
 {"term":"Phase","cat":"The Moon","def":"The shape of the Moon's lit part as seen from Earth, from new to full."},
 {"term":"Planet","cat":"Solar System","def":"A large round world that orbits the Sun and has cleared its path of other objects."},
 {"term":"Planetary nebula","cat":"Stars","def":"A glowing shell of gas puffed off by a dying Sun-like star."},
 {"term":"Pulsar","cat":"Exotic objects","def":"A fast-spinning neutron star that sweeps beams of radiation past us."},
 {"term":"Quasar","cat":"Galaxies","def":"The blazing core of a distant galaxy, powered by a giant black hole."},
 {"term":"Red giant","cat":"Stars","def":"A dying Sun-like star that has swelled to enormous size."},
 {"term":"Redshift","cat":"Cosmology","def":"The reddening of light from objects moving away from us as space expands."},
 {"term":"Right ascension","cat":"Coordinates","def":"A star's east-west position in the sky, similar to longitude on Earth."},
 {"term":"Solar System","cat":"Solar System","def":"The Sun together with everything bound to it by gravity."},
 {"term":"Solar wind","cat":"The Sun","def":"A constant stream of particles flowing outward from the Sun."},
 {"term":"Spiral galaxy","cat":"Galaxies","def":"A galaxy with arms winding out from a central bulge, like the Milky Way."},
 {"term":"Star cluster","cat":"Star groups","def":"A group of stars that formed together and stay near one another."},
 {"term":"Supernova","cat":"Stars","def":"The explosive death of a massive star, briefly outshining a galaxy."},
 {"term":"Telescope","cat":"Tools","def":"An instrument that gathers light or radio waves to reveal distant objects."},
 {"term":"Terrestrial planet","cat":"Planets","def":"A small, rocky planet like Mercury, Venus, Earth or Mars."},
 {"term":"White dwarf","cat":"Stars","def":"The small, dense, fading core left when a Sun-like star dies."},
]

PRON = [
 {"term":"Betelgeuse","say":"BEETLE-juice","note":"The red supergiant marking Orion's shoulder."},
 {"term":"Uranus","say":"YOOR-uh-nuss","note":"The sideways ice giant; astronomers prefer this stress to avoid giggles."},
 {"term":"Aldebaran","say":"al-DEB-uh-ran","note":"The orange eye of Taurus the bull."},
 {"term":"Andromeda","say":"an-DROM-uh-duh","note":"The nearest large galaxy and its constellation."},
 {"term":"Cassiopeia","say":"kass-ee-oh-PEE-uh","note":"The W-shaped queen of the northern sky."},
 {"term":"Ophiuchus","say":"oh-fee-YOO-kus","note":"The large serpent-bearer constellation."},
 {"term":"Sagittarius","say":"saj-ih-TAIR-ee-us","note":"The archer pointing at the galaxy's heart."},
 {"term":"Ganymede","say":"GAN-ih-meed","note":"Jupiter's moon, the largest in the Solar System."},
 {"term":"Io","say":"EYE-oh","note":"Jupiter's fiery, volcanic moon."},
 {"term":"Callisto","say":"kuh-LISS-toh","note":"Jupiter's heavily cratered outer moon."},
 {"term":"Enceladus","say":"en-SELL-uh-dus","note":"Saturn's icy moon with watery geysers."},
 {"term":"Titan","say":"TY-tun","note":"Saturn's giant moon with a thick atmosphere."},
 {"term":"Ceres","say":"SEER-eez","note":"The dwarf planet in the asteroid belt."},
 {"term":"Eris","say":"AIR-iss","note":"A distant dwarf planet about Pluto's size."},
 {"term":"Halley","say":"HAL-ee","note":"The famous comet; rhymes with 'valley'."},
 {"term":"Nebula","say":"NEB-yoo-luh","note":"A cloud of gas and dust; plural is nebulae."},
 {"term":"Quasar","say":"KWAY-zar","note":"A galaxy's brilliant, black-hole-powered core."},
 {"term":"Pulsar","say":"PULL-zar","note":"A spinning neutron star that pulses."},
 {"term":"Cepheid","say":"SEFF-ee-id","note":"A pulsing star used to measure distances."},
 {"term":"Pleiades","say":"PLEE-uh-deez","note":"The Seven Sisters star cluster in Taurus."},
 {"term":"Algol","say":"AL-gol","note":"The 'demon star' that dims every few days."},
 {"term":"Rigel","say":"RYE-jel","note":"The brilliant blue supergiant in Orion."},
 {"term":"Procyon","say":"PROH-see-on","note":"A bright star in the little dog, Canis Minor."},
 {"term":"Vega","say":"VEE-guh","note":"The blue-white star in Lyra, a future pole star."},
 {"term":"Arcturus","say":"ark-TOOR-us","note":"The bright orange giant in Bootes."},
 {"term":"Perseid","say":"PUR-see-id","note":"The popular August meteor shower."},
]

# "Object classes" replaces taxonomy: how astronomers sort what's out there.
TAXONOMY = [
 {"group":"Stars","rank":"Glowing gas balls","examples":"The Sun, Sirius, Betelgeuse, Polaris","note":"Make their own light by fusing atoms in their cores."},
 {"group":"Planets","rank":"Eight major worlds","examples":"Mercury, Earth, Jupiter, Neptune","note":"Round worlds that orbit the Sun and have cleared their paths."},
 {"group":"Dwarf planets","rank":"Round but not dominant","examples":"Pluto, Ceres, Eris, Makemake","note":"Round worlds that share their orbit with other bodies."},
 {"group":"Moons","rank":"Natural satellites","examples":"The Moon, Titan, Europa, Ganymede","note":"Orbit planets or smaller bodies rather than the Sun directly."},
 {"group":"Asteroids","rank":"Rocky leftovers","examples":"Vesta, Pallas, Bennu, Ryugu","note":"Small rocky bodies, most in the belt between Mars and Jupiter."},
 {"group":"Comets","rank":"Icy wanderers","examples":"Halley, Hale-Bopp, NEOWISE","note":"Icy bodies that grow tails when warmed by the Sun."},
 {"group":"Nebulae","rank":"Clouds of gas and dust","examples":"Orion, Crab, Ring, Helix","note":"Where stars are born, and where dying stars shed their gas."},
 {"group":"Star clusters","rank":"Families of stars","examples":"Pleiades, Hyades, M13, Omega Centauri","note":"Groups of stars born together from the same cloud."},
 {"group":"Galaxies","rank":"Cities of stars","examples":"Milky Way, Andromeda, Whirlpool","note":"Vast systems of stars, gas and dark matter bound by gravity."},
 {"group":"Black holes","rank":"Gravity's extreme","examples":"Sagittarius A*, Cygnus X-1","note":"Regions where gravity traps even light."},
 {"group":"Neutron stars & pulsars","rank":"Crushed stellar cores","examples":"Crab Pulsar, Vela Pulsar","note":"Ultra-dense remains of exploded massive stars."},
 {"group":"Exoplanets","rank":"Worlds of other suns","examples":"51 Pegasi b, TRAPPIST-1 planets","note":"Planets orbiting stars far beyond our Solar System."},
]

CONCEPTS = [
 {"title":"Looking out is looking back","body":"Light takes time to travel, so the farther away something is, the older the light we see. Looking deep into space is also looking deep into the past, all the way back toward the early universe.","src":"nasa"},
 {"title":"Gravity rules everything","body":"From a falling apple to the orbits of planets and the shape of galaxies, one gentle force shapes it all. The more mass an object has, the stronger its pull, and the closer you are, the stronger it feels.","src":"nasa"},
 {"title":"We are made of star stuff","body":"The atoms in your body, the iron in your blood and the oxygen you breathe were forged inside stars and scattered by their deaths. Every person is built from the ashes of ancient stars.","src":"esahubble"},
 {"title":"The universe is mostly empty","body":"Space is vast and the objects in it are tiny by comparison. Even the busy-looking asteroid belt is so spread out that spacecraft pass through it with ease.","src":"nasaplanets"},
 {"title":"Stars are born, live and die","body":"Stars form in clouds of gas, shine for millions or billions of years, then end as fading embers or violent explosions. Their endings seed space with the material for new stars and worlds.","src":"esahubble"},
 {"title":"Our place is humble","body":"Earth is one small world circling an ordinary star, in one of hundreds of billions of galaxies. Astronomy gently reminds us how vast the universe is and how much we still have to learn.","src":"iau"},
 {"title":"The sky is a clock and a map","body":"For thousands of years people have used the Sun, Moon and stars to mark time, find direction and plan the seasons. The motions of the sky are steady and predictable.","src":"nasa"},
 {"title":"The universe is expanding","body":"Distant galaxies are racing away from us, and the farther they are, the faster they recede. Space itself is stretching, carrying the galaxies apart like raisins in rising dough.","src":"esahubble"},
 {"title":"Science changes with evidence","body":"When new discoveries arrive, science updates its ideas, even cherished ones. Pluto's move from planet to dwarf planet shows how definitions sharpen as we learn more.","src":"iau"},
 {"title":"Anyone can explore the sky","body":"Astronomy begins with simply looking up. With patient eyes, a star map, or a pair of binoculars, anyone can find planets, clusters and the band of the Milky Way.","src":"nasa"},
]

CAREERS = [
 {"role":"Astronomer","what":"Studies stars, galaxies and the universe, often using telescopes and large sets of data.","path":"A degree in physics or astronomy, usually followed by graduate study and research.","src":"nasa"},
 {"role":"Astrophysicist","what":"Uses physics to explain how stars, black holes and the cosmos work.","path":"Strong maths and physics, then a university degree and often a doctorate.","src":"esahubble"},
 {"role":"Planetary scientist","what":"Studies planets, moons, asteroids and comets, including data from space missions.","path":"A science degree in geology, physics or planetary science, plus research experience.","src":"nasaplanets"},
 {"role":"Aerospace engineer","what":"Designs and builds rockets, satellites, rovers and spacecraft.","path":"A degree in aerospace or mechanical engineering and hands-on project work.","src":"jpl"},
 {"role":"Astronaut","what":"Trains to live and work in space, running experiments and maintaining spacecraft.","path":"A science, engineering or medical background, top fitness, and years of selection and training.","src":"nasa"},
 {"role":"Mission operator","what":"Commands spacecraft and keeps them healthy from control rooms on Earth.","path":"A degree in engineering or science and specialised training in spacecraft operations.","src":"jpl"},
 {"role":"Data scientist","what":"Finds discoveries hidden in the huge data sets that telescopes produce.","path":"Skills in maths, statistics and computer programming, often with a science degree.","src":"noirlab"},
 {"role":"Optical engineer","what":"Designs the mirrors, lenses and instruments that make telescopes work.","path":"A degree in physics, optics or engineering and specialised study of light.","src":"stsci"},
 {"role":"Science communicator","what":"Shares discoveries through writing, video, museums and planetariums.","path":"A mix of science knowledge and skill in writing, media or teaching.","src":"esa"},
 {"role":"Planetarium educator","what":"Teaches the public about the night sky using a domed star theatre.","path":"A background in astronomy or education and a love of explaining the cosmos.","src":"nasa"},
]

HISTORY = [
 {"year":"c. 3000 BCE","title":"Ancient sky-watchers","body":"Civilisations from Babylon to Egypt to China carefully track the Sun, Moon and stars to mark seasons, festivals and time."},
 {"year":"c. 150 CE","title":"Ptolemy maps the heavens","body":"The astronomer Ptolemy writes down an Earth-centred model of the cosmos that will guide astronomy for over a thousand years."},
 {"year":"1543","title":"The Sun takes centre stage","body":"Copernicus argues that the Earth and planets orbit the Sun, not the other way around, beginning a revolution in thought."},
 {"year":"1609","title":"Galileo's telescope","body":"Galileo turns a telescope to the sky, discovering mountains on the Moon and four moons of Jupiter, and changing astronomy forever."},
 {"year":"1687","title":"Newton explains gravity","body":"Isaac Newton shows that one law of gravity governs both falling apples and orbiting planets, uniting the heavens and the Earth."},
 {"year":"1929","title":"The expanding universe","body":"Edwin Hubble finds that distant galaxies are racing away from us, revealing that the whole universe is expanding."},
 {"year":"1957","title":"The space age begins","body":"The Soviet Union launches Sputnik, the first artificial satellite, opening the era of space exploration."},
 {"year":"1969","title":"Humans walk on the Moon","body":"Apollo 11 lands the first people on the Moon, the farthest humans have ever travelled from Earth."},
 {"year":"1990","title":"Hubble opens a new window","body":"The Hubble Space Telescope launches into orbit, returning astonishingly clear views of the distant universe."},
 {"year":"2019","title":"A black hole, pictured","body":"The Event Horizon Telescope releases the first direct image of a black hole, in the galaxy Messier 87."},
]

MILESTONES = [
 {"id":"first-light","need":1,"title":"First Light","blurb":"You finished your first lesson. In astronomy, 'first light' is the moment a new telescope sees the sky for the first time.","cite":"NASA"},
 {"id":"stargazer","need":10,"title":"Stargazer","blurb":"Ten lessons done. You are learning to read the night sky like the sky-watchers of old.","cite":"International Astronomical Union"},
 {"id":"navigator","need":25,"title":"Sky Navigator","blurb":"Twenty-five lessons complete. Sailors once crossed oceans guided by this kind of knowledge.","cite":"NASA"},
 {"id":"explorer","need":50,"title":"Solar Explorer","blurb":"Fifty lessons. You have journeyed in your mind across the worlds of the Solar System.","cite":"NASA Solar System Exploration"},
 {"id":"voyager","need":100,"title":"Deep-Space Voyager","blurb":"One hundred lessons. Like the Voyager probes, you are reaching far beyond where you began.","cite":"NASA Jet Propulsion Laboratory"},
 {"id":"galaxy-hopper","need":200,"title":"Galaxy Hopper","blurb":"Two hundred lessons. You are travelling among the galaxies, the great cities of stars.","cite":"ESA/Hubble"},
 {"id":"cosmologist","need":350,"title":"Budding Cosmologist","blurb":"Three hundred and fifty lessons. You are grappling with the biggest questions about the whole universe.","cite":"ESA/Hubble"},
 {"id":"astronomer","need":501,"title":"Master Astronomer","blurb":"Every lesson complete. You have explored the cosmos from the Moon to the edge of the observable universe.","cite":"International Astronomical Union"},
]

# Meteorite & space-rock collection (repurposes the rock/shell collection screen).
# art uses space art keys; regions are category tags used for grouping/filtering.
SHELLS = [
 {"name":"Iron meteorite","sci":"Iron-nickel metal","group":"Iron meteorite","art":"asteroid","regions":["Iron"],"size":"Mostly metal","desc":"A dense lump of iron and nickel from the shattered core of an ancient asteroid. Cut and etched, many show a criss-cross Widmanstatten pattern that only forms over millions of years of slow cooling in space."},
 {"name":"Stony meteorite","sci":"Silicate rock","group":"Stony meteorite","art":"asteroid","regions":["Stony"],"size":"Rocky","desc":"The most common kind of meteorite, made mostly of rock. A dark, glassy 'fusion crust' forms on the outside as it burns through the atmosphere."},
 {"name":"Stony-iron meteorite","sci":"Rock and metal mix","group":"Stony-iron meteorite","art":"asteroid","regions":["Stony-iron"],"size":"Mixed","desc":"A rare blend of rock and metal. The most beautiful type, the pallasite, holds green olivine crystals set in shining metal like stained glass."},
 {"name":"Chondrite","sci":"Contains chondrules","group":"Stony meteorite","art":"asteroid","regions":["Stony"],"size":"Ancient","desc":"An unmelted stony meteorite dotted with tiny round beads called chondrules. These are among the oldest solid materials in the Solar System, older than any planet."},
 {"name":"Carbonaceous chondrite","sci":"Carbon-rich","group":"Stony meteorite","art":"asteroid","regions":["Stony"],"size":"Carbon-rich","desc":"A dark, fragile meteorite rich in carbon and even water and simple organic molecules, offering clues to how the building blocks of life were delivered to worlds."},
 {"name":"Pallasite","sci":"Olivine in metal","group":"Stony-iron meteorite","art":"asteroid","regions":["Stony-iron"],"size":"Gem-bearing","desc":"A prized stony-iron meteorite with translucent green olivine crystals embedded in iron-nickel metal, thought to form at the boundary between an asteroid's core and mantle."},
 {"name":"Lunar meteorite","sci":"From the Moon","group":"Lunar meteorite","art":"moon","regions":["Lunar"],"size":"Moon rock","desc":"A piece of the Moon blasted into space by an impact, which later fell to Earth. Its chemistry matches the rocks the Apollo astronauts brought home."},
 {"name":"Martian meteorite","sci":"From Mars","group":"Martian meteorite","art":"planet","regions":["Martian"],"size":"Mars rock","desc":"A rare meteorite chipped off Mars by a giant impact. Trapped gas inside matches the Martian atmosphere measured by spacecraft, proving its origin."},
 {"name":"Tektite","sci":"Impact glass","group":"Impact glass","art":"asteroid","regions":["Impactite"],"size":"Natural glass","desc":"A blob of natural glass formed when a meteorite impact melted Earth's rock and flung it through the air, where it cooled into smooth, dark shapes."},
 {"name":"Moldavite","sci":"Green tektite","group":"Impact glass","art":"asteroid","regions":["Impactite"],"size":"Green glass","desc":"A bottle-green tektite from a huge impact in Europe about 15 million years ago, prized as a gemstone."},
 {"name":"Hoba meteorite","sci":"Largest known","group":"Iron meteorite","art":"asteroid","regions":["Iron","Famous"],"size":"~60 tonnes","desc":"The largest single meteorite ever found, resting where it fell in Namibia. So heavy it has never been moved, it is a flat slab of iron and nickel."},
 {"name":"Canyon Diablo","sci":"Meteor Crater iron","group":"Iron meteorite","art":"asteroid","regions":["Iron","Famous"],"size":"Crater-maker","desc":"Fragments of the iron asteroid that blasted out Meteor Crater in Arizona about 50,000 years ago, a kilometre-wide bowl still visible today."},
 {"name":"Allende meteorite","sci":"Famous carbonaceous","group":"Stony meteorite","art":"asteroid","regions":["Stony","Famous"],"size":"Fell 1969","desc":"A widely studied carbonaceous meteorite that fell in Mexico in 1969, packed with ancient grains that predate the Solar System."},
 {"name":"Murchison meteorite","sci":"Organic-rich","group":"Stony meteorite","art":"asteroid","regions":["Stony","Famous"],"size":"Fell 1969","desc":"A carbonaceous meteorite famous for containing amino acids, the building blocks of proteins, hinting that such chemistry is common in space."},
 {"name":"Willamette meteorite","sci":"Large iron","group":"Iron meteorite","art":"asteroid","regions":["Iron","Famous"],"size":"~15 tonnes","desc":"A huge iron meteorite found in Oregon, pitted with deep cavities, long held sacred by Indigenous peoples of the region."},
 {"name":"Sikhote-Alin","sci":"Witnessed iron fall","group":"Iron meteorite","art":"asteroid","regions":["Iron","Famous"],"size":"Fell 1947","desc":"An iron meteorite seen falling over Russia in 1947 in a brilliant fireball, scattering thousands of twisted metal fragments."},
 {"name":"Nakhla meteorite","sci":"Martian, fell 1911","group":"Martian meteorite","art":"planet","regions":["Martian","Famous"],"size":"Mars rock","desc":"A Martian meteorite that fell in Egypt in 1911, one of the first stones recognised as having come from the red planet."},
 {"name":"Micrometeorite","sci":"Tiny space dust","group":"Stony meteorite","art":"asteroid","regions":["Stony"],"size":"Microscopic","desc":"A speck of space dust that survives its fall, so small it can settle on rooftops. Tonnes of this cosmic dust drift down onto Earth every day."},
 {"name":"Ureilite","sci":"Carbon-bearing stony","group":"Stony meteorite","art":"asteroid","regions":["Stony"],"size":"Diamond-bearing","desc":"An unusual stony meteorite containing carbon, sometimes even tiny diamonds formed by the shock of cosmic impacts."},
 {"name":"Mesosiderite","sci":"Mixed stony-iron","group":"Stony-iron meteorite","art":"asteroid","regions":["Stony-iron"],"size":"Jumbled","desc":"A jumbled stony-iron meteorite of broken rock and metal welded together, recording a violent collision between asteroids long ago."},
]

MARVELS = [
 {"title":"The Sun is unimaginably huge","fact":"More than a million Earths could fit inside the Sun, and it holds 99.8% of all the mass in the Solar System.","src":"nasa"},
 {"title":"A storm bigger than Earth","fact":"Jupiter's Great Red Spot is a storm so large that the entire Earth could fit inside it, and it has raged for centuries.","src":"nasaplanets"},
 {"title":"The fastest spacecraft ever","fact":"The Parker Solar Probe reaches about 690,000 km/h as it whips around the Sun, fast enough to fly from New York to London in seconds.","src":"jpl"},
 {"title":"A spoonful that weighs a mountain","fact":"Neutron stars are so dense that a single sugar-cube of their material would weigh about as much as a mountain.","src":"esahubble"},
 {"title":"More stars than grains of sand","fact":"There are more stars in the observable universe than grains of sand on every beach on Earth combined.","src":"esahubble"},
 {"title":"Light takes ages to cross space","fact":"Light from the next nearest star takes over four years to reach us, and from the Andromeda Galaxy, about 2.5 million years.","src":"nasa"},
 {"title":"Diamonds may rain on Neptune","fact":"Deep inside Neptune and Uranus, crushing pressure may turn carbon into diamonds that drift down like rain.","src":"nasaplanets"},
 {"title":"A day longer than a year","fact":"Venus spins so slowly that a single Venusian day lasts longer than its entire year around the Sun.","src":"nasaplanets"},
 {"title":"The tallest mountain in the Solar System","fact":"Mars hosts Olympus Mons, a volcano about three times the height of Mount Everest and as wide as a country.","src":"nasaplanets"},
 {"title":"Saturn could float","fact":"Saturn is so light for its size that, given a big enough ocean, the whole planet would float on water.","src":"nasaplanets"},
 {"title":"We have touched an asteroid and a comet","fact":"Spacecraft have landed on comets and grabbed pieces of asteroids, returning samples of the early Solar System to Earth.","src":"esa"},
 {"title":"Footprints that will last","fact":"With no wind or rain, the Apollo astronauts' footprints on the Moon could remain for millions of years.","src":"nasa"},
]

if __name__ == "__main__":
    print("glossary",len(GLOSSARY),"pron",len(PRON),"taxonomy",len(TAXONOMY),
          "concepts",len(CONCEPTS),"careers",len(CAREERS),"history",len(HISTORY),
          "milestones",len(MILESTONES),"shells",len(SHELLS),"marvels",len(MARVELS))
