# -*- coding: utf-8 -*-
# Hand-authored concept lessons. Structured as tracks -> units -> lessons so we can
# build both the lessons dict and the UNIT_PLAN ordering. Part 1 of 2.

def mc(q, choices, answer, why):
    return {"type":"mc","q":q,"choices":choices,"answer":answer,"why":why}
def tf(q, answer, why):
    return {"type":"tf","q":q,"answer":answer,"why":why}

# Each lesson: dict with id,title,level,explain[2],why,hook,terms,quiz,src,(misconception)
# Units: (unit_id, title, subtitle, level, [lessons])

FOUNDATIONS = [
 ("u-found-1","What Astronomy Is","Looking up, and what we are looking at","Foundations",[
   {"id":"what-is-astronomy","title":"What Is Astronomy?","level":"Foundations",
    "explain":["Astronomy is the science of everything beyond Earth: the Sun, Moon, planets, stars, galaxies and the whole universe. It is one of the oldest sciences, because people have always watched the sky to track time, seasons and direction.",
               "Astronomers study light and other signals that reach us from space. Because that light takes time to travel, looking far out into space also means looking back in time."],
    "why":"Astronomy is how we learn our place in a universe far larger and older than the Earth.",
    "hook":"Every time you look at a star, you are seeing light that left it years, even centuries, ago.",
    "terms":[["Astronomy","The scientific study of objects and events beyond Earth's atmosphere."],
             ["Universe","Everything that exists: all space, time, matter and energy."]],
    "quiz":[mc("Astronomy is the study of:",["weather on Earth","everything beyond Earth","only the Moon","rocks underground"],1,"Astronomy covers everything beyond Earth."),
            tf("Because light takes time to travel, looking far into space is also looking back in time.",True,"True - distant light shows the past.")]},
   {"id":"astronomy-vs-astrology","title":"Astronomy vs Astrology","level":"Foundations",
    "explain":["Astronomy is a science: it uses observation, measurement and testing to learn how the universe really works. Astrology is the much older belief that the positions of stars and planets control human lives, and it is not supported by evidence.",
               "The two share a tangled history, since ancient sky-watchers did both. Today only astronomy is a science, though we still keep old astrological names like the 'zodiac' for parts of the sky."],
    "why":"Knowing the difference helps you tell real science from belief that only looks scientific.",
    "hook":"Same night sky, two very different ways of thinking about it.",
    "terms":[["Astrology","The non-scientific belief that star and planet positions influence human affairs."],
             ["Evidence","Observations or measurements used to test whether an idea is true."]],
    "misconception":"Your 'star sign' does not actually line up with where the Sun is today, because Earth's axis has slowly shifted over thousands of years.",
    "quiz":[mc("Which one is a science?",["astrology","astronomy","both equally","neither"],1,"Astronomy is the science."),
            tf("Astrology is supported by strong scientific evidence.",False,"It is not; astronomy is the science.")]},
 ]),
 ("u-found-2","Finding Your Way Around the Sky","The celestial sphere and how the sky moves","Foundations",[
   {"id":"celestial-sphere","title":"The Celestial Sphere","level":"Foundations",
    "explain":["The stars are at wildly different distances, but they look as though they are stuck to the inside of a giant dome around us. Astronomers use this imaginary 'celestial sphere' as a map, marking positions much like latitude and longitude on Earth.",
               "The sphere seems to turn once a day, carrying the stars from east to west. Really it is the Earth that spins; the sky only appears to move."],
    "why":"The celestial sphere is the basic map astronomers use to say where anything is in the sky.",
    "hook":"The whole sky is a map, and you are standing at its center.",
    "terms":[["Celestial sphere","An imaginary dome of sky around Earth used to map the positions of objects."],
             ["Celestial pole","The point in the sky directly above Earth's north or south pole, around which the sky seems to turn."]],
    "quiz":[mc("The stars seem to move across the sky each night mainly because:",["the stars orbit Earth","the Earth spins","the Sun pushes them","the Moon pulls them"],1,"Earth's spin makes the sky appear to turn."),
            tf("On the celestial sphere, all stars are really the same distance from Earth.",False,"They only appear that way; distances vary hugely.")]},
   {"id":"constellations-explained","title":"How Constellations Work","level":"Foundations",
    "explain":["A constellation is a pattern people imagined by connecting bright stars, like cosmic dot-to-dot. The stars in a pattern are usually not near each other in space at all; they just happen to line up from our point of view.",
               "Astronomers have agreed on 88 official constellations that together cover the entire sky, so every star belongs to one region, like every town belongs to a country."],
    "why":"Constellations are the sky's address system and make it easy to find your way around.",
    "hook":"Orion's belt stars look side by side, but they are hundreds of light-years apart.",
    "terms":[["Constellation","One of 88 official sky regions, traditionally seen as a pattern of stars."],
             ["Asterism","A familiar star pattern that is not an official constellation, like the Big Dipper."]],
    "quiz":[mc("How many official constellations are there?",["12","50","88","100"],2,"There are 88 official constellations."),
            tf("Stars in a constellation are usually close together in space.",False,"They usually just line up from Earth's view.")]},
   {"id":"magnitude-brightness","title":"How Bright Is That Star?","level":"Core",
    "explain":["Astronomers measure star brightness on a scale called magnitude. Oddly, the scale runs backwards: the brighter an object, the smaller (or even negative) its magnitude number.",
               "A star can look bright because it truly shines fiercely, or simply because it is close. 'Apparent magnitude' is how bright it looks from Earth, while 'absolute magnitude' is how bright it would be at a standard distance."],
    "why":"Magnitude lets astronomers compare how bright objects look and how powerful they really are.",
    "hook":"On the magnitude scale, the brightest stars score below zero.",
    "terms":[["Magnitude","A number measuring brightness, where smaller means brighter."],
             ["Apparent magnitude","How bright an object looks from Earth, regardless of its true power."]],
    "quiz":[mc("On the magnitude scale, a brighter star has a:",["bigger number","smaller number","always negative number","letter grade"],1,"Smaller numbers mean brighter."),
            tf("A star can look bright just because it is close to us.",True,"True - nearness boosts apparent brightness.")]},
 ]),
 ("u-found-3","Light, Distance and Scale","The astonishing sizes of space","Core",[
   {"id":"speed-of-light","title":"The Speed of Light","level":"Core",
    "explain":["Light is the fastest thing in the universe, racing at about 300,000 kilometres every second. Nothing that carries energy or information can go faster.",
               "Even at that blistering speed, space is so vast that light from the Sun takes about eight minutes to reach us, and light from the next nearest star takes over four years."],
    "why":"The speed of light sets the cosmic speed limit and the clock for how we see the universe.",
    "hook":"Sunlight you feel right now left the Sun eight minutes ago.",
    "terms":[["Speed of light","The cosmic speed limit, about 300,000 km per second."],
             ["Light-year","The distance light travels in one year, about 9.5 trillion km."]],
    "quiz":[mc("About how long does sunlight take to reach Earth?",["1 second","8 minutes","1 hour","1 day"],1,"Roughly 8 minutes."),
            tf("Nothing can travel faster than light.",True,"True - it is the cosmic speed limit.")]},
   {"id":"light-years","title":"Measuring in Light-Years","level":"Core",
    "explain":["Distances in space are so huge that kilometres become useless. Instead astronomers use the light-year: the distance light travels in a year, nearly ten trillion kilometres.",
               "When we say a star is 100 light-years away, we are also saying its light took 100 years to reach us, so we see it as it was a century ago."],
    "why":"Light-years are the ruler astronomers use to measure the gaps between stars and galaxies.",
    "hook":"A light-year measures distance, not time, even though 'year' is hiding in the name.",
    "terms":[["Light-year","A unit of distance: how far light travels in one year."],
             ["Parsec","Another distance unit astronomers use, equal to about 3.26 light-years."]],
    "misconception":"A light-year is a distance, not an amount of time, even though the word 'year' makes it sound like a duration.",
    "quiz":[mc("A light-year is a measure of:",["time","distance","brightness","temperature"],1,"It measures distance."),
            tf("If a star is 100 light-years away, we see it as it was 100 years ago.",True,"True - its light is 100 years old.")]},
   {"id":"scale-of-solar-system","title":"The Scale of the Solar System","level":"Core",
    "explain":["The Solar System is mostly empty space. If the Sun were the size of a beach ball, Earth would be a peppercorn about 26 metres away, and tiny Pluto would be a pinhead a kilometre off.",
               "Astronomers measure these distances in 'astronomical units', where one unit is the average Earth-Sun distance. Neptune orbits about 30 of those units out."],
    "why":"Grasping the true scale shows why even our own planetary neighbourhood is mostly emptiness.",
    "hook":"Shrink the Sun to a beach ball and Earth becomes a peppercorn down the street.",
    "terms":[["Astronomical unit","The average distance from Earth to the Sun, about 150 million km."],
             ["Solar System","The Sun and everything bound to it by gravity."]],
    "quiz":[mc("One astronomical unit is the distance from:",["Earth to the Moon","Earth to the Sun","Sun to Pluto","star to star"],1,"It is the Earth-Sun distance."),
            tf("The Solar System is mostly empty space.",True,"True - the worlds are tiny compared to the gaps.")]},
   {"id":"scale-of-universe","title":"The Scale of the Universe","level":"Core",
    "explain":["Beyond the Solar System the scale grows almost beyond imagining. Our galaxy, the Milky Way, is about 100,000 light-years across and holds hundreds of billions of stars.",
               "Beyond it lie billions of other galaxies. The part of the universe we can see stretches tens of billions of light-years in every direction."],
    "why":"Seeing the full scale puts Earth in perspective: one world, around one star, in one of billions of galaxies.",
    "hook":"There are more stars in the universe than grains of sand on every beach on Earth.",
    "terms":[["Galaxy","A huge gravity-bound system of stars, gas and dust."],
             ["Observable universe","The part of the universe whose light has had time to reach us."]],
    "quiz":[mc("The Milky Way is roughly how wide?",["100 light-years","1,000 light-years","100,000 light-years","1 light-year"],2,"About 100,000 light-years."),
            tf("There are billions of galaxies beyond our own.",True,"True - the universe is full of galaxies.")]},
 ]),
 ("u-found-4","Gravity, the Great Sculptor","The force that shapes everything","Core",[
   {"id":"gravity-basics","title":"What Is Gravity?","level":"Foundations",
    "explain":["Gravity is the attraction between any two objects that have mass. The more mass an object has, and the closer you are, the stronger its pull.",
               "Gravity is gentle for small things but becomes mighty for huge ones. It holds you to the Earth, keeps the Moon circling us, and binds whole galaxies together."],
    "why":"Gravity is the master force that builds and runs almost everything in astronomy.",
    "hook":"The same force that drops an apple also steers entire galaxies.",
    "terms":[["Gravity","The attractive force between objects with mass."],
             ["Mass","The amount of matter in an object, which gives it gravity and weight."]],
    "quiz":[mc("Gravity gets stronger when an object has more:",["colour","mass","speed","age"],1,"More mass means more gravity."),
            tf("Gravity holds galaxies together as well as keeping us on the ground.",True,"True - it works on every scale.")]},
   {"id":"why-round","title":"Why Big Worlds Are Round","level":"Core",
    "explain":["Once an object grows large enough, its own gravity pulls equally from every direction toward its center, squashing it into a ball. That is why the Sun, planets and big moons are round.",
               "Small objects like asteroids and comet nuclei do not have enough gravity to overcome the strength of their rock, so they keep lumpy, potato-like shapes."],
    "why":"Roundness is a clue to size: it tells you an object's gravity won over its own strength.",
    "hook":"Gravity is a sculptor that only carves spheres once a world gets big enough.",
    "terms":[["Hydrostatic equilibrium","The balanced state in which gravity pulls a large body into a round shape."],
             ["Asteroid","A small rocky body, usually too little for gravity to make it round."]],
    "quiz":[mc("Large worlds are round because of their own:",["spin","gravity","heat","magnetism"],1,"Gravity pulls them into spheres."),
            tf("Most small asteroids are perfectly round.",False,"They are usually lumpy and irregular.")]},
 ]),
]

ORBITS = [
 ("u-orbit-1","Orbits and Why They Happen","Falling forever around a world","Foundations",[
   {"id":"what-is-orbit","title":"What Is an Orbit?","level":"Foundations",
    "explain":["An orbit is the curved path one object takes around another because of gravity. A moon orbits a planet, planets orbit the Sun, and the Sun orbits the center of the galaxy.",
               "An orbiting object is really falling toward the body it circles, but moving sideways so fast that it keeps missing. The result is an endless loop."],
    "why":"Orbits explain how everything from moons to galaxies stays in motion without crashing or flying away.",
    "hook":"To orbit the Earth is to fall toward it forever and always miss.",
    "terms":[["Orbit","The curved path an object follows around another under gravity."],
             ["Satellite","Any object that orbits a larger one, natural or human-made."]],
    "quiz":[mc("An object stays in orbit because it is:",["pushed by wind","falling but moving sideways fast","tied by a cable","floating with no forces"],1,"It falls while moving sideways."),
            tf("Planets orbit the Sun because of gravity.",True,"True - gravity holds them in their paths.")]},
   {"id":"orbital-shapes","title":"The Shapes of Orbits","level":"Core",
    "explain":["Orbits are not perfect circles but ellipses, gently stretched ovals. Sometimes a body is a little closer to what it orbits, and sometimes a little farther.",
               "A comet can have a very stretched orbit, racing close to the Sun then swinging far out for decades, while a planet's orbit is nearly circular."],
    "why":"The shape of an orbit explains why some worlds have steady years and others wild, looping journeys.",
    "hook":"Every orbit is an oval, even the ones that look like circles.",
    "terms":[["Ellipse","A stretched oval, the true shape of an orbit."],
             ["Eccentricity","A measure of how stretched or circular an orbit is."]],
    "quiz":[mc("The true shape of an orbit is a/an:",["circle","square","ellipse","triangle"],2,"Orbits are ellipses."),
            tf("Comets often have very stretched orbits.",True,"True - they swing close then far from the Sun.")]},
   {"id":"keplers-laws","title":"Kepler's Rules of Motion","level":"Core",
    "explain":["Four centuries ago Johannes Kepler discovered the rules that planets obey. He found their orbits are ellipses, and that a planet moves faster when it is closer to the Sun and slower when far away.",
               "He also found that planets farther from the Sun take much longer to go around. These patterns held for every planet and still guide spacecraft today."],
    "why":"Kepler's rules turned the wandering planets into a predictable, clockwork system.",
    "hook":"Planets speed up near the Sun and dawdle when they are far away, every single time.",
    "terms":[["Orbit","The path of one body around another."],
             ["Ellipse","The oval shape Kepler showed all orbits follow."]],
    "quiz":[mc("A planet moves fastest when it is:",["farthest from the Sun","closest to the Sun","at the top of its orbit","never changing speed"],1,"Closest to the Sun, it moves fastest."),
            tf("Planets farther from the Sun take longer to orbit.",True,"True - distant planets have long years.")]},
   {"id":"escape-velocity","title":"Escape Velocity","level":"Core",
    "explain":["To leave a world for good, you must go fast enough to outrun its gravity. That speed is called escape velocity, and it depends on how massive the world is.",
               "Earth's escape velocity is about 11 kilometres per second, which is why rockets must be so powerful. On the tiny Moon it is far lower."],
    "why":"Escape velocity is why launching from Earth is hard, and landing back on it must be done carefully.",
    "hook":"Beat 11 kilometres a second and Earth can never pull you back.",
    "terms":[["Escape velocity","The speed needed to break free of a world's gravity for good."],
             ["Thrust","The pushing force a rocket engine makes."]],
    "quiz":[mc("Escape velocity is higher for a world with more:",["colour","mass","moons","craters"],1,"More mass means a higher escape velocity."),
            tf("The Moon has a lower escape velocity than Earth.",True,"True - it is much less massive.")]},
 ]),
 ("u-orbit-2","Earth, Sun and Moon","The motions that rule our days","Foundations",[
   {"id":"day-and-night","title":"Day and Night","level":"Foundations",
    "explain":["Earth spins once about every 24 hours on an invisible line called its axis. The side facing the Sun has day; the side turned away has night.",
               "Because Earth turns from west to east, the Sun appears to rise in the east and set in the west, though the Sun itself is not really moving across our sky."],
    "why":"Earth's spin is the simple cause of the most basic rhythm in our lives.",
    "hook":"The Sun never rises; the horizon falls away as Earth turns toward it.",
    "terms":[["Axis","The imaginary line through a planet's poles that it spins around."],
             ["Rotation","The spinning of an object around its own axis."]],
    "quiz":[mc("Day and night happen because Earth:",["orbits the Sun","spins on its axis","wobbles","changes size"],1,"Earth's spin causes day and night."),
            tf("The Sun really moves across the sky each day.",False,"It only appears to; Earth is spinning.")]},
   {"id":"seasons","title":"Why We Have Seasons","level":"Core",
    "explain":["Earth's axis is tilted by about 23 degrees. As Earth orbits the Sun, this tilt means each hemisphere leans toward the Sun for part of the year and away for the rest.",
               "When your hemisphere tilts toward the Sun, days are longer and sunlight is more direct, giving summer. The seasons are not caused by Earth being closer to the Sun."],
    "why":"The tilt, not distance, explains why summer and winter happen at opposite times north and south.",
    "hook":"It is Earth's lean, not its distance from the Sun, that makes summer warm.",
    "terms":[["Axial tilt","The angle by which a planet's axis leans, about 23 degrees for Earth."],
             ["Hemisphere","One half of a planet, such as the northern or southern half."]],
    "misconception":"Seasons are not caused by Earth getting closer to or farther from the Sun; in fact Earth is closest to the Sun during northern winter.",
    "quiz":[mc("Seasons are caused mainly by Earth's:",["distance from the Sun","axial tilt","speed","spin rate"],1,"The axial tilt causes seasons."),
            tf("When it is summer in the north, it is winter in the south.",True,"True - the hemispheres tilt opposite ways.")]},
   {"id":"moon-phases","title":"The Phases of the Moon","level":"Foundations",
    "explain":["The Moon makes no light of its own; it shines by reflecting sunlight. As the Moon orbits Earth each month, we see different amounts of its lit half, giving the phases from new to full and back.",
               "A full Moon happens when the Moon is opposite the Sun in our sky, so we see its whole lit face. A new Moon sits near the Sun, its lit side turned away from us."],
    "why":"Phases are a monthly clock in the sky and a clear lesson in how sunlight lights up worlds.",
    "hook":"The Moon is always half lit; we just see that half from changing angles.",
    "terms":[["Phase","The shape of the Moon's lit part as seen from Earth."],
             ["Reflection","Light bouncing off a surface, as sunlight does off the Moon."]],
    "misconception":"Moon phases are not caused by Earth's shadow falling on the Moon; that is a lunar eclipse, which is different and rare.",
    "quiz":[mc("The Moon shines because it:",["burns like the Sun","reflects sunlight","glows on its own","is hit by lightning"],1,"It reflects sunlight."),
            tf("Moon phases are caused by Earth's shadow on the Moon.",False,"They come from the changing angle of sunlight, not Earth's shadow.")]},
   {"id":"tides","title":"The Tides","level":"Core",
    "explain":["The Moon's gravity pulls hardest on the side of Earth nearest it, and least on the far side. This stretching raises the oceans into two bulges, giving most coasts two high tides a day as Earth turns.",
               "The Sun adds a smaller tug. When Sun and Moon line up, tides are extra large 'spring tides'; when they pull at right angles, tides are gentler 'neap tides'."],
    "why":"Tides are the most visible sign on Earth of another world's gravity reaching across space.",
    "hook":"Twice a day the whole ocean rises, tugged by a world 384,000 kilometres away.",
    "terms":[["Tide","The regular rise and fall of the sea caused mainly by the Moon's gravity."],
             ["Spring tide","An unusually large tide when the Sun and Moon line up."]],
    "quiz":[mc("Ocean tides are caused mainly by the gravity of the:",["Sun only","Moon","other planets","wind"],1,"Mainly the Moon's gravity."),
            tf("Most coasts get two high tides each day.",True,"True - from the two ocean bulges.")]},
   {"id":"eclipses","title":"Eclipses","level":"Core",
    "explain":["An eclipse happens when one body's shadow falls on another. In a solar eclipse the Moon passes between Earth and the Sun, briefly blocking the Sun for people in the shadow's path.",
               "In a lunar eclipse the Earth passes between Sun and Moon, and the Moon slides into Earth's shadow, often glowing red. Eclipses are rare because the Moon's tilted orbit usually misses."],
    "why":"Eclipses are dramatic proof of how precisely the Sun, Earth and Moon line up and move.",
    "hook":"For a few minutes the Moon can blot out the Sun completely.",
    "terms":[["Solar eclipse","When the Moon blocks the Sun as seen from Earth."],
             ["Lunar eclipse","When the Moon passes into Earth's shadow."]],
    "misconception":"We do not get an eclipse every month because the Moon's orbit is tilted, so its shadow usually passes above or below the Sun or Earth.",
    "quiz":[mc("During a solar eclipse, what blocks the Sun?",["a cloud","the Moon","Earth's shadow","a planet"],1,"The Moon passes in front of the Sun."),
            tf("A lunar eclipse happens when the Moon enters Earth's shadow.",True,"True - Earth is between the Sun and Moon.")]},
   {"id":"why-no-eclipse-monthly","title":"Why Not an Eclipse Every Month?","level":"Core",
    "explain":["The Moon orbits Earth roughly once a month, so you might expect an eclipse at every new and full Moon. But the Moon's orbit is tilted about five degrees from Earth's orbit around the Sun.",
               "Because of that tilt, the Moon usually passes a little above or below the perfect line, and its shadow misses. Only when the alignment is just right do we get an eclipse."],
    "why":"This shows how a small tilt turns a monthly event into a rare and special one.",
    "hook":"A tilt of just five degrees is why eclipses are precious instead of routine.",
    "terms":[["Orbital tilt","The angle between the Moon's orbit and Earth's orbit around the Sun."],
             ["Alignment","When objects line up in a straight row."]],
    "quiz":[mc("We do not see an eclipse every month because the Moon's orbit is:",["too fast","tilted","too small","invisible"],1,"Its tilt makes the shadow usually miss."),
            tf("Eclipses need a very precise lining up of Sun, Earth and Moon.",True,"True - alignment must be nearly perfect.")]},
 ]),
]

SOLAR = [
 ("u-solar-1","Building the Solar System","How the Sun and planets were born","Core",[
   {"id":"solar-system-formation","title":"How the Solar System Formed","level":"Core",
    "explain":["About 4.6 billion years ago, a giant cloud of gas and dust collapsed under its own gravity. Most of it gathered in the center and became the Sun, while the leftovers settled into a spinning disk.",
               "Within that disk, dust grains stuck together into ever-larger lumps, which grew into the planets, moons, asteroids and comets we see today."],
    "why":"The Solar System's birth story explains why the planets all orbit the same way in nearly the same plane.",
    "hook":"Everything in the Solar System was built from the same swirling cloud.",
    "terms":[["Nebula","A cloud of gas and dust in space, sometimes the birthplace of stars."],
             ["Protoplanetary disk","The spinning disk of gas and dust around a young star where planets form."]],
    "quiz":[mc("The Solar System formed from a collapsing cloud of:",["water","gas and dust","metal","ice cream"],1,"Gas and dust collapsed under gravity."),
            tf("The Sun and planets formed from the same cloud.",True,"True - they share one origin.")]},
   {"id":"rocky-vs-gas","title":"Rocky Worlds and Giant Worlds","level":"Core",
    "explain":["The four inner planets, Mercury, Venus, Earth and Mars, are small and made mostly of rock and metal. They formed where the young Sun's heat allowed only solid materials to survive close in.",
               "Farther out, where it was cold enough for ice, planets grew huge and gathered thick atmospheres of gas. These are the giants: Jupiter, Saturn, Uranus and Neptune."],
    "why":"This split explains why the planets fall into two very different families.",
    "hook":"Near the Sun, worlds are small and stony; far out, they are giant and gassy.",
    "terms":[["Terrestrial planet","A small, rocky planet like Earth or Mars."],
             ["Gas giant","A huge planet made mostly of gas, like Jupiter or Saturn."]],
    "quiz":[mc("The inner planets are made mostly of:",["gas","rock and metal","ice","cloud"],1,"They are rocky and metallic."),
            tf("The giant planets formed in the colder, outer Solar System.",True,"True - cold let them grow huge.")]},
   {"id":"asteroid-belt-concept","title":"The Asteroid Belt","level":"Core",
    "explain":["Between Mars and Jupiter lies a ring of rocky leftovers called the asteroid belt. These are pieces that never came together into a planet, partly because Jupiter's strong gravity kept stirring them up.",
               "Despite films showing crowded fields of rocks, the belt is mostly empty; the asteroids are spread across a huge volume of space."],
    "why":"The belt is a frozen record of the building blocks that made the planets.",
    "hook":"The asteroid belt is a planet that never managed to form.",
    "terms":[["Asteroid belt","The ring of rocky bodies orbiting between Mars and Jupiter."],
             ["Asteroid","A small rocky body left over from planet formation."]],
    "misconception":"The asteroid belt is not a thick, crowded field; spacecraft fly through it easily because the rocks are far apart.",
    "quiz":[mc("The asteroid belt lies between Mars and:",["Earth","Jupiter","Saturn","the Sun"],1,"It sits between Mars and Jupiter."),
            tf("The asteroid belt is densely packed with rocks close together.",False,"It is mostly empty space.")]},
 ]),
 ("u-solar-2","Our Star, the Sun","The engine at the center","Core",[
   {"id":"sun-basics","title":"The Sun Up Close","level":"Foundations",
    "explain":["The Sun is an ordinary star, a vast ball of glowing gas so large that more than a million Earths could fit inside. It is by far the most massive thing in the Solar System.",
               "Its surface seethes at about 5,500 degrees Celsius, and its light and heat make life on Earth possible."],
    "why":"The Sun is our nearest star and the source of nearly all energy on Earth.",
    "hook":"Our 'average' star could swallow a million Earths.",
    "terms":[["Star","A glowing ball of gas powered by nuclear fusion."],
             ["Photosphere","The visible surface of the Sun."]],
    "quiz":[mc("The Sun is a:",["planet","star","comet","moon"],1,"The Sun is a star."),
            tf("Over a million Earths could fit inside the Sun.",True,"True - it is enormous.")]},
   {"id":"nuclear-fusion","title":"How the Sun Shines","level":"Core",
    "explain":["Deep in the Sun's core, immense pressure and heat force hydrogen atoms to fuse into helium. This nuclear fusion releases a flood of energy that slowly works its way out and streams into space as sunlight.",
               "The Sun has been shining this way for about 4.6 billion years and has enough fuel to keep going for roughly 5 billion more."],
    "why":"Fusion is the power source of the Sun and every star, lighting up the whole universe.",
    "hook":"The Sun turns four million tonnes of itself into pure energy every second.",
    "terms":[["Nuclear fusion","Joining light atoms into heavier ones, releasing energy."],
             ["Core","The hot, dense center of a star where fusion happens."]],
    "quiz":[mc("The Sun makes its energy by fusing hydrogen into:",["oxygen","helium","iron","carbon"],1,"Hydrogen fuses into helium."),
            tf("The Sun's energy comes from nuclear fusion in its core.",True,"True - fusion powers the Sun.")]},
   {"id":"solar-activity","title":"Sunspots and Solar Storms","level":"Core",
    "explain":["The Sun is not calm. Dark, cooler patches called sunspots come and go, and the Sun can hurl out bursts of radiation and clouds of particles called solar flares and coronal mass ejections.",
               "When this 'space weather' reaches Earth, it can disturb satellites and power grids, and it lights up the polar skies with auroras."],
    "why":"Solar activity connects the Sun directly to technology and beautiful light shows on Earth.",
    "hook":"A storm on the Sun can paint the night sky green over the Earth.",
    "terms":[["Sunspot","A cooler, darker patch on the Sun's surface."],
             ["Aurora","Glowing lights near the poles caused by particles from the Sun."]],
    "quiz":[mc("Sunspots appear darker because they are:",["holes","cooler than nearby areas","made of dust","very far away"],1,"They are cooler than their surroundings."),
            tf("Activity on the Sun can cause auroras on Earth.",True,"True - solar particles spark auroras.")]},
 ]),
 ("u-solar-3","Worlds and Their Features","Atmospheres, rings and moons","Core",[
   {"id":"atmospheres","title":"Planetary Atmospheres","level":"Core",
    "explain":["An atmosphere is the blanket of gases held around a world by its gravity. Earth's is mostly nitrogen and oxygen, Venus has a crushing carbon-dioxide blanket, and Mars has only a thin wisp left.",
               "Atmospheres trap heat, shape weather, and on Earth protect life from harmful radiation and most incoming space rocks."],
    "why":"A world's atmosphere decides its weather, its temperature, and whether it could support life.",
    "hook":"The same gas that makes soda fizzy makes Venus the hottest planet.",
    "terms":[["Atmosphere","The layer of gases held around a world by gravity."],
             ["Greenhouse effect","Warming caused when atmospheric gases trap heat."]],
    "quiz":[mc("A thick carbon-dioxide atmosphere makes which planet so hot?",["Mars","Venus","Mercury","Neptune"],1,"Venus, through a runaway greenhouse effect."),
            tf("A planet's gravity holds its atmosphere in place.",True,"True - without enough gravity, gases escape.")]},
   {"id":"planetary-rings","title":"Rings Around Worlds","level":"Core",
    "explain":["Saturn is famous for its dazzling rings, made of countless chunks of ice and rock orbiting the planet. Each chunk follows its own little orbit, from grains to house-sized boulders.",
               "Jupiter, Uranus and Neptune have fainter rings too. Rings may form when a moon is shattered or when material never gathers into one."],
    "why":"Rings are stunning natural laboratories showing orbits and gravity in action.",
    "hook":"Saturn's rings are billions of tiny moons, each on its own orbit.",
    "terms":[["Ring system","A disk of orbiting ice and rock around a planet."],
             ["Orbit","The path each ring particle follows around the planet."]],
    "quiz":[mc("Saturn's rings are made of:",["solid metal","ice and rock chunks","gas","one big sheet"],1,"Countless chunks of ice and rock."),
            tf("Only Saturn has rings.",False,"All four giant planets have rings; Saturn's are just brightest.")]},
   {"id":"what-is-moon-concept","title":"What Makes a Moon","level":"Foundations",
    "explain":["A moon is any natural object that orbits a planet, dwarf planet or asteroid, rather than orbiting the Sun directly. Earth has one; Jupiter and Saturn have dozens each.",
               "Moons come in huge variety: some are bigger than the planet Mercury, others are tiny captured asteroids. Some hide oceans beneath icy shells."],
    "why":"Moons are worlds in their own right and some of the best places to search for life.",
    "hook":"Some moons are bigger than planets, and some may hide oceans.",
    "terms":[["Moon","A natural object that orbits a planet or smaller body."],
             ["Natural satellite","Another name for a moon."]],
    "quiz":[mc("A moon orbits a:",["the Sun directly","planet or smaller body","galaxy","star cluster"],1,"It orbits a planet or other body, not the Sun directly."),
            tf("Some moons are larger than the planet Mercury.",True,"True - Ganymede and Titan both are.")]},
 ]),
]
