# -*- coding: utf-8 -*-
# Concept lessons part 2 of 2: stars, galaxies, cosmology, missions, skywatching.

def mc(q, choices, answer, why):
    return {"type":"mc","q":q,"choices":choices,"answer":answer,"why":why}
def tf(q, answer, why):
    return {"type":"tf","q":q,"answer":answer,"why":why}

STARS = [
 ("u-star-1","What Stars Are","The glowing engines of the universe","Core",[
   {"id":"what-is-star","title":"What Is a Star?","level":"Foundations",
    "explain":["A star is an enormous ball of hot gas, mostly hydrogen, held together by its own gravity and shining because of nuclear fusion in its core. The Sun is the nearest example.",
               "Stars look like tiny points only because they are so far away. The next nearest star beyond the Sun is over four light-years off."],
    "why":"Stars are the building blocks of galaxies and the factories that make most chemical elements.",
    "hook":"Every star you see is a distant sun, many far bigger than our own.",
    "terms":[["Star","A ball of hot gas that shines by nuclear fusion."],
             ["Fusion","Joining light atoms into heavier ones to release energy."]],
    "quiz":[mc("A star shines because of:",["burning wood","nuclear fusion","reflected light","electricity"],1,"Fusion in its core makes it shine."),
            tf("The Sun is a star.",True,"True - it is our nearest star.")]},
   {"id":"star-colors-temp","title":"Star Colours and Heat","level":"Core",
    "explain":["A star's colour reveals its temperature. The hottest stars glow blue-white, medium stars like the Sun shine yellow, and the coolest stars burn red.",
               "This is the opposite of how we usually think of 'hot' and 'cold' colours; in space, blue is hotter than red."],
    "why":"Colour is a quick clue astronomers use to read a star's temperature from light alone.",
    "hook":"In the sky, blue stars are the hot ones and red stars are the cool ones.",
    "terms":[["Temperature","How hot something is; for stars it sets their colour."],
             ["Spectrum","The band of colours that light can be split into."]],
    "misconception":"Red stars are cooler than blue stars, even though on Earth we often link red with heat.",
    "quiz":[mc("Which colour star is hottest?",["red","yellow","blue-white","orange"],2,"Blue-white stars are hottest."),
            tf("Our yellow Sun is hotter at its surface than a blue-white star.",False,"Blue-white stars are hotter than the Sun.")]},
   {"id":"star-sizes","title":"Dwarfs, Giants and Supergiants","level":"Core",
    "explain":["Stars come in wildly different sizes. Most, like the Sun, are modest 'dwarf' stars. Others swell into giants and supergiants hundreds or thousands of times wider.",
               "If a supergiant like Betelgeuse replaced the Sun, it would swallow the orbits of the inner planets. Tiny white dwarfs, by contrast, pack a star's mass into an Earth-sized ball."],
    "why":"Size is a major clue to a star's age and its eventual fate.",
    "hook":"Some single stars are wider than the entire orbit of Mars.",
    "terms":[["Giant star","A star that has swelled far larger than the Sun."],
             ["White dwarf","The small, dense, fading core left when a Sun-like star dies."]],
    "quiz":[mc("Most stars, like the Sun, are:",["supergiants","modest dwarf stars","white dwarfs","black holes"],1,"Most are modest main-sequence dwarf stars."),
            tf("A supergiant star can be larger than the orbit of a planet.",True,"True - they are immense.")]},
 ]),
 ("u-star-2","The Lives of Stars","Birth, change and death","Core",[
   {"id":"star-birth","title":"How Stars Are Born","level":"Core",
    "explain":["Stars are born inside cold clouds of gas and dust called nebulae. When part of a cloud is squeezed, gravity pulls it tighter and tighter until the center grows hot and dense.",
               "Once the core becomes hot enough, fusion ignites and a new star begins to shine, blowing away the leftover gas around it."],
    "why":"Star birth is the first chapter of a story that ends in the elements making up our world.",
    "hook":"Stars are born in vast cosmic nurseries thousands of light-years wide.",
    "terms":[["Nebula","A cloud of gas and dust where stars can form."],
             ["Protostar","A forming star not yet hot enough for fusion."]],
    "quiz":[mc("Stars are born inside clouds called:",["galaxies","nebulae","craters","comets"],1,"Nebulae are stellar nurseries."),
            tf("A star begins to shine once fusion starts in its core.",True,"True - fusion lights the new star.")]},
   {"id":"main-sequence","title":"A Star's Long Middle Age","level":"Core",
    "explain":["For most of its life a star steadily fuses hydrogen into helium in its core, a stable stage astronomers call the main sequence. The Sun is about halfway through this calm phase.",
               "How long this lasts depends on mass. Lightweight stars sip their fuel and last for many billions of years, while massive stars burn furiously and live only millions."],
    "why":"The main sequence is where stars spend most of their lives, including our Sun right now.",
    "hook":"The biggest stars live fast and die young; the smallest may outlast the universe so far.",
    "terms":[["Main sequence","The long, stable stage when a star fuses hydrogen in its core."],
             ["Mass","The amount of matter in a star, which sets how it lives and dies."]],
    "quiz":[mc("During the main sequence, a star fuses hydrogen into:",["iron","helium","gold","oxygen"],1,"Hydrogen fuses into helium."),
            tf("Massive stars live longer than small ones.",False,"Massive stars burn out far faster.")]},
   {"id":"star-death-small","title":"How Sun-Like Stars Die","level":"Core",
    "explain":["When a Sun-like star runs low on fuel, it swells into a red giant, then gently puffs its outer layers into space as a glowing shell called a planetary nebula.",
               "All that remains is the hot, dense core, a white dwarf, which slowly cools and fades over billions of years."],
    "why":"This is the future of our own Sun, and it scatters new elements into space.",
    "hook":"In its final act, a star like the Sun blows a glowing smoke ring across the sky.",
    "terms":[["Red giant","A dying Sun-like star that has swelled enormously."],
             ["Planetary nebula","The glowing shell of gas shed by a dying Sun-like star."]],
    "misconception":"A 'planetary nebula' has nothing to do with planets; early astronomers just thought the round glow looked planet-like.",
    "quiz":[mc("A Sun-like star ends as a:",["black hole","white dwarf","blue giant","quasar"],1,"It leaves behind a white dwarf."),
            tf("The Sun will one day become a red giant.",True,"True - that is its expected fate.")]},
   {"id":"supernova-concept","title":"Supernovae: When Giants Die","level":"Core",
    "explain":["A massive star ends far more violently. When its core runs out of fuel, it collapses in an instant and rebounds in a titanic explosion called a supernova, briefly outshining a whole galaxy.",
               "Supernovae forge and scatter heavy elements like iron and gold. The atoms in your blood and a gold ring were made in such explosions."],
    "why":"Supernovae seed the universe with the elements that make planets and people possible.",
    "hook":"The iron in your blood was forged in an exploding star.",
    "terms":[["Supernova","The explosive death of a massive star."],
             ["Element","A basic kind of atom, like iron or oxygen, many made in stars."]],
    "quiz":[mc("A supernova is the:",["birth of a planet","explosive death of a massive star","calm phase of the Sun","glow of a comet"],1,"It is a massive star's explosive death."),
            tf("Heavy elements like gold are made in supernova explosions.",True,"True - explosions forge heavy elements.")]},
   {"id":"neutron-stars-blackholes","title":"Neutron Stars and Black Holes","level":"Core",
    "explain":["After a supernova, the crushed core may survive as a neutron star, so dense that a sugar-cube of it would weigh as much as a mountain. Spinning ones sweep beams past us as pulsars.",
               "If the dying star is heavy enough, the core collapses completely into a black hole, a place where gravity is so strong that not even light can escape."],
    "why":"These extreme leftovers are nature's densest objects and test the limits of physics.",
    "hook":"A spoonful of neutron star would outweigh a mountain.",
    "terms":[["Neutron star","An incredibly dense stellar core left after a supernova."],
             ["Black hole","A region whose gravity lets nothing, not even light, escape."]],
    "quiz":[mc("The most massive dying stars can collapse into a:",["white dwarf","black hole","red giant","comet"],1,"They form black holes."),
            tf("A pulsar is a spinning neutron star.",True,"True - pulsars are spinning neutron stars.")]},
 ]),
]

GALAXIES = [
 ("u-gal-1","Galaxies","Cities of stars","Core",[
   {"id":"what-is-galaxy","title":"What Is a Galaxy?","level":"Foundations",
    "explain":["A galaxy is a vast collection of stars, gas, dust and dark matter held together by gravity. They range from dwarf galaxies of a few million stars to giants of a trillion.",
               "Our Sun is just one of several hundred billion stars in our galaxy, the Milky Way, and there are billions of other galaxies beyond it."],
    "why":"Galaxies are the basic building blocks of the universe's large-scale structure.",
    "hook":"Our Sun is one star among hundreds of billions in just one galaxy.",
    "terms":[["Galaxy","A huge gravity-bound system of stars, gas, dust and dark matter."],
             ["Dark matter","Invisible matter whose gravity helps hold galaxies together."]],
    "quiz":[mc("Our galaxy is called the:",["Solar System","Milky Way","Andromeda","Local Group"],1,"We live in the Milky Way."),
            tf("There are billions of galaxies in the universe.",True,"True - galaxies are everywhere.")]},
   {"id":"galaxy-types","title":"Shapes of Galaxies","level":"Core",
    "explain":["Galaxies come in a few main shapes. Spirals, like the Milky Way, have graceful arms winding around a bright center. Ellipticals are smooth balls or eggs of older stars.",
               "Irregular galaxies have no clear shape, often because a collision has scrambled them. Sorting galaxies by shape was one of astronomy's first great organising ideas."],
    "why":"A galaxy's shape hints at its history, its age and its store of star-forming gas.",
    "hook":"Galaxies come as pinwheels, eggs and shapeless smudges.",
    "terms":[["Spiral galaxy","A galaxy with arms winding out from a central bulge."],
             ["Elliptical galaxy","A smooth, rounded galaxy of mostly older stars."]],
    "quiz":[mc("The Milky Way is which type of galaxy?",["elliptical","spiral","irregular","ring"],1,"It is a spiral galaxy."),
            tf("Irregular galaxies have no clear shape.",True,"True - often due to collisions.")]},
   {"id":"milky-way-concept","title":"Our Home, the Milky Way","level":"Core",
    "explain":["The Milky Way is a barred spiral galaxy about 100,000 light-years wide. Our Sun lies far out in one of its arms, circling the center once every 230 million years or so.",
               "On a dark night, looking along the disk of our own galaxy, we see its combined starlight as a faint glowing band arching across the sky."],
    "why":"Understanding the Milky Way is understanding our own cosmic neighbourhood and address.",
    "hook":"That misty band across a dark sky is the inside of our own galaxy.",
    "terms":[["Milky Way","The barred spiral galaxy that contains our Solar System."],
             ["Galactic center","The crowded core of the galaxy, home to a giant black hole."]],
    "quiz":[mc("The glowing band of the Milky Way in our sky is:",["a cloud","light from our galaxy's stars","the zodiac","a comet trail"],1,"It is the combined light of our galaxy's stars."),
            tf("The Sun sits at the exact center of the Milky Way.",False,"The Sun lies far out in a spiral arm.")]},
 ]),
 ("u-gal-2","Between and Beyond the Stars","Nebulae, clusters and groups","Core",[
   {"id":"nebula-types","title":"Kinds of Nebulae","level":"Core",
    "explain":["A nebula is a cloud of gas and dust in space. Some glow as stars are born inside them, some shine by reflecting nearby starlight, and dark nebulae simply block the light behind them.",
               "Others, like planetary nebulae and supernova remnants, are gas thrown off by dying stars. Nebulae are both the cradles and the graveyards of stars."],
    "why":"Nebulae are where the cycle of star birth and death plays out in plain view.",
    "hook":"The same kind of cloud can be a stellar nursery or a stellar tombstone.",
    "terms":[["Nebula","A cloud of gas and dust in space."],
             ["Supernova remnant","The expanding cloud left by an exploded star."]],
    "quiz":[mc("A dark nebula is visible because it:",["glows brightly","blocks the light behind it","reflects the Sun","spins fast"],1,"It blots out background light."),
            tf("Nebulae can be both birthplaces and remains of stars.",True,"True - they mark birth and death.")]},
   {"id":"star-clusters-concept","title":"Star Clusters","level":"Core",
    "explain":["Stars are often born in groups, and many stay loosely together as clusters. Open clusters are young, scattered families of a few hundred stars, like the Pleiades.",
               "Globular clusters are ancient, tightly packed balls of hundreds of thousands of stars that orbit the outskirts of galaxies."],
    "why":"Clusters let astronomers study many stars of the same age and birthplace at once.",
    "hook":"A globular cluster can pack a million suns into a ball.",
    "terms":[["Open cluster","A young, loose group of stars born together."],
             ["Globular cluster","An ancient, dense ball of hundreds of thousands of stars."]],
    "quiz":[mc("Which cluster type is old and tightly packed?",["open cluster","globular cluster","asteroid cluster","comet cluster"],1,"Globular clusters are old and dense."),
            tf("The stars in a cluster were born together.",True,"True - they share a birthplace.")]},
   {"id":"local-group","title":"Galaxies in Groups","level":"Core",
    "explain":["Galaxies are not scattered evenly; gravity gathers them into groups and clusters. Our Milky Way belongs to a small gathering called the Local Group, along with the Andromeda Galaxy and dozens of smaller ones.",
               "On the largest scale, these groups link into vast filaments and walls, with great empty voids between, forming a 'cosmic web'."],
    "why":"Seeing how galaxies cluster reveals the largest structures in the entire universe.",
    "hook":"Galaxies gather into a web that spans the whole universe.",
    "terms":[["Local Group","The small cluster of galaxies that includes the Milky Way."],
             ["Cosmic web","The vast network of galaxy filaments and voids across the universe."]],
    "quiz":[mc("The Milky Way belongs to a galaxy group called the:",["Solar System","Local Group","Oort Cloud","Kuiper Belt"],1,"The Local Group."),
            tf("Galaxies are spread perfectly evenly through space.",False,"They gather into groups, clusters and a cosmic web.")]},
 ]),
]

COSMOLOGY = [
 ("u-cosmos-1","The Universe as a Whole","Its birth, growth and contents","Core",[
   {"id":"big-bang","title":"The Big Bang","level":"Core",
    "explain":["The leading scientific story of the universe's beginning is the Big Bang. Around 13.8 billion years ago, the entire universe was unimaginably hot and dense, then began expanding and cooling.",
               "As it cooled, the first atoms, stars and galaxies formed over millions and billions of years. The Big Bang was not an explosion in space, but an expansion of space itself."],
    "why":"The Big Bang is the foundation of modern cosmology and our best account of cosmic history.",
    "hook":"Everything, everywhere, began about 13.8 billion years ago.",
    "terms":[["Big Bang","The theory that the universe began hot and dense and has expanded ever since."],
             ["Cosmology","The study of the universe as a whole, its origin and fate."]],
    "misconception":"The Big Bang was not an explosion that flung matter into empty space; space itself began expanding everywhere at once.",
    "quiz":[mc("About how old is the universe?",["6,000 years","13.8 billion years","1 million years","100 billion years"],1,"About 13.8 billion years."),
            tf("The Big Bang was an explosion at one point in already-existing space.",False,"It was an expansion of space itself, everywhere at once.")]},
   {"id":"expanding-universe","title":"The Expanding Universe","level":"Core",
    "explain":["Nearly a century ago, astronomers discovered that distant galaxies are rushing away from us, and the farther a galaxy is, the faster it recedes. This showed that the whole universe is expanding.",
               "Picture raisins in rising bread dough: as the dough swells, every raisin moves away from every other. Galaxies are like the raisins, carried apart as space stretches."],
    "why":"Cosmic expansion is the key evidence behind the Big Bang and the future of the universe.",
    "hook":"Almost every galaxy is racing away from us as space itself stretches.",
    "terms":[["Expansion","The stretching of space that carries galaxies apart."],
             ["Redshift","The reddening of light from objects moving away from us."]],
    "quiz":[mc("Distant galaxies are mostly:",["coming toward us","moving away from us","standing still","spinning in place"],1,"They are receding as space expands."),
            tf("The farther a galaxy is, the faster it moves away.",True,"True - this revealed the expansion.")]},
   {"id":"cmb","title":"The Afterglow of the Big Bang","level":"Core",
    "explain":["The Big Bang left a faint glow that still fills all of space, called the cosmic microwave background. It is the cooled-down light from when the young universe first became clear, about 380,000 years after the start.",
               "This afterglow was found by accident in 1964 and is one of the strongest pieces of evidence that the Big Bang really happened."],
    "why":"This ancient light is a direct snapshot of the infant universe and a pillar of cosmology.",
    "hook":"A faint hiss of ancient light fills every corner of space, even tonight.",
    "terms":[["Cosmic microwave background","Faint leftover radiation from the early universe."],
             ["Evidence","Observations that test whether an idea is true."]],
    "quiz":[mc("The cosmic microwave background is:",["light from the Sun","leftover glow from the early universe","a kind of star","a galaxy"],1,"It is the Big Bang's afterglow."),
            tf("The cosmic microwave background supports the Big Bang theory.",True,"True - it is key evidence.")]},
 ]),
 ("u-cosmos-2","The Dark and the Strange","Hidden matter and extreme objects","Core",[
   {"id":"dark-matter","title":"Dark Matter","level":"Core",
    "explain":["Galaxies spin so fast that their visible stars alone do not have enough gravity to hold them together. Something unseen must be adding extra pull. Astronomers call this mysterious stuff dark matter.",
               "Dark matter gives off no light, so we detect it only by its gravity. It seems to make up far more of the universe than all the ordinary matter we can see."],
    "why":"Dark matter is one of the biggest unsolved mysteries in all of science.",
    "hook":"Most of the universe's matter is invisible, and no one yet knows what it is.",
    "terms":[["Dark matter","Invisible matter detected only through its gravity."],
             ["Gravity","The force whose strength reveals hidden mass."]],
    "quiz":[mc("We know dark matter exists because of its:",["colour","gravity","sound","smell"],1,"We detect it by its gravity."),
            tf("Dark matter gives off lots of visible light.",False,"It gives off no light we can see.")]},
   {"id":"dark-energy","title":"Dark Energy","level":"Core",
    "explain":["In the 1990s astronomers found a shock: the universe's expansion is not slowing down as expected, but speeding up. The unknown cause was named dark energy.",
               "Dark energy seems to be a property of space itself, pushing the universe to expand ever faster. It appears to make up most of the energy in the cosmos."],
    "why":"Dark energy shapes the ultimate fate of the universe, and remains deeply mysterious.",
    "hook":"The universe is not just expanding; it is expanding faster every day.",
    "terms":[["Dark energy","An unknown influence causing the universe's expansion to speed up."],
             ["Accelerating universe","The discovery that cosmic expansion is getting faster."]],
    "quiz":[mc("Dark energy seems to make the universe's expansion:",["slow down","speed up","stop","reverse"],1,"It speeds the expansion up."),
            tf("Dark energy is fully understood by scientists.",False,"It remains one of the great mysteries.")]},
   {"id":"black-holes-deep","title":"Black Holes Up Close","level":"Core",
    "explain":["A black hole is a region where matter is crushed so tightly that its gravity lets nothing escape, not even light. Its edge of no return is called the event horizon.",
               "Black holes form when massive stars die, and giant ones sit at the centers of galaxies. In 2019 astronomers captured the first image of one, seeing its dark shadow against glowing gas."],
    "why":"Black holes are nature's most extreme objects and key to how galaxies grow.",
    "hook":"At a black hole's edge, even light gives up trying to escape.",
    "terms":[["Event horizon","The boundary of a black hole, past which nothing returns."],
             ["Supermassive black hole","A giant black hole at the center of a galaxy."]],
    "misconception":"Black holes do not roam space hoovering up everything; from a safe distance their gravity behaves like that of any object with the same mass.",
    "quiz":[mc("The point of no return around a black hole is the:",["core","event horizon","corona","halo"],1,"It is called the event horizon."),
            tf("Even light cannot escape from within a black hole.",True,"True - that is what makes it black.")]},
   {"id":"are-we-alone","title":"Are We Alone?","level":"Core",
    "explain":["With billions of stars hosting planets, many scientists think life could exist elsewhere. Astronomers search for habitable worlds and even listen for radio signals from possible civilisations.",
               "So far we have found no proof of life beyond Earth. The honest answer is that we do not yet know, which is exactly why the search is so exciting."],
    "why":"The search for life beyond Earth is one of the deepest questions astronomy can ask.",
    "hook":"Billions of worlds are out there; we have explored almost none of them.",
    "terms":[["Habitable zone","The region around a star where liquid water could exist."],
             ["Exoplanet","A planet orbiting a star other than the Sun."]],
    "quiz":[mc("So far, life beyond Earth has been:",["proven on Mars","not yet found","found on the Moon","found on the Sun"],1,"No life beyond Earth has been confirmed yet."),
            tf("A habitable zone is where liquid water could exist on a planet.",True,"True - it is the 'just right' zone.")]},
 ]),
]

MISSIONS = [
 ("u-mission-1","Reaching Space","Rockets and how we get there","Core",[
   {"id":"how-rockets-work","title":"How Rockets Work","level":"Core",
    "explain":["A rocket flies by throwing mass out the back at high speed. As the hot gas rushes downward, the rocket is pushed upward, following the rule that every action has an equal and opposite reaction.",
               "Unlike a jet, a rocket carries its own oxygen, so it can work in the vacuum of space where there is no air to burn fuel with."],
    "why":"Rockets are the only machines that can carry us beyond Earth's atmosphere.",
    "hook":"A rocket flies by throwing part of itself away, very fast.",
    "terms":[["Thrust","The forward push a rocket gets from its exhaust."],
             ["Reaction","The equal and opposite push that drives a rocket forward."]],
    "quiz":[mc("A rocket moves forward by pushing gas:",["forward","backward","sideways","upward only"],1,"Gas goes back, so the rocket goes forward."),
            tf("A rocket can work in space because it carries its own oxygen.",True,"True - no outside air is needed.")]},
   {"id":"getting-to-orbit","title":"Getting to Orbit","level":"Core",
    "explain":["Reaching space is not just about going up; it is mostly about going sideways very fast. To orbit, a spacecraft must travel about eight kilometres every second so it keeps falling around the Earth.",
               "That is why rockets tip over and accelerate sideways soon after launch, building the enormous speed an orbit requires."],
    "why":"Understanding orbit explains why spaceflight is about speed as much as height.",
    "hook":"Reaching orbit is less about going up than about going sideways fast enough.",
    "terms":[["Orbital velocity","The sideways speed needed to stay in orbit."],
             ["Low Earth orbit","The region just above the atmosphere where many satellites fly."]],
    "quiz":[mc("To reach orbit, a spacecraft mainly needs huge:",["height","sideways speed","weight","colour"],1,"It needs great sideways speed."),
            tf("Satellites in orbit are constantly falling around the Earth.",True,"True - orbit is continuous falling.")]},
   {"id":"gravity-assist","title":"Slingshots Around Planets","level":"Core",
    "explain":["To reach the distant planets, spacecraft borrow speed from worlds they pass. By swinging close to a planet, a probe is flung onward faster, like a ball whipped around on a string.",
               "This 'gravity assist' saved the Voyager probes years of travel and let them tour all four giant planets."],
    "why":"Gravity assists make far-off missions possible without impossibly large rockets.",
    "hook":"Spacecraft steal a little speed from planets to reach the outer Solar System.",
    "terms":[["Gravity assist","Using a planet's gravity to speed up or steer a spacecraft."],
             ["Flyby","Passing close to a world without landing or orbiting."]],
    "quiz":[mc("A gravity assist uses a planet's gravity to:",["slow a probe only","change a probe's speed and path","land a probe","light a probe"],1,"It changes the probe's speed and direction."),
            tf("Gravity assists helped Voyager visit the giant planets.",True,"True - they borrowed speed from planets.")]},
 ]),
 ("u-mission-2","Eyes on the Universe","Telescopes and exploration","Core",[
   {"id":"how-telescopes-work","title":"How Telescopes Work","level":"Foundations",
    "explain":["A telescope's main job is to gather light. A large lens or mirror collects far more light than your eye can, making faint objects visible and revealing fine detail.",
               "The bigger the mirror, the more it can see. That is why major observatories build mirrors many metres across."],
    "why":"Telescopes are the central tool of astronomy, extending our sight across the universe.",
    "hook":"A telescope is really a giant light bucket.",
    "terms":[["Telescope","An instrument that gathers light to reveal distant objects."],
             ["Aperture","The width of a telescope's main lens or mirror."]],
    "quiz":[mc("A telescope's main job is to gather:",["heat","light","sound","wind"],1,"It gathers light."),
            tf("A bigger mirror lets a telescope see fainter objects.",True,"True - more light means more reach.")]},
   {"id":"invisible-light","title":"Seeing Invisible Light","level":"Core",
    "explain":["Visible light is only a sliver of all the light in the universe. Objects also shine in radio waves, infrared, ultraviolet, X-rays and gamma rays, which our eyes cannot see.",
               "Special telescopes capture these hidden kinds of light, revealing things like cool dust, hot gas around black holes, and the afterglow of the Big Bang."],
    "why":"Looking beyond visible light unveils a universe invisible to the human eye.",
    "hook":"Most of the universe shines in colours your eyes can never see.",
    "terms":[["Electromagnetic spectrum","The full range of light, from radio waves to gamma rays."],
             ["Infrared","Light just beyond red that we feel as heat."]],
    "quiz":[mc("Visible light is only a small part of the:",["Solar System","electromagnetic spectrum","Milky Way","atmosphere"],1,"It is a sliver of the full spectrum."),
            tf("Some telescopes detect X-rays and radio waves from space.",True,"True - they reveal hidden light.")]},
   {"id":"why-space-telescopes","title":"Why Put Telescopes in Space?","level":"Core",
    "explain":["Earth's atmosphere blurs starlight, which is why stars twinkle, and it blocks many kinds of light entirely. Telescopes in orbit rise above this haze for a perfectly clear view.",
               "Space telescopes like Hubble and the James Webb can see sharper detail and catch infrared and ultraviolet light that never reaches the ground."],
    "why":"Space telescopes give our clearest, deepest views of the cosmos.",
    "hook":"Above the air, the stars stop twinkling and snap into focus.",
    "terms":[["Atmosphere","The air around Earth that blurs and blocks starlight."],
             ["Space telescope","A telescope placed in orbit for a clearer view."]],
    "quiz":[mc("Stars twinkle because of Earth's:",["spin","atmosphere","magnetism","gravity"],1,"The atmosphere makes starlight shimmer."),
            tf("Space telescopes avoid the blurring of Earth's atmosphere.",True,"True - that is a key reason to launch them.")]},
   {"id":"history-spaceflight","title":"The Story of Spaceflight","level":"Core",
    "explain":["The space age began in 1957 when the Soviet Union launched Sputnik, the first satellite. Soon after, Yuri Gagarin became the first human in space, and in 1969 Apollo 11 landed people on the Moon.",
               "Since then, robotic probes have visited every planet, rovers have explored Mars, and astronauts have lived for decades aboard space stations."],
    "why":"Knowing this history shows how quickly humanity went from the ground to the Moon and beyond.",
    "hook":"From the first beeping satellite to footprints on the Moon took just twelve years.",
    "terms":[["Satellite","An object placed in orbit around the Earth."],
             ["Space age","The era of human space exploration begun in 1957."]],
    "quiz":[mc("The first artificial satellite was:",["Apollo 11","Sputnik","Hubble","Voyager"],1,"Sputnik, launched in 1957."),
            tf("Apollo 11 landed humans on the Moon in 1969.",True,"True - the first crewed Moon landing.")]},
 ]),
]

SKYWATCHING = [
 ("u-sky-1","Watching the Sky","Skills for the backyard astronomer","Foundations",[
   {"id":"naked-eye-observing","title":"Stargazing With Your Own Eyes","level":"Foundations",
    "explain":["You can begin astronomy with no equipment at all. On a clear, dark night away from city lights, your eyes can see thousands of stars, planets, the Moon, meteors and the band of the Milky Way.",
               "Give your eyes about twenty minutes to adapt to the dark, and use a red light to read a star map so you do not spoil your night vision."],
    "why":"Naked-eye observing is the oldest form of astronomy and still the best place to start.",
    "hook":"The best first telescope is no telescope at all, just your own dark-adapted eyes.",
    "terms":[["Dark adaptation","The way eyes grow more sensitive after time in darkness."],
             ["Light pollution","Glow from city lights that hides faint stars."]],
    "quiz":[mc("To see faint stars, you should let your eyes:",["stay in bright light","adapt to the dark","close fully","look at a phone"],1,"Eyes need time to adapt to darkness."),
            tf("You need a telescope before you can do any astronomy.",False,"Much can be seen with the naked eye alone.")]},
   {"id":"using-star-charts","title":"Reading Star Charts","level":"Foundations",
    "explain":["A star chart is a map of the night sky, showing the constellations visible at a given date and time. Held overhead and turned to match your direction, it helps you find your way among the stars.",
               "Bright, easy patterns like the Big Dipper or Orion act as signposts, pointing the way to fainter stars and constellations nearby."],
    "why":"Star charts turn a confusing sky into a readable map you can navigate.",
    "hook":"Find one famous pattern, and it points the way to all the rest.",
    "terms":[["Star chart","A map of the night sky for a given time and place."],
             ["Signpost","A bright, easy pattern used to find fainter ones."]],
    "quiz":[mc("The Big Dipper's pointer stars lead you to:",["Orion","the North Star","Venus","the Moon"],1,"They point to Polaris, the North Star."),
            tf("Star charts change with the date and time.",True,"True - the visible sky shifts through the year.")]},
   {"id":"binoculars-telescopes","title":"Binoculars and First Telescopes","level":"Core",
    "explain":["Before buying a telescope, many astronomers start with binoculars. They are cheap, easy to aim, and reveal the Moon's craters, Jupiter's moons and rich star clusters.",
               "A first telescope should be chosen for a steady mount and a decent-sized aperture rather than for big magnification claims printed on the box."],
    "why":"The right simple gear makes early astronomy rewarding instead of frustrating.",
    "hook":"A humble pair of binoculars can show you the moons of Jupiter.",
    "terms":[["Binoculars","Twin small telescopes used together, great for beginners."],
             ["Magnification","How much a telescope enlarges a view; not the most important feature."]],
    "misconception":"High magnification is not what makes a telescope good; a steady mount and a larger aperture matter far more.",
    "quiz":[mc("A good first telescope is chosen mainly for its steady mount and:",["price stickers","aperture","colour","brand name"],1,"Aperture and stability matter most."),
            tf("Binoculars can show the four large moons of Jupiter.",True,"True - they are easy to spot in binoculars.")]},
 ]),
 ("u-sky-2","People and Paths","The story of astronomy and how to join","Foundations",[
   {"id":"ancient-astronomy","title":"Astronomy in the Ancient World","level":"Foundations",
    "explain":["Long before telescopes, people across the world tracked the sky. Ancient Babylonians, Egyptians, Chinese, Maya and Polynesians used the stars to mark seasons, plan farming and navigate the seas.",
               "Many built remarkable monuments, like Stonehenge, aligned to the rising and setting Sun, showing how deeply the sky was woven into daily life."],
    "why":"Ancient sky-watching is the root from which all of modern astronomy grew.",
    "hook":"People were reading the sky as a calendar thousands of years before the first telescope.",
    "terms":[["Astronomy","The study of the sky and objects beyond Earth."],
             ["Navigation","Finding your way, often by using the stars."]],
    "quiz":[mc("Ancient peoples mainly used the stars to:",["watch films","mark seasons and navigate","heat their homes","make glass"],1,"For timekeeping, seasons and navigation."),
            tf("People studied the sky long before telescopes existed.",True,"True - sky-watching is very ancient.")]},
   {"id":"telescope-revolution","title":"The Telescope Changes Everything","level":"Core",
    "explain":["In 1609 Galileo turned a new invention, the telescope, toward the sky and changed astronomy forever. He saw mountains on the Moon, moons circling Jupiter and countless hidden stars.",
               "These discoveries showed that Earth was not the center of everything, supporting the idea that the planets orbit the Sun."],
    "why":"The telescope transformed astronomy from naked-eye watching into deep exploration.",
    "hook":"One small telescope in 1609 toppled the idea that Earth sat at the center of all.",
    "terms":[["Telescope","An instrument that gathers light to reveal distant objects."],
             ["Heliocentric","The model with the Sun, not Earth, at the center."]],
    "quiz":[mc("Galileo's telescope revealed moons orbiting:",["Mars","Jupiter","Saturn","the Sun"],1,"He discovered four moons of Jupiter."),
            tf("Galileo's discoveries supported the idea that planets orbit the Sun.",True,"True - they challenged an Earth-centred view.")]},
   {"id":"modern-astronomy-careers","title":"Careers in Astronomy and Space","level":"Foundations",
    "explain":["Astronomy and space offer many paths. Astronomers and astrophysicists study the universe, while engineers design rockets, satellites and rovers. Planetary scientists study worlds, and many people build and run telescopes.",
               "Beyond research, there are roles in software, data analysis, science communication and teaching. Most start with curiosity and a strong base in maths and science."],
    "why":"Knowing the many careers shows there are real ways to turn a love of space into a job.",
    "hook":"It takes far more than astronauts to explore space.",
    "terms":[["Astrophysicist","A scientist who studies the physics of stars and the universe."],
             ["Planetary scientist","A researcher who studies planets, moons and other worlds."]],
    "quiz":[mc("Which is a space-related career?",["only astronaut","astronomer, engineer, and many more","none exist","only teacher"],1,"There are many roles, from research to engineering."),
            tf("Maths and science are useful foundations for space careers.",True,"True - they underpin most space work.")]},
   {"id":"citizen-science-astro","title":"How You Can Contribute","level":"Foundations",
    "explain":["You do not need to be a professional to help real astronomy. Through 'citizen science' projects, volunteers classify galaxies, hunt for planets and spot asteroids using online data.",
               "Amateur astronomers also discover comets and track exploding stars, and their observations genuinely add to scientific knowledge."],
    "why":"Citizen science shows that anyone curious can take part in real discovery.",
    "hook":"Ordinary people have discovered comets, planets and new kinds of galaxies.",
    "terms":[["Citizen science","Real scientific research that volunteers can take part in."],
             ["Amateur astronomer","A non-professional who observes the sky, often skilfully."]],
    "quiz":[mc("Citizen science lets volunteers help by:",["doing nothing","classifying and spotting real data","only watching films","selling telescopes"],1,"They analyse real data and make discoveries."),
            tf("Amateur astronomers have discovered comets.",True,"True - amateurs make real discoveries.")]},
 ]),
]
