# -*- coding: utf-8 -*-
# Notable named stars. Tuple: (id, Name, sci(query), group, trait)
# group is the star type/short description used after "is a".

STARS = [
 ("sirius","Sirius","Sirius","blue-white star","The brightest star in the entire night sky, it is only about 8.6 light-years away and has a tiny white-dwarf companion."),
 ("canopus","Canopus","Canopus","white supergiant star","The second-brightest star in the night sky, a brilliant beacon of the far southern constellation Carina."),
 ("alpha-centauri","Alpha Centauri","Alpha Centauri","triple star system","The closest star system to the Sun at about 4.4 light-years, a trio that includes the faint red dwarf Proxima Centauri."),
 ("arcturus","Arcturus","Arcturus","orange giant star","A brilliant orange giant racing through the galaxy, it is the brightest star in the northern half of the sky."),
 ("vega","Vega","Vega","blue-white star","A nearby blue-white star that was once the pole star and will be again in about 12,000 years."),
 ("capella","Capella","Capella","yellow giant star","Actually a close pair of yellow giant stars, it is the sixth-brightest star and gleams high overhead in winter."),
 ("rigel","Rigel","Rigel","blue supergiant star","A colossal blue supergiant, it is the brightest star in Orion and one of the most luminous stars known."),
 ("procyon","Procyon","Procyon","white star","A bright, nearby star with a white-dwarf companion, it forms a winter triangle with Sirius and Betelgeuse."),
 ("betelgeuse","Betelgeuse","Betelgeuse","red supergiant star","A vast red supergiant marking Orion's shoulder; it is so swollen it will one day explode as a supernova."),
 ("achernar","Achernar","Achernar","blue star","A hot, fast-spinning blue star at the end of the river constellation Eridanus, flattened by its own rotation."),
 ("aldebaran","Aldebaran","Aldebaran","orange giant star","The orange 'eye of the bull' in Taurus, it appears among the Hyades cluster but is actually much closer to us."),
 ("antares","Antares","Antares","red supergiant star","A huge red supergiant whose name means 'rival of Mars' for its fiery color; it is the heart of the scorpion."),
 ("spica","Spica","Spica","blue star","The brilliant blue star of Virgo, it is actually two stars whirling around each other every four days."),
 ("pollux","Pollux","Pollux","orange giant star","The brighter of the Gemini twins, this orange giant is known to host at least one planet."),
 ("fomalhaut","Fomalhaut","Fomalhaut","white star","A bright, lonely star of the autumn sky, surrounded by a famous ring of dusty debris."),
 ("deneb","Deneb","Deneb","blue supergiant star","An immensely luminous blue supergiant marking the tail of the swan; despite its great distance it still shines brightly."),
 ("regulus","Regulus","Regulus","blue-white star","The bright 'little king' at the heart of Leo, a fast-spinning star squashed into an egg shape."),
 ("castor","Castor","Castor (star)","multiple star system","One of the Gemini twins, it looks like a single star but is really a system of six stars bound together."),
 ("polaris","Polaris","Polaris","yellow supergiant star","The North Star sits almost exactly above Earth's north pole, so it appears to stay still while the sky wheels around it."),
 ("altair","Altair","Altair","white star","A nearby, fast-spinning white star and a corner of the Summer Triangle; it whirls so fast it bulges at its equator."),
 ("proxima-centauri","Proxima Centauri","Proxima Centauri","red dwarf star","The single closest star to the Sun, a dim red dwarf that hosts at least one Earth-sized planet."),
 ("mira","Mira","Mira","red giant star","A pulsing red giant whose brightness swings so much it disappears from naked-eye view and returns over about eleven months."),
 ("algol","Algol","Algol","eclipsing binary star","The 'demon star' dims noticeably every 2.9 days when a dimmer companion passes in front of it."),
 ("bellatrix","Bellatrix","Bellatrix","blue giant star","A hot blue giant marking Orion's other shoulder, sometimes called the 'amazon star'."),
 ("rigil-kentaurus","Rigil Kentaurus","Alpha Centauri A","yellow star","The Sun-like primary star of the Alpha Centauri system, almost a twin of our own star."),
 ("mizar","Mizar","Mizar","multiple star system","The bend in the Big Dipper's handle; with sharp eyes you can spot its companion Alcor right beside it."),
 ("alcor","Alcor","Alcor","white star","The faint companion to Mizar in the Big Dipper, long used as a simple test of good eyesight."),
 ("dubhe","Dubhe","Dubhe","orange giant star","One of the two 'pointer stars' of the Big Dipper that lead the eye straight to the North Star."),
 ("merak","Merak","Merak","white star","The lower pointer star of the Big Dipper's bowl, partner to Dubhe in finding Polaris."),
 ("alkaid","Alkaid","Alkaid","blue star","The hot blue star at the very tip of the Big Dipper's handle."),
 ("thuban","Thuban","Thuban","white giant star","A modest star in Draco that was the North Star when the Egyptian pyramids were built."),
 ("vega-sister-placeholder","Sadr","Sadr","yellow supergiant star","The luminous star at the heart of the Northern Cross in Cygnus, buried in glowing Milky Way clouds."),
 ("albireo","Albireo","Albireo","double star","A famous colour-contrast double star: a golden star paired with a blue one, lovely in any small telescope."),
 ("mintaka","Mintaka","Mintaka","multiple star system","The westernmost star of Orion's Belt, sitting almost exactly on the celestial equator."),
 ("alnilam","Alnilam","Alnilam","blue supergiant star","The brilliant central star of Orion's Belt, a distant and extremely luminous blue supergiant."),
 ("alnitak","Alnitak","Alnitak","blue supergiant star","The easternmost star of Orion's Belt, glowing near the dark Horsehead Nebula."),
 ("aldebaran-companion-placeholder","Hadar","Beta Centauri","blue giant star","Also called Agena, this blue giant is the second-brightest star in Centaurus, near Alpha Centauri."),
 ("acrux","Acrux","Acrux","blue star","The brightest star of the Southern Cross and the southernmost first-magnitude star visible from Earth."),
 ("gacrux","Gacrux","Gacrux","red giant star","The red giant at the top of the Southern Cross, the nearest red giant star to the Sun."),
 ("shaula","Shaula","Shaula","blue star","The bright star marking the stinger in the scorpion's curled tail."),
 ("bellatrix-southern-placeholder","Peacock","Alpha Pavonis","blue star","The brightest star of the southern constellation Pavo, the peacock."),
 ("denebola","Denebola","Denebola","white star","The bright star marking the tail of Leo the lion."),
 ("alphard","Alphard","Alphard","orange giant star","The 'solitary one', a lone orange giant in the otherwise empty stretch of Hydra."),
 ("hamal","Hamal","Hamal","orange giant star","The brightest star of Aries the ram, an orange giant known to host a planet."),
 ("nunki","Nunki","Nunki","blue star","A hot blue star in the handle of the Sagittarius 'teapot', near the galactic center."),
 ("saiph","Saiph","Saiph","blue supergiant star","A blue supergiant marking one of Orion's knees, nearly as luminous as Rigel but cooler-looking to the eye."),
 ("wezen","Wezen","Wezen","yellow supergiant star","A rare yellow supergiant in the great dog, hundreds of times wider than the Sun."),
 ("adhara","Adhara","Adhara","blue giant star","The second-brightest star in Canis Major and one of the strongest sources of ultraviolet light in our sky."),
 ("castor-pollux-placeholder","Alphecca","Alphecca","white star","The brightest jewel in the Northern Crown, a white star with a faint companion."),
 ("rasalhague","Rasalhague","Rasalhague","white star","The bright head of the serpent-bearer Ophiuchus."),
 ("kochab","Kochab","Kochab","orange giant star","One of the 'guardians of the pole' in the Little Dipper, it was the pole star around 1500 BCE."),
 ("alderamin","Alderamin","Alderamin","white star","The brightest star of Cepheus, destined to become a future North Star as Earth's axis slowly wobbles."),
 ("enif","Enif","Enif","orange supergiant star","The bright orange star marking the nose of Pegasus the winged horse."),
 ("scheat","Scheat","Scheat","red giant star","A red giant at one corner of the Great Square of Pegasus."),
 ("markab","Markab","Markab","blue-white star","A star at another corner of the Great Square of Pegasus, long used in navigation."),
 ("alnair","Alnair","Alnair","blue star","The brightest star of Grus the crane, a hot blue star of the southern sky."),
 ("diphda","Diphda","Diphda","orange giant star","Also called Deneb Kaitos, the brightest star of Cetus the sea monster."),
 ("mirach","Mirach","Mirach","red giant star","A red giant in Andromeda, handy as a signpost: nearby sits a faint galaxy nicknamed 'Mirach's Ghost'."),
 ("alpheratz","Alpheratz","Alpheratz","blue star","A star shared between Andromeda and the Great Square of Pegasus, linking the two figures."),
 ("almach","Almach","Almach","orange giant star","A beautiful golden-and-blue double star at the foot of Andromeda."),
 ("rasalgethi","Rasalgethi","Rasalgethi","red supergiant star","A giant variable star marking the head of Hercules, paired with a greenish companion."),
 ("etamin","Eltanin","Eltanin","orange giant star","The brightest star of Draco the dragon, sometimes called the 'zenith star' over London."),
 ("vindemiatrix","Vindemiatrix","Vindemiatrix","yellow giant star","A yellow giant in Virgo whose name means 'the grape gatherer'."),
 ("zubenelgenubi","Zubenelgenubi","Zubenelgenubi","white star","Its tongue-twisting name means 'the southern claw', a leftover from when Libra's stars belonged to the scorpion."),
 ("menkar","Menkar","Menkar","red giant star","A cool red giant marking the jaw of Cetus the whale."),
 ("mirfak","Mirfak","Mirfak","yellow supergiant star","The brightest star of Perseus, a luminous yellow supergiant set in a sparkling cluster."),
 ("schedar","Schedar","Schedar","orange giant star","The brightest star of Cassiopeia, an orange giant marking the queen's chest."),
 ("caph","Caph","Caph (star)","yellow-white star","One of the stars forming the famous W of Cassiopeia."),
 ("alphekka-placeholder","Sabik","Sabik","white star","A bright star in Ophiuchus, the serpent-bearer."),
 ("sheliak","Sheliak","Sheliak","eclipsing binary star","A star in Lyra so close to its companion that the two are pulled into egg shapes and trade material."),
 ("sulafat","Sulafat","Sulafat","blue giant star","A blue giant in Lyra, near the famous Ring Nebula."),
 ("tarazed","Tarazed","Tarazed","orange giant star","An orange giant that flanks bright Altair in the eagle, Aquila."),
 ("alshain","Alshain","Alshain","yellow star","A modest star flanking Altair on the other side from Tarazed."),
 ("gienah","Gienah","Gienah","blue star","A star in Corvus the crow, whose name means 'the wing'."),
 ("algieba","Algieba","Algieba","orange giant pair","A close pair of golden giant stars in the 'sickle' of Leo, splendid in a telescope."),
 ("regor-placeholder","Suhail","Suhail","orange supergiant star","An orange supergiant in Vela, the sails of the ancient ship Argo."),
 ("avior","Avior","Avior","orange giant star","A star in Carina used as a navigation reference, despite its odd modern name."),
 ("miaplacidus","Miaplacidus","Miaplacidus","blue-white star","The second-brightest star of Carina, deep in the southern sky."),
 ("atria","Atria","Atria","orange giant star","The brightest star of the Southern Triangle, an orange giant."),
 ("sargas","Sargas","Sargas","yellow giant star","A bright star in the curling tail of Scorpius the scorpion."),
 ("dschubba","Dschubba","Dschubba","blue star","A blue star marking the forehead of Scorpius, near red Antares."),
 ("kaus-australis","Kaus Australis","Kaus Australis","blue star","The brightest star of Sagittarius, marking the bottom of the archer's bow."),
 ("nashira-placeholder","Deneb Algedi","Deneb Algedi","white star","The brightest star of Capricornus, the sea-goat."),
 ("sadalsuud","Sadalsuud","Sadalsuud","yellow supergiant star","The brightest star of Aquarius, a distant and luminous yellow supergiant."),
 ("homam-placeholder","Sadalmelik","Sadalmelik","yellow supergiant star","Another luminous yellow supergiant in Aquarius, its name meaning 'lucky star of the king'."),
 ("hadar-placeholder2","Menkalinan","Menkalinan","white star","The second-brightest star of Auriga, a pair of stars that eclipse each other."),
 ("elnath","Elnath","Elnath","blue giant star","A blue giant shared on the border of Taurus and Auriga, marking the tip of the bull's horn."),
 ("alhena","Alhena","Alhena","blue-white star","A bright star marking the foot of one of the Gemini twins."),
 ("propus-placeholder","Tejat","Tejat","red giant star","A red giant in Gemini marking the other twin's foot."),
 ("naos","Naos","Naos","blue supergiant star","One of the hottest and most luminous stars visible to the naked eye, in the stern of the ship Puppis."),
]

def build():
    out = []
    for sid, name, sci, group, trait in STARS:
        out.append({
            "id": sid, "name": name, "sci": sci,
            "cat": "star",
            "group": group,
            "hab": "our Milky Way galaxy",
            "habKey": "milkyway",
            "flavor": "Like all stars, it is a giant ball of hot gas that shines by fusing lighter elements into heavier ones in its core.",
            "art": "star",
            "trait": trait,
            "track": "fauna",
            "termA": ["Star", "A giant glowing ball of gas, like the Sun, that makes its own light through nuclear fusion."],
            "termB": ["Light-year", "The distance light travels in one year, about 9.5 trillion kilometres."],
        })
    return out

if __name__ == "__main__":
    b = build()
    print(len(b), "stars")
    ids = [x["id"] for x in b]
    assert len(ids) == len(set(ids)), "dup ids"
    print("unique ok")
