# -*- coding: utf-8 -*-
# The 88 official IAU constellations, with sky hemisphere and a factual trait.
# Each tuple: (id, Name, sci(genitive/abbr for query), sky, trait)
# sky is one of: "the northern sky", "the southern sky", "the zodiac"

CONSTELLATIONS = [
 ("andromeda","Andromeda","Andromeda (constellation)","the northern sky","Named for a princess of Greek myth, it holds the Andromeda Galaxy, the most distant thing easily seen with the unaided eye."),
 ("antlia","Antlia","Antlia","the southern sky","A faint southern constellation named after the air pump, one of several invented in the 1700s to fill empty sky."),
 ("apus","Apus","Apus","the southern sky","Its name means 'bird of paradise', a dim group near the south celestial pole."),
 ("aquarius","Aquarius","Aquarius","the zodiac","The 'water bearer' is an ancient zodiac constellation, but its stars are faint and spread out."),
 ("aquila","Aquila","Aquila (constellation)","the northern sky","The 'eagle' carries the brilliant star Altair, one corner of the Summer Triangle."),
 ("ara","Ara","Ara (constellation)","the southern sky","Representing an altar, it lies in a rich part of the southern Milky Way."),
 ("aries","Aries","Aries (constellation)","the zodiac","The 'ram' is a small zodiac constellation that once marked the spot where the Sun crossed the equator in spring."),
 ("auriga","Auriga","Auriga (constellation)","the northern sky","The 'charioteer' contains Capella, the sixth-brightest star in the night sky."),
 ("bootes","Bootes","Bootes","the northern sky","The 'herdsman' is home to Arcturus, a brilliant orange star you can find by following the handle of the Big Dipper."),
 ("caelum","Caelum","Caelum","the southern sky","A tiny, faint constellation named for an engraver's chisel."),
 ("camelopardalis","Camelopardalis","Camelopardalis","the northern sky","Its long name means 'giraffe', a large but dim region near the north celestial pole."),
 ("cancer","Cancer","Cancer (constellation)","the zodiac","The faintest zodiac constellation, the 'crab' holds the Beehive star cluster, visible as a misty patch."),
 ("canes-venatici","Canes Venatici","Canes Venatici","the northern sky","The 'hunting dogs' contain the famous Whirlpool Galaxy, M51."),
 ("canis-major","Canis Major","Canis Major","the southern sky","The 'great dog' carries Sirius, the brightest star in the entire night sky."),
 ("canis-minor","Canis Minor","Canis Minor","the northern sky","The 'little dog' is marked by Procyon, the eighth-brightest star in the sky."),
 ("capricornus","Capricornus","Capricornus","the zodiac","The 'sea goat' is the smallest zodiac constellation, an ancient figure half-goat and half-fish."),
 ("carina","Carina","Carina (constellation)","the southern sky","The 'keel' of the ship Argo holds Canopus, the second-brightest star, and the huge Carina Nebula."),
 ("cassiopeia","Cassiopeia","Cassiopeia (constellation)","the northern sky","This vain queen forms an unmistakable W or M shape opposite the Big Dipper around the pole star."),
 ("centaurus","Centaurus","Centaurus","the southern sky","The 'centaur' contains Alpha Centauri, the closest star system to the Sun."),
 ("cepheus","Cepheus","Cepheus (constellation)","the northern sky","This king of myth gives his name to Cepheid stars, pulsing beacons used to measure cosmic distances."),
 ("cetus","Cetus","Cetus (constellation)","the southern sky","The 'sea monster' or whale holds Mira, a red giant whose brightness swings wildly over months."),
 ("chamaeleon","Chamaeleon","Chamaeleon","the southern sky","A small, faint constellation near the south pole named for the color-changing lizard."),
 ("circinus","Circinus","Circinus","the southern sky","A tiny southern constellation named after a drafting compass."),
 ("columba","Columba","Columba","the southern sky","The 'dove' is a small constellation said to represent the bird Noah released from the ark."),
 ("coma-berenices","Coma Berenices","Coma Berenices","the northern sky","'Berenice's hair' is a faint sprinkle of stars and home to a great cluster of distant galaxies."),
 ("corona-australis","Corona Australis","Corona Australis","the southern sky","The 'southern crown' is a small, neat arc of stars near Sagittarius."),
 ("corona-borealis","Corona Borealis","Corona Borealis","the northern sky","The 'northern crown' is a delicate semicircle of stars, easy to recognize once you find it."),
 ("corvus","Corvus","Corvus (constellation)","the southern sky","The 'crow' is a small but distinct four-star pattern in the southern sky."),
 ("crater","Crater","Crater (constellation)","the southern sky","The 'cup' is a faint constellation said to be the goblet of the god Apollo."),
 ("crux","Crux","Crux","the southern sky","The smallest constellation of all, the Southern Cross is a beloved landmark for finding south."),
 ("cygnus","Cygnus","Cygnus (constellation)","the northern sky","The 'swan', also called the Northern Cross, flies along the Milky Way and carries bright Deneb."),
 ("delphinus","Delphinus","Delphinus","the northern sky","The 'dolphin' is a small, charming diamond of stars leaping out of the Milky Way."),
 ("dorado","Dorado","Dorado","the southern sky","The 'swordfish' contains most of the Large Magellanic Cloud, a small companion galaxy."),
 ("draco","Draco","Draco (constellation)","the northern sky","The 'dragon' winds between the Big and Little Dippers; its star Thuban was the pole star in the age of the pyramids."),
 ("equuleus","Equuleus","Equuleus","the northern sky","The 'little horse' is the second-smallest constellation, a faint group near Pegasus."),
 ("eridanus","Eridanus","Eridanus (constellation)","the southern sky","Representing a great river, it is one of the longest constellations, winding far across the sky."),
 ("fornax","Fornax","Fornax","the southern sky","Named for a furnace, this faint region is a favorite deep-sky window for studying distant galaxies."),
 ("gemini","Gemini","Gemini (constellation)","the zodiac","The 'twins' are marked by the bright pair Castor and Pollux, side by side in the winter sky."),
 ("grus","Grus","Grus (constellation)","the southern sky","The 'crane' is a graceful southern bird-shaped constellation."),
 ("hercules","Hercules","Hercules (constellation)","the northern sky","The strongman of myth contains M13, one of the finest globular star clusters in the northern sky."),
 ("horologium","Horologium","Horologium","the southern sky","A faint southern constellation named after a pendulum clock."),
 ("hydra","Hydra","Hydra (constellation)","the southern sky","The 'water snake' is the largest of all constellations, sprawling more than a quarter of the way around the sky."),
 ("hydrus","Hydrus","Hydrus","the southern sky","The 'male water snake' is a small constellation near the south celestial pole, not to be confused with Hydra."),
 ("indus","Indus","Indus (constellation)","the southern sky","Representing an indigenous person, it is a faint constellation of the deep southern sky."),
 ("lacerta","Lacerta","Lacerta","the northern sky","The 'lizard' is a small, faint zigzag of stars tucked into the northern Milky Way."),
 ("leo","Leo","Leo (constellation)","the zodiac","The 'lion' is one of the few constellations that truly looks like its name, led by the bright star Regulus."),
 ("leo-minor","Leo Minor","Leo Minor","the northern sky","The 'smaller lion' is a faint trio of stars beside the much grander Leo."),
 ("lepus","Lepus","Lepus (constellation)","the southern sky","The 'hare' crouches beneath the feet of Orion the hunter."),
 ("libra","Libra","Libra (constellation)","the zodiac","The 'scales' is the only zodiac constellation representing an object rather than a living thing."),
 ("lupus","Lupus","Lupus (constellation)","the southern sky","The 'wolf' lies in a rich southern stretch of the Milky Way."),
 ("lynx","Lynx","Lynx (constellation)","the northern sky","So faint it was named for the lynx, since you supposedly need a cat's sharp eyes to see it."),
 ("lyra","Lyra","Lyra (constellation)","the northern sky","The 'lyre' carries Vega, a brilliant blue-white star and corner of the Summer Triangle."),
 ("mensa","Mensa","Mensa (constellation)","the southern sky","Named for Table Mountain, it is the only constellation named after a real place on Earth."),
 ("microscopium","Microscopium","Microscopium","the southern sky","A faint southern constellation named after the microscope."),
 ("monoceros","Monoceros","Monoceros","the northern sky","The 'unicorn' is faint but sits in a glorious part of the winter Milky Way full of nebulae."),
 ("musca","Musca","Musca","the southern sky","The 'fly' is the only constellation named after an insect, near the Southern Cross."),
 ("norma","Norma","Norma (constellation)","the southern sky","Named after a carpenter's set square, it lies in the dense southern Milky Way."),
 ("octans","Octans","Octans","the southern sky","It contains the south celestial pole, but its 'south star' Sigma Octantis is barely visible."),
 ("ophiuchus","Ophiuchus","Ophiuchus","the northern sky","The 'serpent bearer' is a huge constellation the Sun passes through, though it is not counted among the zodiac signs."),
 ("orion","Orion","Orion (constellation)","the southern sky","The 'hunter' is the most recognizable constellation, with its three-star belt and the glowing Orion Nebula below."),
 ("pavo","Pavo","Pavo (constellation)","the southern sky","The 'peacock' is a southern constellation whose brightest star is even named Peacock."),
 ("pegasus","Pegasus","Pegasus (constellation)","the northern sky","The winged horse is marked by the Great Square, a huge box of stars high in the autumn sky."),
 ("perseus","Perseus","Perseus (constellation)","the northern sky","This hero holds Algol, the 'demon star', which fades every few days as a companion eclipses it."),
 ("phoenix","Phoenix","Phoenix (constellation)","the southern sky","Named for the mythical firebird, it is the largest of the faint southern bird constellations."),
 ("pictor","Pictor","Pictor","the southern sky","Named for a painter's easel, it hosts Beta Pictoris, a young star with a famous disk of planet-forming dust."),
 ("pisces","Pisces","Pisces (constellation)","the zodiac","The 'fishes' is a large but dim zodiac constellation; the Sun now sits here at the spring equinox."),
 ("piscis-austrinus","Piscis Austrinus","Piscis Austrinus","the southern sky","The 'southern fish' holds Fomalhaut, a lonely bright star in an otherwise empty patch of autumn sky."),
 ("puppis","Puppis","Puppis","the southern sky","The 'stern' of the ancient ship Argo lies in a brilliant stretch of the southern Milky Way."),
 ("pyxis","Pyxis","Pyxis","the southern sky","The 'compass' of the ship Argo is a small, faint southern constellation."),
 ("reticulum","Reticulum","Reticulum","the southern sky","Named for an eyepiece reticle, it is a small diamond of stars in the far south."),
 ("sagitta","Sagitta","Sagitta","the northern sky","The 'arrow' is the third-smallest constellation, a tiny but clear dart in the Milky Way."),
 ("sagittarius","Sagittarius","Sagittarius","the zodiac","The 'archer' points its bow straight at the crowded, glowing center of our Milky Way galaxy."),
 ("scorpius","Scorpius","Scorpius","the zodiac","The 'scorpion' is a striking curl of stars led by red Antares, the 'rival of Mars'."),
 ("sculptor","Sculptor","Sculptor (constellation)","the southern sky","A faint constellation that happens to contain the south pole of our entire Milky Way galaxy."),
 ("scutum","Scutum","Scutum","the southern sky","The 'shield' is small but sits over a bright star cloud in the Milky Way."),
 ("serpens","Serpens","Serpens","the northern sky","The 'serpent' is the only constellation split into two separate pieces, held by Ophiuchus."),
 ("sextans","Sextans","Sextans","the southern sky","Named for a navigator's sextant, it is a faint constellation just south of Leo."),
 ("taurus","Taurus","Taurus (constellation)","the zodiac","The 'bull' carries the bright orange star Aldebaran and the sparkling Pleiades star cluster."),
 ("telescopium","Telescopium","Telescopium","the southern sky","A faint southern constellation named, fittingly for us, after the telescope."),
 ("triangulum","Triangulum","Triangulum","the northern sky","A simple, neat triangle of stars that hosts the Triangulum Galaxy, M33."),
 ("triangulum-australe","Triangulum Australe","Triangulum Australe","the southern sky","The 'southern triangle' is brighter and easier to see than its northern namesake."),
 ("tucana","Tucana","Tucana","the southern sky","The 'toucan' holds the Small Magellanic Cloud and the magnificent globular cluster 47 Tucanae."),
 ("ursa-major","Ursa Major","Ursa Major","the northern sky","The 'great bear' contains the Big Dipper, whose pointer stars lead you straight to the North Star."),
 ("ursa-minor","Ursa Minor","Ursa Minor","the northern sky","The 'little bear', or Little Dipper, ends at Polaris, the North Star that marks true north."),
 ("vela","Vela","Vela (constellation)","the southern sky","The 'sails' of the ship Argo lie in a rich southern field dotted with nebulae."),
 ("virgo","Virgo","Virgo (constellation)","the zodiac","The 'maiden' is the second-largest constellation and home to a huge cluster of galaxies."),
 ("volans","Volans","Volans","the southern sky","The 'flying fish' is a small constellation tucked beside the Large Magellanic Cloud."),
 ("vulpecula","Vulpecula","Vulpecula","the northern sky","The 'little fox' is faint but home to the Dumbbell Nebula, a favorite small-telescope target."),
]

def build():
    out = []
    for cid, name, sci, sky, trait in CONSTELLATIONS:
        out.append({
            "id": cid, "name": name, "sci": sci,
            "cat": "constellation",
            "group": "constellation",
            "hab": sky,
            "habKey": ("zodiac" if sky=="the zodiac" else ("northsky" if "northern" in sky else "southsky")),
            "flavor": "Like all constellations, it is one of the 88 official patterns the sky is divided into.",
            "art": "constellation",
            "trait": trait,
            "track": "fauna",
            "termA": ["Constellation", "One of the 88 official patterns that astronomers use to divide up the sky."],
            "termB": None,
        })
    return out

if __name__ == "__main__":
    b = build()
    print(len(b), "constellations")
    print(b[0])
