# -*- coding: utf-8 -*-
import gen_curriculum as g
S = g.S
B = "fauna"
S("wood-duck","Wood duck","duck (bird)",B,"wetland","omni","The male is among the most colorful of all waterfowl, and ducklings leap from the high tree-hole nest the day after they hatch.",sci="Aix sponsa",kind="bird")
S("northern-pintail","Northern pintail","duck (bird)",B,"wetland","omni","A slender, elegant duck named for the male's long, pointed tail; it is a strong long-distance migrant.",sci="Anas acuta",kind="bird")
S("american-wigeon","American wigeon","duck (bird)",B,"wetland","herb","The male's white crown earns it the nickname 'baldpate,' and it often snatches plants that diving birds bring up.",sci="Mareca americana",kind="bird")
S("green-winged-teal","Green-winged teal","duck (bird)",B,"wetland","omni","The smallest North American dabbling duck, it twists and turns in fast, tight flocks.",sci="Anas crecca",kind="bird")
S("northern-shoveler","Northern shoveler","duck (bird)",B,"wetland","omni","Its huge spoon-shaped bill is lined with comb-like teeth that strain tiny food from the water.",sci="Spatula clypeata",kind="bird")
S("canvasback","Canvasback","duck (bird)",B,"lake","aquaticplants","A fast-flying diving duck with a sloping forehead, it dives to feed on roots and plants on the bottom.",sci="Aythya valisineria",kind="bird")
S("ruddy-duck","Ruddy duck","duck (bird)",B,"lake","aquaticplants","A small, stiff-tailed diving duck whose breeding male sports a bright sky-blue bill.",sci="Oxyura jamaicensis",kind="bird")
S("hooded-merganser","Hooded merganser","duck (bird)",B,"lake","fish","It can raise a striking fan-shaped crest, and it dives for fish gripping them with a thin, saw-edged bill.",sci="Lophodytes cucullatus",kind="bird")
S("common-merganser","Common merganser","duck (bird)",B,"river","fish","A sleek fish-eating diving duck whose serrated 'sawbill' helps it hold slippery prey.",sci="Mergus merganser",kind="bird")
S("trumpeter-swan","Trumpeter swan","swan (bird)",B,"lake","aquaticplants","The heaviest native waterfowl in North America, it was nearly hunted to extinction before a remarkable recovery.",sci="Cygnus buccinator",kind="bird")
S("tundra-swan","Tundra swan","swan (bird)",B,"wetland","aquaticplants","It nests on the Arctic tundra and migrates south in long, calling V-formations each winter.",sci="Cygnus columbianus",kind="bird")
S("snow-goose","Snow goose","goose (bird)",B,"wetland","herb","It migrates in enormous, noisy flocks and comes in a white form and a dark 'blue' form.",sci="Anser caerulescens",kind="bird")
S("american-coot","American coot","water bird",B,"lake","aquaticplants","Though it swims like a duck, it is actually a rail, and it has lobed rather than webbed toes.",sci="Fulica americana",kind="bird")
S("pied-billed-grebe","Pied-billed grebe","water bird",B,"lake","fish","It can sink slowly out of sight like a submarine by squeezing the air out of its feathers.",sci="Podilymbus podiceps",kind="bird")
S("double-crested-cormorant","Double-crested cormorant","water bird",B,"lake","fish","After diving for fish it perches with wings spread to dry, because its feathers are not fully waterproof.",sci="Nannopterus auritus",kind="bird")
S("american-white-pelican","American white pelican","water bird",B,"lake","fish","One of the largest North American birds, groups of them herd fish into the shallows and scoop them up together.",sci="Pelecanus erythrorhynchos",kind="bird")
S("belted-kingfisher","Belted kingfisher","water bird",B,"river","fish","It plunges headfirst from a perch to catch fish, and unusually the female is more colorful than the male.",sci="Megaceryle alcyon",kind="bird")
S("great-egret","Great egret","wading bird",B,"wetland","fish","This tall white heron was hunted nearly to extinction for the long plumes it grows in the breeding season.",sci="Ardea alba",kind="bird")
S("snowy-egret","Snowy egret","wading bird",B,"wetland","fish","It has black legs and bright yellow feet, which it shuffles in the water to stir up hidden prey.",sci="Egretta thula",kind="bird")
S("green-heron","Green heron","wading bird",B,"wetland","fish","One of the few tool-using birds, it drops insects or feathers onto the water as bait to lure fish.",sci="Butorides virescens",kind="bird")
S("black-crowned-night-heron","Black-crowned night-heron","wading bird",B,"wetland","fish","It hunts mostly at dusk and through the night, when taller daytime herons are roosting.",sci="Nycticorax nycticorax",kind="bird")
S("american-bittern","American bittern","wading bird",B,"wetland","fish","When alarmed it freezes with its striped neck and bill pointed straight up, vanishing among the reeds.",sci="Botaurus lentiginosus",kind="bird")
S("killdeer","Killdeer","shorebird (bird)",B,"meadow","insects","To protect its ground nest it fakes a broken wing, luring predators away before flying off unharmed.",sci="Charadrius vociferus",kind="bird")
S("american-woodcock","American woodcock","shorebird (bird)",B,"wetforest","insects","A plump shorebird of damp woods, the male performs a spiraling 'sky dance' high overhead at dusk.",sci="Scolopax minor",kind="bird")
S("spotted-sandpiper","Spotted sandpiper","shorebird (bird)",B,"river","insects","It teeters and bobs its tail constantly, and the female often mates with several males who raise the chicks.",sci="Actitis macularius",kind="bird")
S("greater-yellowlegs","Greater yellowlegs","shorebird (bird)",B,"wetland","insects","A tall, watchful wader on bright yellow legs, it gives loud ringing alarm calls across the marsh.",sci="Tringa melanoleuca",kind="bird")
S("ring-billed-gull","Ring-billed gull","gull (bird)",B,"lake","omni","The familiar 'parking-lot gull,' it is named for the neat black ring around its yellow bill.",sci="Larus delawarensis",kind="bird")
S("red-bellied-woodpecker","Red-bellied woodpecker","woodpecker (bird)",B,"forest","omni","Despite the name, the boldest mark is the red cap on its head; the pale belly blush is hard to see.",sci="Melanerpes carolinus",kind="bird")
S("downy-woodpecker","Downy woodpecker","woodpecker (bird)",B,"forest","insects","The smallest woodpecker in North America, it is a frequent and acrobatic visitor to backyard feeders.",sci="Dryobates pubescens",kind="bird")
S("hairy-woodpecker","Hairy woodpecker","woodpecker (bird)",B,"forest","insects","It looks like a larger twin of the downy woodpecker but has a noticeably longer, chisel-like bill.",sci="Dryobates villosus",kind="bird")
S("northern-flicker","Northern flicker","woodpecker (bird)",B,"edge","insects","Unusual among woodpeckers, it often feeds on the ground, using its long tongue to lap up ants.",sci="Colaptes auratus",kind="bird")
S("red-headed-woodpecker","Red-headed woodpecker","woodpecker (bird)",B,"edge","omni","Its entire head is bright crimson, and it is skilled enough to catch insects on the wing and store food.",sci="Melanerpes erythrocephalus",kind="bird")
S("yellow-bellied-sapsucker","Yellow-bellied sapsucker","woodpecker (bird)",B,"forest","insects","It drills neat rows of small holes, called sap wells, in tree bark and feeds on the oozing sap.",sci="Sphyrapicus varius",kind="bird")
S("acorn-woodpecker","Acorn woodpecker","woodpecker (bird)",B,"forest","insects","It drills holes in 'granary' trees and wedges thousands of acorns into them, one per hole, to store for winter.",sci="Melanerpes formicivorus",kind="bird")
S("northern-bobwhite","Northern bobwhite","game bird",B,"grass","seeds","A small quail named for the male's clear, whistled 'bob-WHITE' call ringing across grassy fields.",sci="Colinus virginianus",kind="bird")
