# -*- coding: utf-8 -*-
import gen_curriculum as g
S = g.S
B = "fauna"
S("mourning-dove","Mourning dove","dove (bird)",B,"urban","seeds","Its soft, mournful cooing is often mistaken for an owl, and it is one of the most abundant birds in North America.",sci="Zenaida macroura",kind="bird")
S("rock-pigeon","Rock pigeon","dove (bird)",B,"urban","seeds","The familiar city pigeon, it descends from wild doves that nested on sea cliffs and rocky ledges.",sci="Columba livia",kind="bird")
S("white-breasted-nuthatch","White-breasted nuthatch","songbird (bird)",B,"forest","insects","It walks headfirst down tree trunks, an upside-down view that helps it spot food other birds miss.",sci="Sitta carolinensis",kind="bird")
S("red-breasted-nuthatch","Red-breasted nuthatch","songbird (bird)",B,"conifer","insects","It smears sticky tree sap around the entrance of its nest hole, apparently to keep intruders out.",sci="Sitta canadensis",kind="bird")
S("brown-creeper","Brown creeper","songbird (bird)",B,"forest","insects","It spirals up a tree trunk probing the bark for insects, then flutters down to start up the next tree.",sci="Certhia americana",kind="bird")
S("tufted-titmouse","Tufted titmouse","songbird (bird)",B,"forest","seeds","A perky crested songbird, it will sometimes pluck hair from a living animal to line its nest.",sci="Baeolophus bicolor",kind="bird")
S("carolina-wren","Carolina wren","songbird (bird)",B,"edge","insects","Tiny but startlingly loud, the male belts out a ringing 'tea-kettle, tea-kettle, tea-kettle' song.",sci="Thryothorus ludovicianus",kind="bird")
S("house-wren","House wren","songbird (bird)",B,"urban","insects","A plain but feisty little bird, it crams nest boxes full of twigs and fiercely defends its territory.",sci="Troglodytes aedon",kind="bird")
S("american-dipper","American dipper","songbird (bird)",B,"river","insects","North America's only truly aquatic songbird, it walks along the bottom of cold mountain streams to feed.",sci="Cinclus mexicanus",kind="bird")
S("cedar-waxwing","Cedar waxwing","songbird (bird)",B,"edge","fruit","Sleek and social, it feeds in flocks on berries and has bright waxy-red tips on its wing feathers.",sci="Bombycilla cedrorum",kind="bird")
S("gray-catbird","Gray catbird","songbird (bird)",B,"edge","omni","It mews like a cat and stitches snippets of other birds' songs into its own rambling tune.",sci="Dumetella carolinensis",kind="bird")
S("northern-mockingbird","Northern mockingbird","songbird (bird)",B,"urban","omni","It can learn and imitate hundreds of sounds, copying other birds and even car alarms and machines.",sci="Mimus polyglottos",kind="bird")
S("brown-thrasher","Brown thrasher","songbird (bird)",B,"edge","omni","It has one of the largest song repertoires of any North American bird, with over a thousand song types.",sci="Toxostoma rufum",kind="bird")
S("eastern-towhee","Eastern towhee","songbird (bird)",B,"edge","seeds","It scratches noisily in dead leaves, kicking backward with both feet at once to uncover seeds and bugs.",sci="Pipilo erythrophthalmus",kind="bird")
S("dark-eyed-junco","Dark-eyed junco","songbird (bird)",B,"forest","seeds","Often called the 'snowbird,' it flashes white outer tail feathers as it flits up from the ground.",sci="Junco hyemalis",kind="bird")
S("song-sparrow","Song sparrow","songbird (bird)",B,"edge","seeds","One of the most widespread sparrows, each male sings his own personal variation of the species' tune.",sci="Melospiza melodia",kind="bird")
S("white-throated-sparrow","White-throated sparrow","songbird (bird)",B,"forest","seeds","It whistles a clear, wavering song that people often write as 'Oh sweet Canada, Canada, Canada.'",sci="Zonotrichia albicollis",kind="bird")
S("white-crowned-sparrow","White-crowned sparrow","songbird (bird)",B,"edge","seeds","Marked by a crisp black-and-white striped crown, it is a champion long-distance migrant.",sci="Zonotrichia leucophrys",kind="bird")
S("chipping-sparrow","Chipping sparrow","songbird (bird)",B,"urban","seeds","A small, tidy sparrow with a rusty cap, it sings a long, dry, mechanical-sounding trill.",sci="Spizella passerina",kind="bird")
S("house-sparrow","House sparrow","songbird (bird)",B,"urban","seeds","Introduced from Europe, this non-native bird now lives around buildings and farms across the continent.",sci="Passer domesticus",kind="bird")
S("house-finch","House finch","songbird (bird)",B,"urban","seeds","The red color on the male comes from pigments in the food he eats, so diet can change how bright he is.",sci="Haemorhous mexicanus",kind="bird")
S("purple-finch","Purple finch","songbird (bird)",B,"conifer","seeds","A famous guide described the rosy male as a sparrow 'dipped in raspberry juice.'",sci="Haemorhous purpureus",kind="bird")
S("pine-siskin","Pine siskin","songbird (bird)",B,"conifer","seeds","A streaky little finch with yellow wing flashes, it wanders far and wide chasing good seed crops.",sci="Spinus pinus",kind="bird")
S("evening-grosbeak","Evening grosbeak","songbird (bird)",B,"conifer","seeds","A chunky finch with a massive pale bill powerful enough to crack open hard cherry and other seeds.",sci="Coccothraustes vespertinus",kind="bird")
S("indigo-bunting","Indigo bunting","songbird (bird)",B,"edge","seeds","The male glows brilliant blue, though the color is really a trick of light, as the feathers are brown.",sci="Passerina cyanea",kind="bird")
S("rose-breasted-grosbeak","Rose-breasted grosbeak","songbird (bird)",B,"forest","seeds","The male is black and white with a bright red splash on the chest, like a spilled drop of paint.",sci="Pheucticus ludovicianus",kind="bird")
S("scarlet-tanager","Scarlet tanager","songbird (bird)",B,"forest","insects","In summer the male is brilliant scarlet with black wings, then molts to a dull yellow-green for winter.",sci="Piranga olivacea",kind="bird")
S("baltimore-oriole","Baltimore oriole","songbird (bird)",B,"edge","fruit","It weaves a remarkable hanging, sock-shaped nest and is strongly drawn to oranges and ripe fruit.",sci="Icterus galbula",kind="bird")
S("red-winged-blackbird","Red-winged blackbird","songbird (bird)",B,"wetland","seeds","The male flashes scarlet shoulder patches and sings loudly to defend his patch of marsh.",sci="Agelaius phoeniceus",kind="bird")
S("common-grackle","Common grackle","songbird (bird)",B,"urban","omni","A long-tailed blackbird that gleams with iridescent purple and bronze and has a piercing pale eye.",sci="Quiscalus quiscula",kind="bird")
S("brown-headed-cowbird","Brown-headed cowbird","songbird (bird)",B,"edge","seeds","It lays its eggs in other birds' nests, leaving those parents to raise its chicks instead of their own.",sci="Molothrus ater",kind="bird")
S("eastern-meadowlark","Eastern meadowlark","songbird (bird)",B,"grass","insects","A bird of open grasslands, it has a bright yellow chest crossed by a black V and a clear, flute-like song.",sci="Sturnella magna",kind="bird")
S("bobolink","Bobolink","songbird (bird)",B,"grass","seeds","It migrates from northern hayfields all the way to southern South America and back, twice a year.",sci="Dolichonyx oryzivorus",kind="bird")
S("barn-swallow","Barn swallow","songbird (bird)",B,"edge","insects","It builds a cup of mud in barns and under bridges and has a deeply forked, streaming tail.",sci="Hirundo rustica",kind="bird")
S("tree-swallow","Tree swallow","songbird (bird)",B,"wetland","insects","Iridescent blue-green above and white below, it nests in tree holes and boxes, often near water.",sci="Tachycineta bicolor",kind="bird")
