# -*- coding: utf-8 -*-
import gen_curriculum as g
S = g.S
B = "fauna"
S("american-mink","American mink","weasel (mammal)",B,"river","carn","A glossy, semiaquatic weasel, it hunts both on land and underwater along streambanks and pond edges.",sci="Neogale vison",kind="animal")
S("long-tailed-weasel","Long-tailed weasel","weasel (mammal)",B,"edge","smallmammals","A small but fearless hunter, in the north it trades its brown coat for pure white in winter.",sci="Neogale frenata",kind="animal")
S("american-badger","American badger","badger (mammal)",B,"grass","smallmammals","A powerful digger, it can tunnel through soil astonishingly fast to chase ground squirrels into their burrows.",sci="Taxidea taxus",kind="animal")
S("fisher","Fisher","weasel (mammal)",B,"forest","carn","A large forest weasel, it is one of the few predators skilled enough to regularly kill porcupines.",sci="Pekania pennanti",kind="animal")
S("wolverine","Wolverine","weasel (mammal)",B,"tundra","carn","The largest land-dwelling weasel, it has jaws and strength out of all proportion to its size.",sci="Gulo gulo",kind="animal")
S("gray-fox","Gray fox","fox (mammal)",B,"forest","omni","Unique among American dogs, it can climb trees, using hooked claws to escape danger or reach fruit.",sci="Urocyon cinereoargenteus",kind="animal")
S("swift-fox","Swift fox","fox (mammal)",B,"grass","omni","A cat-sized fox of the short-grass prairie, it is named for its quick, darting bursts of speed.",sci="Vulpes velox",kind="animal")
S("kit-fox","Kit fox","fox (mammal)",B,"desert","carn","A tiny desert fox with enormous ears that shed body heat and pick up the faint sounds of prey.",sci="Vulpes macrotis",kind="animal")
S("ringtail","Ringtail","raccoon relative (mammal)",B,"rocky","omni","A nimble relative of the raccoon, it has a long banded tail nearly as long as its body and is a superb climber.",sci="Bassariscus astutus",kind="animal")
S("muskrat","Muskrat","rodent (mammal)",B,"wetland","aquaticplants","It builds dome-shaped lodges of cattails and reeds in marshes and swims with a flattened, rudder-like tail.",sci="Ondatra zibethicus",kind="animal")
S("woodchuck","Woodchuck (groundhog)","marmot (mammal)",B,"meadow","herb","A large burrowing ground squirrel, it fattens up in fall and sleeps through winter in true, deep hibernation.",sci="Marmota monax",kind="animal")
S("yellow-bellied-marmot","Yellow-bellied marmot","marmot (mammal)",B,"rocky","herb","It suns itself on mountain boulders and gives a sharp whistle of alarm, earning the nickname 'whistle pig.'",sci="Marmota flaviventris",kind="animal")
S("black-tailed-prairie-dog","Black-tailed prairie dog","prairie dog (mammal)",B,"grass","herb","It lives in vast underground 'towns' and is a keystone of the prairie whose burrows shelter many other animals.",sci="Cynomys ludovicianus",kind="animal")
S("thirteen-lined-ground-squirrel","Thirteen-lined ground squirrel","squirrel (mammal)",B,"grass","omni","Its back is striped and spotted like a tiny leopard, and it spends winter hibernating underground.",sci="Ictidomys tridecemlineatus",kind="animal")
S("golden-mantled-ground-squirrel","Golden-mantled ground squirrel","squirrel (mammal)",B,"mountain","omni","Often mistaken for a big chipmunk, it has the chipmunk's striped body but no stripes across its face.",sci="Callospermophilus lateralis",kind="animal")
S("american-marten","American marten","weasel (mammal)",B,"conifer","smallmammals","A slender, agile climber of northern conifer forests, it chases voles and squirrels through the branches and hunts on the snow in winter.",sci="Martes americana",kind="animal")
S("southern-flying-squirrel","Southern flying squirrel","squirrel (mammal)",B,"forest","omni","Active at night, it glides from tree to tree on a furred flap of skin stretched between its legs.",sci="Glaucomys volans",kind="animal")
S("fox-squirrel","Fox squirrel","squirrel (mammal)",B,"forest","seeds","The largest tree squirrel in North America, it buries nuts one at a time, planting future trees it never returns to.",sci="Sciurus niger",kind="animal")
S("white-footed-mouse","White-footed mouse","mouse (mammal)",B,"forest","seeds","A common woodland mouse with white feet and belly, it caches seeds and nuts for the lean months.",sci="Peromyscus leucopus",kind="animal")
S("deer-mouse","Deer mouse","mouse (mammal)",B,"widespread","seeds","Big-eyed and wide-ranging, this native mouse lives in nearly every habitat across North America.",sci="Peromyscus maniculatus",kind="animal")
S("meadow-vole","Meadow vole","vole (mammal)",B,"meadow","herb","It mows tiny runways through the grass and is a crucial food source for hawks, owls, foxes and snakes.",sci="Microtus pennsylvanicus",kind="animal")
S("eastern-mole","Eastern mole","mole (mammal)",B,"soil","insects","It spends almost its whole life underground, swimming through soil with broad, shovel-shaped front paws.",sci="Scalopus aquaticus",kind="animal")
S("star-nosed-mole","Star-nosed mole","mole (mammal)",B,"wetland","insects","A ring of 22 pink feelers on its snout helps it find food, and it is one of the fastest-eating mammals known.",sci="Condylura cristata",kind="animal")
S("short-tailed-shrew","Northern short-tailed shrew","shrew (mammal)",B,"forest","insects","One of the very few venomous mammals, its toxic saliva can subdue prey larger than itself.",sci="Blarina brevicauda",kind="animal")
S("big-brown-bat","Big brown bat","bat (mammal)",B,"urban","insects","A hardy, widespread bat, it often roosts in attics and barns and hunts beetles and moths after dark.",sci="Eptesicus fuscus",kind="animal")
S("mexican-free-tailed-bat","Mexican free-tailed bat","bat (mammal)",B,"cave","insects","It gathers in colonies of millions and is one of the fastest-flying mammals, reaching high speeds in level flight.",sci="Tadarida brasiliensis",kind="animal")
S("hoary-bat","Hoary bat","bat (mammal)",B,"forest","insects","Named for its frost-tipped fur, this solitary bat migrates long distances and roosts alone in the trees.",sci="Lasiurus cinereus",kind="animal")
S("snowshoe-hare","Snowshoe hare","hare (mammal)",B,"conifer","browse","Its huge, furry hind feet act like snowshoes, and its coat turns from brown to white with the seasons.",sci="Lepus americanus",kind="animal")
S("black-tailed-jackrabbit","Black-tailed jackrabbit","hare (mammal)",B,"desert","herb","Not a rabbit but a hare, its enormous ears help it shed heat in the hot, open country where it lives.",sci="Lepus californicus",kind="animal")
S("mountain-goat","Mountain goat","hoofed mammal",B,"mountain","browse","With rubbery, gripping hoof pads it climbs near-vertical cliffs, living high above the treeline year round.",sci="Oreamnos americanus",kind="animal")
S("javelina","Collared peccary (javelina)","peccary (mammal)",B,"desert","omni","A pig-like animal of the Southwest, it travels in tight-knit herds and marks its group with a strong scent.",sci="Dicotyles tajacu",kind="animal")
S("canada-lynx","Canada lynx","cat (mammal)",B,"conifer","carn","With broad, furry paws like built-in snowshoes, it is a specialist hunter of the snowshoe hare.",sci="Lynx canadensis",kind="animal")
S("western-spotted-skunk","Western spotted skunk","skunk (mammal)",B,"edge","omni","Smaller and more agile than the striped skunk, it does a remarkable handstand to aim its spray.",sci="Spilogale gracilis",kind="animal")
