# -*- coding: utf-8 -*-
import gen_curriculum as g
S = g.S
B = "flora"
def T(sid,name,grp,hab,trait,sci): S(sid,name,grp,B,hab,"photosyn",trait,sci=sci,kind="tree")
T("quaking-aspen","Quaking aspen","aspen tree","mountain","Its leaves tremble in the lightest breeze on flattened stalks, and it spreads by roots into vast connected groves.","Populus tremuloides")
T("paper-birch","Paper birch","birch tree","conifer","Its peeling, papery white bark was used by Native peoples to build lightweight canoes.","Betula papyrifera")
T("eastern-cottonwood","Eastern cottonwood","cottonwood tree","riparian","A fast-growing riverside tree, it releases fluffy, cotton-like seeds that drift on the wind in early summer.","Populus deltoides")
T("american-sycamore","American sycamore","sycamore tree","riparian","Its patchy bark flakes away to reveal creamy white underneath, and old trunks are often hollow.","Platanus occidentalis")
T("tulip-tree","Tulip tree","tulip tree","forest","One of the tallest eastern hardwoods, it lifts greenish, tulip-shaped flowers high in its crown.","Liriodendron tulipifera")
T("american-beech","American beech","beech tree","forest","It has smooth, gray, elephant-skin bark, and young trees cling to their pale tan leaves all winter.","Fagus grandifolia")
T("shagbark-hickory","Shagbark hickory","hickory tree","forest","Mature bark peels away in long, shaggy vertical strips, and the tree bears sweet, edible nuts.","Carya ovata")
T("black-walnut","Black walnut","walnut tree","forest","Its roots release a natural chemical called juglone that discourages many other plants from growing nearby.","Juglans nigra")
T("white-ash","White ash","ash tree","forest","Once a common shade and baseball-bat tree, it is now under siege from the invasive emerald ash borer beetle.","Fraxinus americana")
T("american-elm","American elm","elm tree","urban","Its graceful vase shape once arched over city streets until Dutch elm disease swept many of them away.","Ulmus americana")
T("eastern-redbud","Eastern redbud","redbud tree","edge","Clusters of pink-purple flowers burst directly from its bare branches and trunk in early spring.","Cercis canadensis")
T("flowering-dogwood","Flowering dogwood","dogwood tree","understory","Its showy spring 'petals' are really leaf-like bracts surrounding the tiny true flowers in the center.","Cornus florida")
T("sweetgum","Sweetgum","sweetgum tree","forest","Its star-shaped leaves blaze red and purple in fall, and it drops hard, spiky seed balls.","Liquidambar styraciflua")
T("eastern-hemlock","Eastern hemlock","hemlock tree","conifer","A shade-loving evergreen, it is now threatened across much of its range by a tiny sap-sucking insect.","Tsuga canadensis")
T("balsam-fir","Balsam fir","fir tree","conifer","Prized as a Christmas tree, its smooth bark holds blisters of fragrant, sticky resin.","Abies balsamea")
T("red-spruce","Red spruce","spruce tree","mountain","A slow-growing evergreen of the high Appalachian and northeastern ridgetops.","Picea rubens")
T("eastern-red-cedar","Eastern red cedar","cedar tree","edge","Despite its name it is a juniper, bearing dusty-blue, berry-like cones that many birds eat.","Juniperus virginiana")
T("bald-cypress","Bald cypress","cypress tree","wetland","A conifer that sheds its needles each fall, it grows woody 'knees' up from its roots in southern swamps.","Taxodium distichum")
T("longleaf-pine","Longleaf pine","pine tree","conifer","It depends on fire and spends its first years as a grass-like tuft before suddenly shooting skyward.","Pinus palustris")
T("loblolly-pine","Loblolly pine","pine tree","forest","A fast-growing southern pine, it is one of the most important timber trees in the United States.","Pinus taeda")
T("ponderosa-pine","Ponderosa pine","pine tree","mountain","Its thick, puzzle-piece bark resists fire and smells of vanilla or butterscotch when warmed by the sun.","Pinus ponderosa")
T("lodgepole-pine","Lodgepole pine","pine tree","mountain","Many of its cones are sealed shut with resin and only pop open in the heat of a forest fire.","Pinus contorta")
T("douglas-fir","Douglas fir","fir tree","conifer","Not a true fir, it grows among the tallest of trees and has cones with distinctive three-pointed bracts.","Pseudotsuga menziesii")
T("coast-redwood","Coast redwood","redwood tree","wetforest","It is the tallest tree species on Earth, with some living giants standing over 110 meters high.","Sequoia sempervirens")
T("giant-sequoia","Giant sequoia","sequoia tree","mountain","By the sheer volume of its trunk, it is the largest living tree on the planet.","Sequoiadendron giganteum")
T("western-red-cedar","Western red cedar","cedar tree","wetforest","A giant of the Pacific Northwest, its rot-resistant wood was carved into canoes and totem poles.","Thuja plicata")
T("honey-locust","Honey locust","locust tree","edge","Wild trees guard their trunks and limbs with clusters of long, branching thorns.","Gleditsia triacanthos")
T("black-cherry","Black cherry","cherry tree","forest","Drooping white flower clusters become dark cherries that feed many birds and mammals.","Prunus serotina")
T("sassafras","Sassafras","sassafras tree","edge","A single tree can carry three leaf shapes at once: oval, two-lobed 'mitten,' and three-lobed.","Sassafras albidum")
T("pawpaw","Pawpaw","pawpaw tree","understory","It bears the largest edible fruit native to North America, with a soft, custardy, tropical flavor.","Asimina triloba")
